name: arc_ws/arc_ws__unplanned_water_supply_data_080__FP
stamp: '2019-05-14'
description: Arc Water Supply Unplanned
sos_model: water_supply_demand
scenarios:
  socio-economic: arc_unplanned
  water_demand_projections: final_planning_wrmp_2019
  reservoir_levels: predicted
  water_supply_data: water_supply_data_080 # Needed as input for preparing Wathnet nodal file
narratives: {}
timesteps:
- 2020
- 2021
- 2022
- 2023
- 2024
- 2025
- 2026
- 2027
- 2028
- 2029
- 2030
- 2031
- 2032
- 2033
- 2034
- 2035
- 2036
- 2037
- 2038
- 2039
- 2040
- 2041
- 2042
- 2043
- 2044
strategies: []
