name: arc_etmod-only__baseline
stamp: '2019-05-14'
description: Arc Energy-Transport baseline
sos_model: et_module
scenarios:
  ev_transport_trips: arc_baseline
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2030
  - 2050
