name: arc_ets__expansion
stamp: '2019-05-14'
description: Arc Energy-Transport Expansion
sos_model: energy_transport-scenario_corrected
scenarios:
  fuel_price: baseline
  socio-economic: arc_expansion
  temperature: NF1
  ev_transport_trips: arc_expansion
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices: average_annual_prices
narratives:
  operation_mode:
  - central
  virtual_dw_stock:
  - load_in_directly
  smart_meter_p:
  - electric_world
  t_base_heating:
  - electric_world
  f_eff_achieved:
  - electric_world
  generic_enduse_change:
  - electric_world
  generic_fuel_switch:
  - electric_world
  switches_service:
  - electric_world
strategies:
  - type: pre-specified-planning
    description: 'electric world development, decentral operation allowing expansion'
    filename: ../energy_supply/strategies/electric_world.csv
    model_name: energy_supply_constrained
timesteps:
  - 2015
  - 2030
  - 2050
