name: arc_ws__baseline
stamp: '2019-05-14'
description: Arc Water Supply baseline
sos_model: water_supply_only
scenarios: {}
narratives:
  virtual_dw_stock:
  - load_in_directly
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
