name: arc_dc__baseline
stamp: '2019-05-14'
description: Arc Digital baseline
sos_model: digital_comms_mobile_network
scenarios:
  adoption: fttp_baseline_adoption
  data_growth: baseline
  socio-economic: arc_baseline
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
