name: arc_ed__expansion__expand
stamp: '2019-05-14'
description: Arc Energy Demand expansion
sos_model: energy_demand_unconstrained
scenarios:
  socio-economic: arc_expansion__floor_area_expand
  temperature: NF1
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
