name: arc_et__expansion
stamp: '2019-05-14'
description: Arc Energy-Transport Expansion
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  gva: TODO
  population: TODO
  temperature: NF1
  ev_transport_trips: TODO
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
