name: arc_ws__unplanned
stamp: '2019-05-14'
description: Arc Water Supply Unplanned
sos_model: water_supply_only
scenarios: {}
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
