name: arc_et__expansion
stamp: '2019-05-14'
description: Arc Energy-Transport Expansion
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  socio-economic: arc_expansion
  temperature: NF1
  ev_transport_trips: TODO
  link_travel_time: default
  engine_type_fractions: baseline
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
