name: arc_et__expansion
stamp: '2019-05-14'
description: Arc Energy-Transport Expansion
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  socio-economic: arc_expansion
  temperature: NF1
  ev_transport_trips: TODO
  link_travel_time: default
  engine_type_fractions: baseline
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
narratives: 
  operation_mode:
  - decentral
  virtual_dw_stock:
  - load_in_directly
strategies:
  - type: pre-specified-planning
    description: 'electric world development, decentral operation allowing expansion'
    filename: ../energy_supply/strategies/electric_world.csv
    model_name: energy_supply_constrained
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
