name: arc_et__unplanned_green_gas
stamp: '2019-05-14'
description: Arc Energy-Transport Unplanned
sos_model: energy_transport-unconstrained_corrected
scenarios:
  fuel_price: baseline
  socio-economic: arc_unplanned
  temperature: NF1
  ev_transport_trips: TODO
  link_travel_time: default
  engine_type_fractions: baseline
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices: average_annual_prices
narratives:
  operation_mode:
  - central
  virtual_dw_stock:
  - load_in_directly
  heat_supply_strategy:
  - green_gas
  smart_meter_p:
  - electric_world
  t_base_heating:
  - electric_world
  f_eff_achieved:
  - electric_world
  generic_enduse_change:
  - electric_world
  generic_fuel_switch:
  - electric_world
  switches_service:
  - electric_world
strategies:
  - type: pre-specified-planning
    description: 'net zero development (national), centralised operation'
    filename: ../energy_supply/strategies/net_zero
    model_name: energy_supply_optimised
timesteps:
  - 2015
  - 2030
  - 2050
