name: arc_ed__expansion
stamp: '2019-05-14'
description: Arc Energy Demand Expansion
sos_model: energy_demand_unconstrained
scenarios:
  socio-economic: arc_expansion
  temperature: NF1
narratives:
  virtual_dw_stock:
    - load_in_directly
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
