name: arc_ed__unplanned__ew
stamp: '2019-05-14'
description: Arc Energy Demand Unplanned
sos_model: energy_demand_unconstrained
scenarios:
  socio-economic: arc_unplanned
  temperature: NF1
narratives:
  smart_meter_p:
    - electric_world
  t_base_heating:
    - electric_world
  f_eff_achieved:
    - electric_world
  generic_enduse_change:
    - electric_world
  generic_fuel_switch:
    - electric_world
  switches_service:
    - electric_world
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
