name: arc_et__unplanned
stamp: '2019-05-14'
description: Arc Energy-Transport Unplanned
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  socio-economic: arc_unplanned
  temperature: NF1
  ev_transport_trips: TODO
  link_travel_time: default
  engine_type_fractions: baseline
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices : average_annual_prices
narratives:
  operation_mode:
  - decentral
  virtual_dw_stock:
  - load_in_directly
strategies:
  - type: pre-specified-planning
    description: 'A multi-vector world, decentralised operation'
    filename: ../energy_supply/strategies/multi_vector.csv
    model_name: energy_supply_constrained
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
