name: arc_et__new-cities
stamp: '2019-05-14'
description: Arc Energy-Transport New Cities
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  socio-economic: arc_new-cities
  temperature: NF1
  ev_transport_trips: TODO
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
