name: arc_dc__new-cities
stamp: '2019-05-14'
description: Arc Digital New Cities
sos_model: digital_comms_mobile_network
scenarios:
  adoption: fttp_baseline_adoption
  data_growth: baseline
  socio-economic: arc_new-cities
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
