name: arc_et__baseline
stamp: '2019-05-14'
description: Arc Energy-Transport baseline
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  socio-economic: arc_baseline
  temperature: NF1
  ev_transport_trips: TODO
  link_travel_time: default
  engine_type_fractions: baseline
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices : average_annual_prices
narratives: 
  operation_mode:
  - central
strategies: 
  - type: pre-specified-planning
    description: 'electric world development, default centralised operation'
    filename: ../energy_supply/strategies/electric_world.csv
    model_name: energy_supply_constrained
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
