name: arc_dc__baseline
stamp: '2019-05-14'
description: Arc Digital baseline
sos_model: digital_comms_fixed_only
scenarios:
  adoption: fttp_baseline_adoption
narratives:
  virtual_dw_stock:
  - load_in_directly
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
