name: electricworld
stamp: ''
description: ''
sos_model: energy_sd_constrained
scenarios:
  fuel_price: es_prices_electric_world
  gva: gva_high
  population: pop_high
  temperature: NF1
  dummy_weather_inputs_full: es_dummy_weather_inputs_full 
narratives:
  load_shedding:
  - high_cost
  smart_meter_p:
  - electric_world
  t_base_heating:
  - electric_world
  f_eff_achieved:
  - electric_world
  generic_enduse_change:
  - electric_world
  generic_fuel_switch:
  - electric_world
  switches_service:
  - electric_world
decision_module: ''
strategies:
  - type: pre-specified-planning
    description: 'electric world test'
    filename: ../energy_supply/strategies/electric_world.csv
timesteps:
  - 2015
  - 2030
  - 2050
