decision_module: ''
description: ''
name: energy_supply_demand
narratives:
  mode:
  - constrained_mode
  load_shedding:
  - high_cost
scenarios:
  es_prices: es_prices_dummy
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
sos_model: energy_supply_demand
stamp: ''
timesteps:
- 2015
- 2030
- 2050
strategies: []
