decision_module: ''
description: ''
name: energy_demand_constrained__MULTIVECTOR_NF1__pop_baseline__gva_baseline
narratives:
  smart_meter_p:
  - multivector_narrative
  t_base_heating:
  - multivector_narrative
  f_eff_achieved:
  - multivector_narrative
  generic_enduse_change:
  - multivector_narrative
  heat_recovered:
  - multivector_narrative
  p_cold_rolling_steel:
  - multivector_narrative
  generic_fuel_switch:
  - multivector_narrative
  switches_service:
  - multivector_narrative
scenarios:
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
sos_model: energy_demand_constrained
stamp: ''
strategies: {}
timesteps:
- 2015
- 2030
- 2050