decision_module: ''
description: ''
name: energy_demand_constrained__CENTRAL_NF1__pop_low__gva_baseline
narratives:
  air_leakage:
  - central_narrative
  assump_diff_floorarea_pp:
  - central_narrative
  cooled_floorarea:
  - central_narrative
  dm_improvement:
  - central_narrative
  f_eff_achieved:
  - central_narrative
  generic_enduse_change:
  - central_narrative
  heat_recovered:
  - central_narrative
  t_base_heating:
  - central_narrative
  p_cold_rolling_steel:
  - central_narrative
  smart_meter_p:
  - central_narrative
  generic_fuel_switch:
  - central_narrative
scenarios:
  gva: gva_baseline
  population: pop_low
  temperature: NF1
  weather_station_coordinates: weather_station_coordinates__NF1
sos_model: energy_demand_constrained
stamp: ''
strategies: {}
timesteps:
- 2015
- 2050
