name: energy_sd_constrained
stamp: '2018-02-23T12:00:22.154Z'
description: ''
sos_model: energy_sd_constrained
scenarios:
  fuel_price: baseline
  socio-economic: itrc_baseline16
  temperature: NF1
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  dummy_energy_demands_full: es_energy_demand_dummy_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
narratives: {}
decision_module: ''
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
