decision_module: ''
description: ''
name: energy_supply_demand
narratives:
  load_shedding:
  - high_cost
scenarios:
  fuel_price: baseline
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
  weather_station_coordinates: weather_station_coordinates__NF1
sos_model: energy_supply_demand
stamp: '2018-02-23T12:00:22.154Z'
timesteps:
- 2015
- 2030
- 2050
strategies: []
