description: ''
name: energy_supply_constrained
narratives:
  load_shedding:
  - high_cost
scenarios:
  fuel_price: baseline
  dummy_energy_demands_full: es_energy_demand_dummy_full
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
sos_model: energy_supply_constrained
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
- 2020
strategies: []