name: energy_sd_optimised
stamp: '2018-04-11T12:00:00.000Z'
description: ''
sos_model: energy_sd_optimised
scenarios:
  fuel_price: baseline
  socio-economic: itrc_baseline16
  temperature: NF1
narratives: {}
decision_module: ''
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
