description: ''
name: energy_supply_test
narratives:
  load_shedding:
  - high_cost
scenarios:
  fuel_price: baseline
  dummy_energy_demands_full: es_energy_demand_dummy_full
sos_model: energy_supply_only
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
- 2020
strategies: []
