decision_module: ''
description: ''
name: energy_supply_toy
narratives: {}
scenarios:
  es_prices: es_prices_dummy
  dummy_energy_demands_minimal: es_energy_demand_minimal
sos_model: energy_supply_toy
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
strategies: {}
