name: energy_demand_constrained
stamp: ''
description: Run energy demand for baseline population scenario
sos_model: energy_demand_constrained
scenarios:
  socio-economic: itrc_baseline16
  temperature: NF1
narratives: {}
decision_module: ''
strategies: {}
timesteps:
- 2015
- 2020
- 2030
- 2050
