name: energy_demand_unconstrained
description: Run energy demand for baseline population scenario
stamp: '2017-11-07T14:15:00+00:00'
narratives: {}
timesteps:
- 2015
- 2030
- 2050
sos_model: energy_demand_unconstrained
decision_module: ''
scenarios:
  population: pop_baseline
  gva: gva_baseline
  temperature: NF1
strategies: {}
