decision_module: ''
description: ''
name: energy_supply_demand
narratives:
  load_shedding:
  - high_cost
scenarios:
  es_prices: es_prices_dummy
  gva: gva_baseline
  population: pop_low
  temperature: NF1
  weather_station_coordinates: weather_station_coordinates__NF1
sos_model: energy_supply_demand_update
stamp: '2018-02-23T12:00:22.154Z'
timesteps:
- 2015
- 2020
strategies: []
# - description: high_renewables
#   filename: high_renewables.yml
#   model_name: energy_supply
#   type: pre-specified-planning
