name: energy_transport
stamp: '2019-04-23'
description: 'Test model run for energy (supply-demand constrained) and transport'
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  socio-economic: itrc_baseline16
  temperature: NF1
  link_travel_time: default
  engine_type_fractions: baseline
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2030
  - 2050
