description: 'Runs the minimal energy supply model - expects the minimal data set loaded'
name: energy_supply_minimal
narratives:
  load_shedding:
  - high_cost
scenarios:
  fuel_price: baseline
  dummy_energy_demands_minimal: es_energy_demand_minimal
sos_model: energy_supply_toy
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
strategies: []
