name: energy_demand_constrained
stamp: ''
description: Run energy demand for baseline population scenario
sos_model: energy_demand_constrained
scenarios:
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
narratives: {}
decision_module: ''
strategies: {}
timesteps:
- 2015
- 2030
- 2050
