name: energy_transport-scenario
stamp: '2019-04-23'
description: 'Test model run for energy (supply-demand constrained) and et_module with transport energy demand scenario'
sos_model: energy_transport-scenario
scenarios:
  fuel_price: baseline
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
  ev_transport_trips: electricworld
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
narratives: 
  operation_mode:
  - central
strategies: []
timesteps:
  - 2015
  - 2030
  - 2050
