scenarios:
  fuel_price: baseline
  dummy_energy_demands_full: es_energy_demand_dummy_full
sos_model: energy_supply_optimised
name: energy_supply_agent
stamp: '2018-01-31T10:10:41.791Z'
narratives:
  load_shedding:
  - high_cost
description: Runs the minimal energy supply model with a decision module
strategies:
- type: rule-based
  description: reduce emissions
  path: planning/energyagent.py
  classname: EnergyAgent
timesteps:
- 2015
- 2020
