name: energy_sd_constrained
stamp: '2018-02-23T12:00:22.154Z'
description: ''
sos_model: energy_sd_constrained
scenarios:
  fuel_price: baseline
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
  dummy_energy_demands_full: es_energy_demand_dummy_full
narratives: {}
decision_module: ''
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
