decision_module: ''
description: Run energy demand for baseline population scenario
name: energy_demand_constrained
narratives:
  mode:
  - constrained_mode
scenarios:
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
sos_model: energy_demand_constrained
stamp: ''
strategies: {}
timesteps:
- 2015
- 2030
- 2050