description: ''
name: energy_supply_optimised
narratives:
  load_shedding:
  - high_cost
  operation_mode:
  - central
  heat_supply_strategy:
  - full_electric
scenarios:
  fuel_price: baseline
  dummy_energy_demands_full: es_energy_demand_dummy_optimised
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices: average_annual_prices
sos_model: energy_supply_optimised
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
- 2030
strategies: []
