narratives: 
  t_base_heating: 
    - central_narrative
  generic_enduse_change:
    - central_narrative
scenarios:
  gva_per_head: gva_baseline
  population: pop_low
  temperature: NF1
  weather_station_coordinates: weather_station_coordinates__NF1
strategies: {}
stamp: '2017-11-07T14:15:00+00:00'
timesteps:
- 2015
- 2050
name: energy_demand_constrained
description: Run energy demand for baseline population scenario
sos_model: energy_demand_constrained
decision_module: ''
