name: energy_transport
stamp: '2019-04-23'
description: 'Test model run for energy (supply-demand constrained) and transport'
sos_model: energy_transport
scenarios:
  fuel_price: baseline
  gva: gva_baseline
  population: pop_baseline
  temperature: NF1
  link_travel_time: default
  engine_type_fractions: baseline
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
narratives: 
  operation_mode:
  - central
strategies: []
timesteps:
  - 2015
  - 2030
  - 2050
