name: energy_sd_optimised
stamp: '2018-04-11T12:00:00.000Z'
description: ''
sos_model: energy_sd_optimised
scenarios:
  fuel_price: baseline
  socio-economic: itrc_baseline16
  temperature: NF1
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  dummy_energy_demands_full: es_energy_demand_dummy_full
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices: average_annual_prices
narratives: {}
decision_module: ''
strategies: []
timesteps:
  - 2015
  - 2020
  - 2030
  - 2050
