name: energy_demand_unconstrained
stamp: '2017-11-07T14:15:00+00:00'
description: Run energy demand for baseline population scenario
sos_model: energy_demand_unconstrained
scenarios:
  socio-economic: arc_baseline
  temperature: NF1
narratives:
  generic_enduse_change:
    - multivector_world
decision_module: ''
strategies: {}
timesteps:
- 2015
- 2020
- 2030
- 2050
