name: multivector_decentral
stamp: ''
description: ''
sos_model: energy_sd_constrained
scenarios:
  fuel_price: es_prices_multivector_world
  socio-economic: itrc_low-fcc
  temperature: NF1
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
narratives:
  load_shedding:
  - high_cost
  operation_mode:
  - decentral
  smart_meter_p:
  - multivector_world
  t_base_heating:
  - multivector_world
  f_eff_achieved:
  - multivector_world
  generic_enduse_change:
  - multivector_world
  generic_fuel_switch:
  - multivector_world
  switches_service:
  - multivector_world
decision_module: ''
strategies:
  - type: pre-specified-planning
    description: 'multi vector world'
    filename: ../energy_supply/strategies/multi_vector.csv
timesteps:
  - 2015
  - 2030
  - 2050
