name: multivector_heatnetwork_decentral_netzero_wind-increase
stamp: ''
description: ''
sos_model: energy_transport-scenario-unconstrained_corrected
scenarios:
  fuel_price: es_prices_multivector_world
  socio-economic: itrc_low-fcc
  temperature: NF1
  dummy_weather_inputs_full: es_dummy_weather_inputs_full
  ev_transport_trips: multivector_netzero
  biomass_waste_to_energy: es_biomass_waste_to_energy
  elec_interconnector_prices: average_annual_prices
narratives:
  load_shedding:
  - high_cost
  operation_mode:
  - decentral
  emissions_constraint:
  - emissions_constraint_on
  heat_supply_strategy:
  - heat_networks
  sensitivity_mode:
  - wind_increase
  smart_meter_p:
  - multivector_world
  t_base_heating:
  - multivector_world
  f_eff_achieved:
  - multivector_world_netzero
  generic_enduse_change:
  - multivector_world_netzero
  generic_fuel_switch:
  - multivector_world_netzero
  switches_service:
  - multivector_world_netzero_HeatNetworks
decision_module: ''
strategies:
  - type: pre-specified-planning
    description: 'net zero development (national), decentralised operation'
    filename: ../energy_supply/strategies/multi_vector
    model_name: energy_supply_optimised
timesteps:
  - 2015
  - 2050
