name: nic_ed
stamp: '2020-01-21'
description: 'Energy demand for NIC risk study'
sos_model: energy_demand_constrained
scenarios:
  socio-economic: arc_baseline_nia_pop
  temperature: NF1
narratives: {}
strategies: []
timesteps:
  - 2015
  - 2030
  - 2050
