name: rail_full_test
description: Baseline rail model run for testing
sos_model: rail_full
timesteps: [2015, 2020, 2030]
scenarios:
  socio-economic: itrc_baseline16
  station_usage: baseline
  rail_journey_times_fares: baseline
  car_zonal_journey_costs: baseline
  rail_trip_rates: baseline
narratives: {}
decision_module: []
strategies:
  - type: pre-specified-planning
    description: test interventions
    filename: transport_build_winslow
    model_name: rail
stamp: ''
