name: rail_southampton_test
description: Small baseline rail model run for testing
sos_model: rail_southampton
timesteps: [2015, 2020]
scenarios:
  socio-economic: itrc_baseline16
  station_usage: baseline
  rail_journey_times_fares_soton: baseline
  car_zonal_journey_costs: baseline
  rail_trip_rates: baseline
narratives: {}
decision_module: []
strategies:
  - type: pre-specified-planning
    description: test interventions
    filename: rail_test
    model_name: rail_southampton
stamp: ''
