name: rail_full_2015_2018_2030_2050
description: Baseline rail model run for testing
sos_model: rail_full
timesteps: [2015, 2018, 2030, 2050]
scenarios:
  socio-economic: itrc_baseline16
  station_usage: baseline
  rail_journey_times_fares: baseline
  car_zonal_journey_costs: baseline
  rail_trip_rates: baseline
narratives: {}
decision_module: []
strategies:
  - type: pre-specified-planning
    description: test interventions
    filename: transport_build_winslow.csv
    model_name: rail
stamp: ''
