decision_module: ''
description: Check that the et_module computes available storage capacity from grid-connected
  electric vehicles
name: test_et_module
narratives:
  default:
  - managed
scenarios:
  ev_transport_trips: central
sos_model: et_module
stamp: '2019-02-05T16:19:25.130Z'
timesteps:
- 2015
strategies: []
