name: transport_full_test
description: Baseline transport model run for testing
sos_model: transport_full
timesteps: [2015, 2020]
scenarios:
  population: pop_baseline
  gva: gva_baseline
  fuel_price: baseline
narratives: {}
decision_module: []
strategies: {}
stamp: ''
