name: transport_southampton_test
description: Small baseline transport model run for testing
sos_model: transport_southampton
timesteps: [2015, 2020]
scenarios:
  population: pop_baseline
  gva: gva_baseline
  fuel_price: baseline
  link_travel_time: default
  engine_type_fractions: baseline
narratives: {}
decision_module: []
strategies:
  - type: pre-specified-planning
    description: test interventions
    filename: transport_test.csv
    model_name: transport_southampton
stamp: ''
