name: transport_full_test
description: Baseline transport model run for testing
sos_model: transport_full
timesteps: [2015, 2020]
scenarios:
  socio-economic: itrc_baseline16
  fuel_price: baseline
  link_travel_time: default
  engine_type_fractions: baseline
narratives: {}
decision_module: []
strategies: []
stamp: ''
