description: 'Test model run for water supply and demand models'
name: water_supply_demand_test
narratives: {}
scenarios:
  water_demand_predicted: predicted  # Needed as input for water demand
  reservoir_levels: predicted  # Needed as input for initial timestep of water demand
  water_supply_data: predicted_2020_2050  # Needed as input for preparing Wathnet nodal file
sos_model: water_supply_demand
stamp: '2019-03-01T00:00:00.000Z'
timesteps:
- 2020
- 2021
strategies: []
