name: water_demand_test
description: Test water demand, and conversion from LAD
stamp: '2019-03-01T00:00:00.000Z'
sos_model: water_demand
scenarios:
  water_demand_projections: baseline
  socio-economic: arc_baseline
narratives: {}
timesteps:
- 2020
- 2021
- 2022
- 2023
strategies: []
