description: ''
name: water_supply_test
narratives: {}
scenarios:
  water_supply: water_supply_baseline
sos_model: water_supply_only
stamp: '2019-03-01T00:00:00.000Z'
timesteps:
- 2015
strategies: []
