description: Adoption curves for FTTP
provides:
- description: Adoption rate
  dtype: int
  name: adoption
  unit: '?'
  abs_range:
  - 0
  - 1000
  dims:
  - national
  sug_range:
  - 0
  - 100
variants:
- description: Baseline FTTP adoption for the UK
  data:
    adoption: ../digital_comms/scenarios/fttp_baseline_adoption
  name: fttp_baseline_adoption
- description: High FTTP adoption for the UK
  data:
    adoption: ../digital_comms/scenarios/fttp_high_adoption
  name: fttp_high_adoption
- description: Low FTTP adoption for the UK
  data:
    adoption: ../digital_comms/scenarios/fttp_low_adoption
  name: fttp_low_adoption
- description: Baseline FTTDP adoption for the UK
  data:
    adoption: ../digital_comms/scenarios/fttdp_baseline_adoption
  name: fttdp_baseline_adoption
- description: High FTTDP adoption for the UK
  data:
    adoption: ../digital_comms/scenarios/fttdp_high_adoption
  name: fttdp_high_adoption
- description: Low FTTDP adoption for the UK
  data:
    adoption: ../digital_comms/scenarios/fttdp_low_adoption
  name: fttdp_low_adoption
name: adoption
