variants:
- data:
    dwellings: dwellings/baseline.csv
  description: Baseline
  name: baseline
- data:
    dwellings: dwellings/unplanned.csv
  description: Unplanned
  name: unplanned
- data:
    dwellings: dwellings/expansion.csv
  description: Expansion
  name: expansion
- data:
    dwellings: dwellings/settlements.csv
  description: New Settlements
  name: new_settlements
description:
- data:
    dwellings: dwellings/baseline.csv
  description: Baseline
  name: baseline
- data:
    dwellings: dwellings/unplanned.csv
  description: Unplanned
  name: unplanned
- data:
    dwellings: dwellings/expansion.csv
  description: Expansion
  name: expansion
- data:
    dwellings: dwellings/settlements.csv
  description: New Settlements
  name: new_settlements
provides:
- name: dwellings
  dims:
  - lad_uk_2016
  dtype: int
  description: Project dwelling count by LAD
  unit: '-'
name: arc
