name: biomass_waste_to_energy
description: Biomass and waste data inputs for the energy supply model (full dataset)
provides:
  - name: biomass_feedstock
    description: 'biomass feedstock available in energy hub regions'
    dims:
    - energy_hub
    - seasons
    dtype: float
    unit: kg
  - name: municipal_waste
    description: 'biomass feedstock available in energy hub regions'
    dims:
    - energy_hub
    - seasons
    dtype: float
    unit: kg

variants:
  - name: es_biomass_waste_to_energy
    description: ''
    data:
      biomass_feedstock: ../energy_supply/scenarios/biomass_waste_energy_seasonal.csv
      municipal_waste: ../energy_supply/scenarios/biomass_waste_energy_seosonal.csv

