name: car_zonal_journey_costs
description: car zonal journey costs
provides:
  - name: car_zonal_journey_costs
    dims:
      - lad_gb_2016
    dtype: float
    unit: £
variants:
  - name: baseline
    description: Baseline car zonal journey costs
    data:
      car_zonal_journey_costs: rail_car_zonal_journey_costs.csv
