name: dummy_energy_demands_minimal
description: Dummy energy demand data for the energy supply model (minimal dataset)
provides:
  - name: elecload
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: gasload
    description: ''
    dims:
    - gas_nodes_minimal
    - seasonal_week
    dtype: float
    unit: mcm
  - name: residential_heatload
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: residential_gas_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: mcm
  - name: residential_electricity_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: service_heatload
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: service_gas_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: mcm
  - name: service_electricity_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
variants:
  - name: es_energy_demand_minimal
    description: ''
    data:
      elecload: ../energy_supply/scenarios/energy_demand_minimal
      gasload: ../energy_supply/scenarios/energy_demand_minimal_gasload
      residential_heatload: ../energy_supply/scenarios/energy_demand_minimal
      residential_gas_non_heating: ../energy_supply/scenarios/energy_demand_minimal
      residential_electricity_non_heating: ../energy_supply/scenarios/energy_demand_minimal
      service_heatload: ../energy_supply/scenarios/energy_demand_minimal
      service_gas_non_heating: ../energy_supply/scenarios/energy_demand_minimal
      service_electricity_non_heating: ../energy_supply/scenarios/energy_demand_minimal
