name: es_prices
description: Dummy data for energy_supply prices data
provides:
  - name: gas_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: electricity_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: gas_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: oil_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: coal_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: nuclearFuel_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: cost_of_carbon
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/Mt
variants:
  - name: es_prices_dummy
    description: Dummy prices data to pass to the energy_supply toy model
    data:
      gas_price: ../energy_supply/scenarios/price.csv
      #electricity_price: ../energy_supply/scenarios/price.csv
      oil_price: ../energy_supply/scenarios/price.csv
      coal_price: ../energy_supply/scenarios/price.csv
      nuclearFuel_price: ../energy_supply/scenarios/price.csv
      cost_of_carbon: ../energy_supply/scenarios/price.csv
  - name: es_prices_multivector_world
    description: Multivector prices data to pass to the energy_supply toy model
    data:
      gas_price: ../scenarios/prices/prices__multivector_world.csv
      oil_price: ../scenarios/prices/prices__multivector_world.csv
      coal_price: ../scenarios/prices/prices__multivector_world.csv
      nuclearFuel_price: ../scenarios/prices/prices__multivector_world.csv
      cost_of_carbon: ../scenarios/prices/prices__multivector_world.csv
  - name: es_prices_electric_world
    description: Electirc world prices data to pass to the energy_supply toy model
    data:
      gas_price: ../scenarios/prices/prices__electric_world.csv
      oil_price: ../scenarios/prices/prices__electric_world.csv
      coal_price: ../scenarios/prices/prices__electric_world.csv
      nuclearFuel_price: ../scenarios/prices/prices__electric_world.csv
      cost_of_carbon: ../scenarios/prices/prices__electric_world.csv