name: fuel_price
description: Fuel price scenarios for transport
provides:
  - name: fuel_price
    dims:
      - transport_fuel_type
    dtype: float
    unit: £/l
  - name: tr_fuel_price_electricity
    dtype: float
    unit: £/kWh
  - name: energy_supply_price
    description: ''
    dims:
      - seasons
      - es_fuel_types
    dtype: float
    unit: GBP/MWh
  - name: cost_of_carbon
    description: ''
    dims:
      - seasons
    dtype: float
    unit: GBP/Mt
variants:
  - name: baseline
    description: Baseline fuel price projections
    data:
      fuel_price: transport_fuel_price.csv
      fuel_price_electricity: transport_fuel_price_electricity.csv
      energy_supply_price: energy_supply_price.csv
      cost_of_carbon: cost_of_carbon.csv
