name: fuel_price
description: Fuel price scenarios for transport
provides:
  - name: fuel_price
    dims:
      - transport_fuel_type
    dtype: float
    unit: £/l
  - name: fuel_price_electricity
    dtype: float
    unit: £/kWh
  - name: energy_supply_price
    description: ''
    dims:
      - seasons
      - es_fuel_types
    dtype: float
    unit: GBP/MWh
variants:
  - name: baseline
    description: Baseline fuel price projections
    data:
      fuel_price: transport_fuel_price
      fuel_price_electricity: transport_fuel_price_electricity
      energy_supply_price: energy_supply_price
  - name: es_prices_electric_world
    description: electric world scenario fuel price projections
    data:
      fuel_price: transport_fuel_price
      fuel_price_electricity: transport_fuel_price_electricity
      energy_supply_price: prices/prices__electric_world
  - name: es_prices_multivector_world
    description: electric world scenario fuel price projections
    data:
      fuel_price: transport_fuel_price
      fuel_price_electricity: transport_fuel_price_electricity
      energy_supply_price: prices/prices_multivector_world
