name: gva
description: Gross value added
provides:
  - name: gva_per_head
    description: ''
    dims:
    - lad_uk_2016
    dtype: float
    unit: GBP
  - name: gva_per_sector
    dtype: float
    unit: GBP
    dims:
    - lad_uk_2016
    - sectors
    description: GVA per industrial sector
variants:
  - name: gva_baseline
    description: Baseline gva for the UK
    data:
      gva_per_head: ../energy_demand/scenarios/MISTRAL_pop_gva/data/pop-baseline16_econ-c16_fuel-c16/gva_per_head__lad.csv
      gva_per_sector: ../energy_demand/scenarios/MISTRAL_pop_gva/data/pop-baseline16_econ-c16_fuel-c16/gva_per_head__lad_sectors.csv