name: gva
description: Gross value added
provides:
  - name: gva
    description: ''
    dims:
    - lad_uk_2016
    dtype: float
    unit: GBP
variants:
  - name: gva_baseline
    description: Baseline gva for the UK
    data:
      gva: gva_sven.csv