name: gva
provides:
- name: gva
  dtype: float
  unit: GBP
  dims:
  - lad_uk_2016
  description: ''
- name: gva_per_sector
  dtype: float
  unit: GBP
  dims:
  - lad_uk_2016
  - sectors
  description: GVA per industrial sector
description: Gross value added
variants:
- name: gva_baseline
  description: Baseline gva for the UK
  data:
    gva: gva_sven.csv
    gva_per_sector: ''
