name: link_travel_time
description: Road link travel times for transport base year (currently mocked, not full data)
provides:
  - name: link_travel_time
    unit: h
    dtype: float
variants:
  - name: default
    description: Test data for transport base year
    data:
      link_travel_time: link_travel_time
