name: population
description: UK population, total people
provides:
  - name: population
    description: ''
    dims:
      - lad_uk_2016
    dtype: float
    unit: people
variants:
  - name: pop_baseline
    description: Baseline population for the UK
    data:
      population: population/pop-baseline16_econ-c16_fuel-c16/population__lad.csv
  - name: pop_high
    description: High population for the UK
    data:
      population: population/pop-d_econ-c_fuel-c/population__lad.csv
  - name: pop_low
    description: Low population for the UK
    data:
      population: population/pop-f_econ-c_fuel-c/population__lad.csv