name: socio-economic
description: Spatial scenarios for dwellings, floor area, employment, population, GVA
provides:
  - name: dwellings
    description: Dwelling count (treated as equivalent to number of households)
    dims:
      - lad_uk_2016
    dtype: int
    unit: count
  - name: floor_area
    description: Total floor area (residential/non)
    dims:
      - lad_uk_2016
      - residential_or_non
    dtype: float
    unit: meter**2
  - name: employment
    description: Employment
    dims:
      - lad_uk_2016
    dtype: int
    unit: person
  - name: gva
    description: Regional GVA
    dims:
      - lad_uk_2016
    dtype: float
    unit: GBP
  - name: gva_per_head
    description: Regional GVA per capita
    dims:
      - lad_uk_2016
    dtype: float
    unit: GBP
  - name: gva_per_sector
    description: GVA per industrial sector
    dims:
      - lad_uk_2016
      - sectors
    dtype: float
    unit: GBP
  - name: population
    description: Total population
    dims:
      - lad_uk_2016
    dtype: float
    unit: people
variants:
  - name: itrc_baseline16
    description: Baseline scenario used in ITRC NNA analysis
    data:
      dwellings: socio-economic/arc_dwellings__baseline
      floor_area: socio-economic/arc_floor_area__baseline
      employment: socio-economic/arc_employment__baseline
      gva: socio-economic/arc_gva__baseline
      gva_per_head: population/pop-baseline16_econ-c16_fuel-c16/gva_per_head__lad
      gva_per_sector: population/pop-baseline16_econ-c16_fuel-c16/gva_per_head__lad_sectors
      population: population/pop-baseline16_econ-c16_fuel-c16/population__lad
  - name: itrc_high-dcc
    description: High scenario used in ITRC analysis
    data:
      dwellings: socio-economic/arc_dwellings__baseline
      floor_area: socio-economic/arc_floor_area__baseline
      employment: socio-economic/arc_employment__baseline
      gva: socio-economic/arc_gva__baseline
      gva_per_head: population/pop-d_econ-c_fuel-c/gva_per_head__lad
      gva_per_sector: population/pop-d_econ-c_fuel-c/gva_per_head__lad_sectors
      population: population/pop-d_econ-c_fuel-c/population__lad
  - name: itrc_low-fcc
    description: Low scenario used in ITRC analysis
    data:
      dwellings: socio-economic/arc_dwellings__baseline
      floor_area: socio-economic/arc_floor_area__baseline
      employment: socio-economic/arc_employment__baseline
      gva: socio-economic/arc_gva__baseline
      gva_per_head: population/pop-f_econ-c_fuel-c/gva_per_head__lad
      gva_per_sector: population/pop-f_econ-c_fuel-c/gva_per_head__lad_sectors
      population: population/pop-f_econ-c_fuel-c/population__lad
  - name: arc_baseline
    description: Baseline scenario for Cam-MK-Ox Arc analysis
    data:
      dwellings: socio-economic/arc_dwellings__baseline
      floor_area: socio-economic/arc_floor_area__baseline
      employment: socio-economic/arc_employment__baseline
      gva: socio-economic/arc_gva__baseline
      gva_per_head: socio-economic/arc_gva_per_head__baseline
      gva_per_sector: socio-economic/arc_gva_by_sector_for_energy_demand__baseline
      population: socio-economic/arc_population__baseline
  - name: arc_unplanned
    description: Unplanned scenario for Cam-MK-Ox Arc analysis
    data:
      dwellings: socio-economic/arc_dwellings__0-unplanned
      floor_area: socio-economic/arc_floor_area__0-unplanned
      employment: socio-economic/arc_employment__0-unplanned
      gva: socio-economic/arc_gva__0-unplanned
      gva_per_head: socio-economic/arc_gva_per_head__0-unplanned
      gva_per_sector: socio-economic/arc_gva_by_sector_for_energy_demand__0-unplanned
      population: socio-economic/arc_population__0-unplanned
  - name: arc_new-cities
    description: New cities scenario for Cam-MK-Ox Arc analysis
    data:
      dwellings: socio-economic/arc_dwellings__1-new-cities
      floor_area: socio-economic/arc_floor_area__1-new-cities
      employment: socio-economic/arc_employment__1-new-cities
      gva: socio-economic/arc_gva__1-new-cities
      gva_per_head: socio-economic/arc_gva_per_head__1-new-cities
      gva_per_sector: socio-economic/arc_gva_by_sector_for_energy_demand__1-new-cities
      population: socio-economic/arc_population__1-new-cities
  - name: arc_expansion
    description: Expansion of current major cities scenario for Cam-MK-Ox Arc analysis
    data:
      dwellings: socio-economic/arc_dwellings__2-expansion
      floor_area: socio-economic/arc_floor_area__2-expansion
      employment: socio-economic/arc_employment__2-expansion
      gva: socio-economic/arc_gva__2-expansion
      gva_per_head: socio-economic/arc_gva_per_head__2-expansion
      gva_per_sector: socio-economic/arc_gva_by_sector_for_energy_demand__2-expansion
      population: socio-economic/arc_population__2-expansion
  - name: arc_new-cities23
    description: New cities scenario for Cam-MK-Ox Arc analysis with 23K dwelling per year
    data:
      dwellings: socio-economic/arc_dwellings__3-new-cities23
      floor_area: socio-economic/arc_floor_area__3-new-cities23
      employment: socio-economic/arc_gva_employment__1-new-cities
      gva: socio-economic/arc_gva_employment__1-new-cities
      gva_per_head: socio-economic/arc_gva_per_head__3-new-cities23
      gva_per_sector: socio-economic/arc_gva_by_sector_for_energy_demand__1-new-cities
      population: socio-economic/arc_population__3-new-cities23
  - name: arc_expansion23
    description: Expansion of current major cities scenario for Cam-MK-Ox Arc analysis with 23K dwelling per year
    data:
      dwellings: socio-economic/arc_dwellings__4-expansion23
      floor_area: socio-economic/arc_floor_area__4-expansion23
      employment: socio-economic/arc_gva_employment__2-expansion
      gva: socio-economic/arc_gva_employment__2-expansion
      gva_per_head: socio-economic/arc_gva_per_head__4-expansion23
      gva_per_sector: socio-economic/arc_gva_by_sector_for_energy_demand__2-expansion
      population: socio-economic/arc_population__4-expansion23
