name: station_usage
description: Station usage (rail demand) for rail model
provides:
  - name: day_usage
    dims:
      - NLC_gb
    dtype: float
    unit: people
  - name: year_usage
    dims:
      - NLC_gb
    dtype: float
    unit: people
variants:
  - name: baseline
    description: Baseline rail demand prediction
    data:
      day_usage: rail_day_usage.csv
      year_usage: rail_year_usage.csv
