name: temperature
description: Temperatuer description
provides:
  - name: t_min
    description: 'Minimum daily temperature'
    dims:
      - station_id
      - yearday
    dtype: float
    unit: Degree Celcius
  - name: t_max
    description: 'Minimum daily temperature'
    dims:
      - station_id
      - yearday
    dtype: float
    unit: Degree Celcius
variants:
  - name: default_temperature
    description: Temperature description
    data:
      t_min: weather_data_NF1.csv #weather_data_NF1.parquet #test_temps.csv
      t_max: weather_data_NF1.csv #weather_data_NF1.parquet #test_temps.csv
