name: temperature
description: Minimum and maximum daily temperature projections from the Weather@Home project
provides:
  - name: t_min
    description: 'Minimum daily temperature'
    dims:
      - lad_uk_2016
      - yearday
    dtype: float
    unit: Degree Celcius
  - name: t_max
    description: 'Maximum daily temperature'
    dims:
      - lad_uk_2016
      - yearday
    dtype: float
    unit: Degree Celcius
variants:
  - data:
      t_max: climate/t_max__NF1
      t_min: climate/t_min__NF1
    description: Weather realisation NF1
    name: NF1
  # - data:
  #     t_max: climate/t_max__NF2
  #     t_min: climate/t_min__NF2
  #   description: Weather realisation NF2
  #   name: NF2
  # - data:
  #     t_max: climate/t_max__NF3
  #     t_min: climate/t_min__NF3
  #   description: Weather realisation NF3
  #   name: NF3
  # - data:
  #     t_max: climate/t_max__NF4
  #     t_min: climate/t_min__NF4
  #   description: Weather realisation NF4
  #   name: NF4
  # - data:
  #     t_max: climate/t_max__NF5
  #     t_min: climate/t_min__NF5
  #   description: Weather realisation NF5
  #   name: NF5
  # - data:
  #     t_max: climate/t_max__NF6
  #     t_min: climate/t_min__NF6
  #   description: Weather realisation NF6
  #   name: NF6
  # - data:
  #     t_max: climate/t_max__NF7
  #     t_min: climate/t_min__NF7
  #   description: Weather realisation NF7
  #   name: NF7
  # - data:
  #     t_max: climate/t_max__NF8
  #     t_min: climate/t_min__NF8
  #   description: Weather realisation NF8
  #   name: NF8
  # - data:
  #     t_max: climate/t_max__NF9
  #     t_min: climate/t_min__NF9
  #   description: Weather realisation NF9
  #   name: NF9
  # - data:
  #     t_max: climate/t_max__NF10
  #     t_min: climate/t_min__NF10
  #   description: Weather realisation NF10
  #   name: NF10
  # - data:
  #     t_max: climate/t_max__NF11
  #     t_min: climate/t_min__NF11
  #   description: Weather realisation NF11
  #   name: NF11
  # - data:
  #     t_max: climate/t_max__NF12
  #     t_min: climate/t_min__NF12
  #   description: Weather realisation NF12
  #   name: NF12
  # - data:
  #     t_max: climate/t_max__NF13
  #     t_min: climate/t_min__NF13
  #   description: Weather realisation NF13
  #   name: NF13
  # - data:
  #     t_max: climate/t_max__NF14
  #     t_min: climate/t_min__NF14
  #   description: Weather realisation NF14
  #   name: NF14
  # - data:
  #     t_max: climate/t_max__NF15
  #     t_min: climate/t_min__NF15
  #   description: Weather realisation NF15
  #   name: NF15
  # - data:
  #     t_max: climate/t_max__NF16
  #     t_min: climate/t_min__NF16
  #   description: Weather realisation NF16
  #   name: NF16
  # - data:
  #     t_max: climate/t_max__NF17
  #     t_min: climate/t_min__NF17
  #   description: Weather realisation NF17
  #   name: NF17
  # - data:
  #     t_max: climate/t_max__NF18
  #     t_min: climate/t_min__NF18
  #   description: Weather realisation NF18
  #   name: NF18
  # - data:
  #     t_max: climate/t_max__NF19
  #     t_min: climate/t_min__NF19
  #   description: Weather realisation NF19
  #   name: NF19
  # - data:
  #     t_max: climate/t_max__NF20
  #     t_min: climate/t_min__NF20
  #   description: Weather realisation NF20
  #   name: NF20
  # - data:
  #     t_max: climate/t_max__NF21
  #     t_min: climate/t_min__NF21
  #   description: Weather realisation NF21
  #   name: NF21
  # - data:
  #     t_max: climate/t_max__NF22
  #     t_min: climate/t_min__NF22
  #   description: Weather realisation NF22
  #   name: NF22
  # - data:
  #     t_max: climate/t_max__NF23
  #     t_min: climate/t_min__NF23
  #   description: Weather realisation NF23
  #   name: NF23
  # - data:
  #     t_max: climate/t_max__NF24
  #     t_min: climate/t_min__NF24
  #   description: Weather realisation NF24
  #   name: NF24
  # - data:
  #     t_max: climate/t_max__NF25
  #     t_min: climate/t_min__NF25
  #   description: Weather realisation NF25
  #   name: NF25
  # - data:
  #     t_max: climate/t_max__NF26
  #     t_min: climate/t_min__NF26
  #   description: Weather realisation NF26
  #   name: NF26
  # - data:
  #     t_max: climate/t_max__NF27
  #     t_min: climate/t_min__NF27
  #   description: Weather realisation NF27
  #   name: NF27
  # - data:
  #     t_max: climate/t_max__NF28
  #     t_min: climate/t_min__NF28
  #   description: Weather realisation NF28
  #   name: NF28
  # - data:
  #     t_max: climate/t_max__NF29
  #     t_min: climate/t_min__NF29
  #   description: Weather realisation NF29
  #   name: NF29
  # - data:
  #     t_max: climate/t_max__NF30
  #     t_min: climate/t_min__NF30
  #   description: Weather realisation NF30
  #   name: NF30
  # - data:
  #     t_max: climate/t_max__NF31
  #     t_min: climate/t_min__NF31
  #   description: Weather realisation NF31
  #   name: NF31
  # - data:
  #     t_max: climate/t_max__NF32
  #     t_min: climate/t_min__NF32
  #   description: Weather realisation NF32
  #   name: NF32
  # - data:
  #     t_max: climate/t_max__NF33
  #     t_min: climate/t_min__NF33
  #   description: Weather realisation NF33
  #   name: NF33
  # - data:
  #     t_max: climate/t_max__NF34
  #     t_min: climate/t_min__NF34
  #   description: Weather realisation NF34
  #   name: NF34
  # - data:
  #     t_max: climate/t_max__NF35
  #     t_min: climate/t_min__NF35
  #   description: Weather realisation NF35
  #   name: NF35
  # - data:
  #     t_max: climate/t_max__NF36
  #     t_min: climate/t_min__NF36
  #   description: Weather realisation NF36
  #   name: NF36
  # - data:
  #     t_max: climate/t_max__NF37
  #     t_min: climate/t_min__NF37
  #   description: Weather realisation NF37
  #   name: NF37
  # - data:
  #     t_max: climate/t_max__NF38
  #     t_min: climate/t_min__NF38
  #   description: Weather realisation NF38
  #   name: NF38
  # - data:
  #     t_max: climate/t_max__NF39
  #     t_min: climate/t_min__NF39
  #   description: Weather realisation NF39
  #   name: NF39
  # - data:
  #     t_max: climate/t_max__NF40
  #     t_min: climate/t_min__NF40
  #   description: Weather realisation NF40
  #   name: NF40
  # - data:
  #     t_max: climate/t_max__NF41
  #     t_min: climate/t_min__NF41
  #   description: Weather realisation NF41
  #   name: NF41
  # - data:
  #     t_max: climate/t_max__NF42
  #     t_min: climate/t_min__NF42
  #   description: Weather realisation NF42
  #   name: NF42
  # - data:
  #     t_max: climate/t_max__NF43
  #     t_min: climate/t_min__NF43
  #   description: Weather realisation NF43
  #   name: NF43
  # - data:
  #     t_max: climate/t_max__NF44
  #     t_min: climate/t_min__NF44
  #   description: Weather realisation NF44
  #   name: NF44
  # - data:
  #     t_max: climate/t_max__NF45
  #     t_min: climate/t_min__NF45
  #   description: Weather realisation NF45
  #   name: NF45
  # - data:
  #     t_max: climate/t_max__NF46
  #     t_min: climate/t_min__NF46
  #   description: Weather realisation NF46
  #   name: NF46
  # - data:
  #     t_max: climate/t_max__NF47
  #     t_min: climate/t_min__NF47
  #   description: Weather realisation NF47
  #   name: NF47
  # - data:
  #     t_max: climate/t_max__NF48
  #     t_min: climate/t_min__NF48
  #   description: Weather realisation NF48
  #   name: NF48
  # - data:
  #     t_max: climate/t_max__NF49
  #     t_min: climate/t_min__NF49
  #   description: Weather realisation NF49
  #   name: NF49
  # - data:
  #     t_max: climate/t_max__NF50
  #     t_min: climate/t_min__NF50
  #   description: Weather realisation NF50
  #   name: NF50
  # - data:
  #     t_max: climate/t_max__NF51
  #     t_min: climate/t_min__NF51
  #   description: Weather realisation NF51
  #   name: NF51
  # - data:
  #     t_max: climate/t_max__NF52
  #     t_min: climate/t_min__NF52
  #   description: Weather realisation NF52
  #   name: NF52
  # - data:
  #     t_max: climate/t_max__NF53
  #     t_min: climate/t_min__NF53
  #   description: Weather realisation NF53
  #   name: NF53
  # - data:
  #     t_max: climate/t_max__NF54
  #     t_min: climate/t_min__NF54
  #   description: Weather realisation NF54
  #   name: NF54
  # - data:
  #     t_max: climate/t_max__NF55
  #     t_min: climate/t_min__NF55
  #   description: Weather realisation NF55
  #   name: NF55
  # - data:
  #     t_max: climate/t_max__NF56
  #     t_min: climate/t_min__NF56
  #   description: Weather realisation NF56
  #   name: NF56
  # - data:
  #     t_max: climate/t_max__NF57
  #     t_min: climate/t_min__NF57
  #   description: Weather realisation NF57
  #   name: NF57
  # - data:
  #     t_max: climate/t_max__NF58
  #     t_min: climate/t_min__NF58
  #   description: Weather realisation NF58
  #   name: NF58
  # - data:
  #     t_max: climate/t_max__NF59
  #     t_min: climate/t_min__NF59
  #   description: Weather realisation NF59
  #   name: NF59
  # - data:
  #     t_max: climate/t_max__NF60
  #     t_min: climate/t_min__NF60
  #   description: Weather realisation NF60
  #   name: NF60
  # - data:
  #     t_max: climate/t_max__NF61
  #     t_min: climate/t_min__NF61
  #   description: Weather realisation NF61
  #   name: NF61
  # - data:
  #     t_max: climate/t_max__NF62
  #     t_min: climate/t_min__NF62
  #   description: Weather realisation NF62
  #   name: NF62
  # - data:
  #     t_max: climate/t_max__NF63
  #     t_min: climate/t_min__NF63
  #   description: Weather realisation NF63
  #   name: NF63
  # - data:
  #     t_max: climate/t_max__NF64
  #     t_min: climate/t_min__NF64
  #   description: Weather realisation NF64
  #   name: NF64
  # - data:
  #     t_max: climate/t_max__NF65
  #     t_min: climate/t_min__NF65
  #   description: Weather realisation NF65
  #   name: NF65
  # - data:
  #     t_max: climate/t_max__NF66
  #     t_min: climate/t_min__NF66
  #   description: Weather realisation NF66
  #   name: NF66
  # - data:
  #     t_max: climate/t_max__NF67
  #     t_min: climate/t_min__NF67
  #   description: Weather realisation NF67
  #   name: NF67
  # - data:
  #     t_max: climate/t_max__NF68
  #     t_min: climate/t_min__NF68
  #   description: Weather realisation NF68
  #   name: NF68
  # - data:
  #     t_max: climate/t_max__NF69
  #     t_min: climate/t_min__NF69
  #   description: Weather realisation NF69
  #   name: NF69
  # - data:
  #     t_max: climate/t_max__NF70
  #     t_min: climate/t_min__NF70
  #   description: Weather realisation NF70
  #   name: NF70
  # - data:
  #     t_max: climate/t_max__NF71
  #     t_min: climate/t_min__NF71
  #   description: Weather realisation NF71
  #   name: NF71
  # - data:
  #     t_max: climate/t_max__NF72
  #     t_min: climate/t_min__NF72
  #   description: Weather realisation NF72
  #   name: NF72
  # - data:
  #     t_max: climate/t_max__NF73
  #     t_min: climate/t_min__NF73
  #   description: Weather realisation NF73
  #   name: NF73
  # - data:
  #     t_max: climate/t_max__NF74
  #     t_min: climate/t_min__NF74
  #   description: Weather realisation NF74
  #   name: NF74
  # - data:
  #     t_max: climate/t_max__NF75
  #     t_min: climate/t_min__NF75
  #   description: Weather realisation NF75
  #   name: NF75
  # - data:
  #     t_max: climate/t_max__NF76
  #     t_min: climate/t_min__NF76
  #   description: Weather realisation NF76
  #   name: NF76
  # - data:
  #     t_max: climate/t_max__NF77
  #     t_min: climate/t_min__NF77
  #   description: Weather realisation NF77
  #   name: NF77
  # - data:
  #     t_max: climate/t_max__NF78
  #     t_min: climate/t_min__NF78
  #   description: Weather realisation NF78
  #   name: NF78
  # - data:
  #     t_max: climate/t_max__NF79
  #     t_min: climate/t_min__NF79
  #   description: Weather realisation NF79
  #   name: NF79
  # - data:
  #     t_max: climate/t_max__NF80
  #     t_min: climate/t_min__NF80
  #   description: Weather realisation NF80
  #   name: NF80
  # - data:
  #     t_max: climate/t_max__NF81
  #     t_min: climate/t_min__NF81
  #   description: Weather realisation NF81
  #   name: NF81
  # - data:
  #     t_max: climate/t_max__NF82
  #     t_min: climate/t_min__NF82
  #   description: Weather realisation NF82
  #   name: NF82
  # - data:
  #     t_max: climate/t_max__NF83
  #     t_min: climate/t_min__NF83
  #   description: Weather realisation NF83
  #   name: NF83
  # - data:
  #     t_max: climate/t_max__NF84
  #     t_min: climate/t_min__NF84
  #   description: Weather realisation NF84
  #   name: NF84
  # - data:
  #     t_max: climate/t_max__NF85
  #     t_min: climate/t_min__NF85
  #   description: Weather realisation NF85
  #   name: NF85
  # - data:
  #     t_max: climate/t_max__NF86
  #     t_min: climate/t_min__NF86
  #   description: Weather realisation NF86
  #   name: NF86
  # - data:
  #     t_max: climate/t_max__NF87
  #     t_min: climate/t_min__NF87
  #   description: Weather realisation NF87
  #   name: NF87
  # - data:
  #     t_max: climate/t_max__NF88
  #     t_min: climate/t_min__NF88
  #   description: Weather realisation NF88
  #   name: NF88
  # - data:
  #     t_max: climate/t_max__NF89
  #     t_min: climate/t_min__NF89
  #   description: Weather realisation NF89
  #   name: NF89
  # - data:
  #     t_max: climate/t_max__NF90
  #     t_min: climate/t_min__NF90
  #   description: Weather realisation NF90
  #   name: NF90
  # - data:
  #     t_max: climate/t_max__NF91
  #     t_min: climate/t_min__NF91
  #   description: Weather realisation NF91
  #   name: NF91
  # - data:
  #     t_max: climate/t_max__NF92
  #     t_min: climate/t_min__NF92
  #   description: Weather realisation NF92
  #   name: NF92
  # - data:
  #     t_max: climate/t_max__NF93
  #     t_min: climate/t_min__NF93
  #   description: Weather realisation NF93
  #   name: NF93
  # - data:
  #     t_max: climate/t_max__NF94
  #     t_min: climate/t_min__NF94
  #   description: Weather realisation NF94
  #   name: NF94
  # - data:
  #     t_max: climate/t_max__NF95
  #     t_min: climate/t_min__NF95
  #   description: Weather realisation NF95
  #   name: NF95
  # - data:
  #     t_max: climate/t_max__NF96
  #     t_min: climate/t_min__NF96
  #   description: Weather realisation NF96
  #   name: NF96
  # - data:
  #     t_max: climate/t_max__NF97
  #     t_min: climate/t_min__NF97
  #   description: Weather realisation NF97
  #   name: NF97
  # - data:
  #     t_max: climate/t_max__NF98
  #     t_min: climate/t_min__NF98
  #   description: Weather realisation NF98
  #   name: NF98
  # - data:
  #     t_max: climate/t_max__NF99
  #     t_min: climate/t_min__NF99
  #   description: Weather realisation NF99
  #   name: NF99
  # - data:
  #     t_max: climate/t_max__NF100
  #     t_min: climate/t_min__NF100
  #   description: Weather realisation NF100
  #   name: NF100
