name: temperature
description: Temperatuer description
provides:
  - name: t_min
    description: 'Minimum daily temperature'
    dims:
      - station_ids
      - weather_inst
      - yearday
    dtype: float
    unit: Degree Celcius
  - name: t_max
    description: 'Minimum daily temperature'
    dims:
      - station_ids
      - weather_inst
      - yearday
    dtype: float
    unit: Degree Celcius
variants:
  - name: default_temperature
    description: Temperature description
    data:
      t_min: test_temps.csv
      t_max: test_temps.csv
