name: temperature
description: Minimum and maximum daily temperature projections from the Weather@Home project
provides:
  - name: t_min
    description: 'Minimum daily temperature'
    dims:
      - lad_uk_2016
      - yearday
    dtype: float
    unit: Degree Celcius
  - name: t_max
    description: 'Maximum daily temperature'
    dims:
      - lad_uk_2016
      - yearday
    dtype: float
    unit: Degree Celcius
variants:
  - data:
      t_max: climate/t_max__NF1.csv
      t_min: climate/t_min__NF1.csv
    description: Weather realisation NF1
    name: NF1
  - data:
      t_max: climate/t_max__NF2.csv
      t_min: climate/t_min__NF2.csv
    description: Weather realisation NF2
    name: NF2
  - data:
      t_max: climate/t_max__NF3.csv
      t_min: climate/t_min__NF3.csv
    description: Weather realisation NF3
    name: NF3
  - data:
      t_max: climate/t_max__NF4.csv
      t_min: climate/t_min__NF4.csv
    description: Weather realisation NF4
    name: NF4
  - data:
      t_max: climate/t_max__NF5.csv
      t_min: climate/t_min__NF5.csv
    description: Weather realisation NF5
    name: NF5
  - data:
      t_max: climate/t_max__NF6.csv
      t_min: climate/t_min__NF6.csv
    description: Weather realisation NF6
    name: NF6
  - data:
      t_max: climate/t_max__NF7.csv
      t_min: climate/t_min__NF7.csv
    description: Weather realisation NF7
    name: NF7
  - data:
      t_max: climate/t_max__NF8.csv
      t_min: climate/t_min__NF8.csv
    description: Weather realisation NF8
    name: NF8
  - data:
      t_max: climate/t_max__NF9.csv
      t_min: climate/t_min__NF9.csv
    description: Weather realisation NF9
    name: NF9
  - data:
      t_max: climate/t_max__NF10.csv
      t_min: climate/t_min__NF10.csv
    description: Weather realisation NF10
    name: NF10
  - data:
      t_max: climate/t_max__NF11.csv
      t_min: climate/t_min__NF11.csv
    description: Weather realisation NF11
    name: NF11
  - data:
      t_max: climate/t_max__NF12.csv
      t_min: climate/t_min__NF12.csv
    description: Weather realisation NF12
    name: NF12
  - data:
      t_max: climate/t_max__NF13.csv
      t_min: climate/t_min__NF13.csv
    description: Weather realisation NF13
    name: NF13
  - data:
      t_max: climate/t_max__NF14.csv
      t_min: climate/t_min__NF14.csv
    description: Weather realisation NF14
    name: NF14
  - data:
      t_max: climate/t_max__NF15.csv
      t_min: climate/t_min__NF15.csv
    description: Weather realisation NF15
    name: NF15
  - data:
      t_max: climate/t_max__NF16.csv
      t_min: climate/t_min__NF16.csv
    description: Weather realisation NF16
    name: NF16
  - data:
      t_max: climate/t_max__NF17.csv
      t_min: climate/t_min__NF17.csv
    description: Weather realisation NF17
    name: NF17
  - data:
      t_max: climate/t_max__NF18.csv
      t_min: climate/t_min__NF18.csv
    description: Weather realisation NF18
    name: NF18
  - data:
      t_max: climate/t_max__NF19.csv
      t_min: climate/t_min__NF19.csv
    description: Weather realisation NF19
    name: NF19
  - data:
      t_max: climate/t_max__NF20.csv
      t_min: climate/t_min__NF20.csv
    description: Weather realisation NF20
    name: NF20
  - data:
      t_max: climate/t_max__NF21.csv
      t_min: climate/t_min__NF21.csv
    description: Weather realisation NF21
    name: NF21
  - data:
      t_max: climate/t_max__NF22.csv
      t_min: climate/t_min__NF22.csv
    description: Weather realisation NF22
    name: NF22
  - data:
      t_max: climate/t_max__NF23.csv
      t_min: climate/t_min__NF23.csv
    description: Weather realisation NF23
    name: NF23
  - data:
      t_max: climate/t_max__NF24.csv
      t_min: climate/t_min__NF24.csv
    description: Weather realisation NF24
    name: NF24
  - data:
      t_max: climate/t_max__NF25.csv
      t_min: climate/t_min__NF25.csv
    description: Weather realisation NF25
    name: NF25
  - data:
      t_max: climate/t_max__NF26.csv
      t_min: climate/t_min__NF26.csv
    description: Weather realisation NF26
    name: NF26
  - data:
      t_max: climate/t_max__NF27.csv
      t_min: climate/t_min__NF27.csv
    description: Weather realisation NF27
    name: NF27
  - data:
      t_max: climate/t_max__NF28.csv
      t_min: climate/t_min__NF28.csv
    description: Weather realisation NF28
    name: NF28
  - data:
      t_max: climate/t_max__NF29.csv
      t_min: climate/t_min__NF29.csv
    description: Weather realisation NF29
    name: NF29
  - data:
      t_max: climate/t_max__NF30.csv
      t_min: climate/t_min__NF30.csv
    description: Weather realisation NF30
    name: NF30
  - data:
      t_max: climate/t_max__NF31.csv
      t_min: climate/t_min__NF31.csv
    description: Weather realisation NF31
    name: NF31
  - data:
      t_max: climate/t_max__NF32.csv
      t_min: climate/t_min__NF32.csv
    description: Weather realisation NF32
    name: NF32
  - data:
      t_max: climate/t_max__NF33.csv
      t_min: climate/t_min__NF33.csv
    description: Weather realisation NF33
    name: NF33
  - data:
      t_max: climate/t_max__NF34.csv
      t_min: climate/t_min__NF34.csv
    description: Weather realisation NF34
    name: NF34
  - data:
      t_max: climate/t_max__NF35.csv
      t_min: climate/t_min__NF35.csv
    description: Weather realisation NF35
    name: NF35
  - data:
      t_max: climate/t_max__NF36.csv
      t_min: climate/t_min__NF36.csv
    description: Weather realisation NF36
    name: NF36
  - data:
      t_max: climate/t_max__NF37.csv
      t_min: climate/t_min__NF37.csv
    description: Weather realisation NF37
    name: NF37
  - data:
      t_max: climate/t_max__NF38.csv
      t_min: climate/t_min__NF38.csv
    description: Weather realisation NF38
    name: NF38
  - data:
      t_max: climate/t_max__NF39.csv
      t_min: climate/t_min__NF39.csv
    description: Weather realisation NF39
    name: NF39
  - data:
      t_max: climate/t_max__NF40.csv
      t_min: climate/t_min__NF40.csv
    description: Weather realisation NF40
    name: NF40
  - data:
      t_max: climate/t_max__NF41.csv
      t_min: climate/t_min__NF41.csv
    description: Weather realisation NF41
    name: NF41
  - data:
      t_max: climate/t_max__NF42.csv
      t_min: climate/t_min__NF42.csv
    description: Weather realisation NF42
    name: NF42
  - data:
      t_max: climate/t_max__NF43.csv
      t_min: climate/t_min__NF43.csv
    description: Weather realisation NF43
    name: NF43
  - data:
      t_max: climate/t_max__NF44.csv
      t_min: climate/t_min__NF44.csv
    description: Weather realisation NF44
    name: NF44
  - data:
      t_max: climate/t_max__NF45.csv
      t_min: climate/t_min__NF45.csv
    description: Weather realisation NF45
    name: NF45
  - data:
      t_max: climate/t_max__NF46.csv
      t_min: climate/t_min__NF46.csv
    description: Weather realisation NF46
    name: NF46
  - data:
      t_max: climate/t_max__NF47.csv
      t_min: climate/t_min__NF47.csv
    description: Weather realisation NF47
    name: NF47
  - data:
      t_max: climate/t_max__NF48.csv
      t_min: climate/t_min__NF48.csv
    description: Weather realisation NF48
    name: NF48
  - data:
      t_max: climate/t_max__NF49.csv
      t_min: climate/t_min__NF49.csv
    description: Weather realisation NF49
    name: NF49
  - data:
      t_max: climate/t_max__NF50.csv
      t_min: climate/t_min__NF50.csv
    description: Weather realisation NF50
    name: NF50
  - data:
      t_max: climate/t_max__NF51.csv
      t_min: climate/t_min__NF51.csv
    description: Weather realisation NF51
    name: NF51
  - data:
      t_max: climate/t_max__NF52.csv
      t_min: climate/t_min__NF52.csv
    description: Weather realisation NF52
    name: NF52
  - data:
      t_max: climate/t_max__NF53.csv
      t_min: climate/t_min__NF53.csv
    description: Weather realisation NF53
    name: NF53
  - data:
      t_max: climate/t_max__NF54.csv
      t_min: climate/t_min__NF54.csv
    description: Weather realisation NF54
    name: NF54
  - data:
      t_max: climate/t_max__NF55.csv
      t_min: climate/t_min__NF55.csv
    description: Weather realisation NF55
    name: NF55
  - data:
      t_max: climate/t_max__NF56.csv
      t_min: climate/t_min__NF56.csv
    description: Weather realisation NF56
    name: NF56
  - data:
      t_max: climate/t_max__NF57.csv
      t_min: climate/t_min__NF57.csv
    description: Weather realisation NF57
    name: NF57
  - data:
      t_max: climate/t_max__NF58.csv
      t_min: climate/t_min__NF58.csv
    description: Weather realisation NF58
    name: NF58
  - data:
      t_max: climate/t_max__NF59.csv
      t_min: climate/t_min__NF59.csv
    description: Weather realisation NF59
    name: NF59
  - data:
      t_max: climate/t_max__NF60.csv
      t_min: climate/t_min__NF60.csv
    description: Weather realisation NF60
    name: NF60
  - data:
      t_max: climate/t_max__NF61.csv
      t_min: climate/t_min__NF61.csv
    description: Weather realisation NF61
    name: NF61
  - data:
      t_max: climate/t_max__NF62.csv
      t_min: climate/t_min__NF62.csv
    description: Weather realisation NF62
    name: NF62
  - data:
      t_max: climate/t_max__NF63.csv
      t_min: climate/t_min__NF63.csv
    description: Weather realisation NF63
    name: NF63
  - data:
      t_max: climate/t_max__NF64.csv
      t_min: climate/t_min__NF64.csv
    description: Weather realisation NF64
    name: NF64
  - data:
      t_max: climate/t_max__NF65.csv
      t_min: climate/t_min__NF65.csv
    description: Weather realisation NF65
    name: NF65
  - data:
      t_max: climate/t_max__NF66.csv
      t_min: climate/t_min__NF66.csv
    description: Weather realisation NF66
    name: NF66
  - data:
      t_max: climate/t_max__NF67.csv
      t_min: climate/t_min__NF67.csv
    description: Weather realisation NF67
    name: NF67
  - data:
      t_max: climate/t_max__NF68.csv
      t_min: climate/t_min__NF68.csv
    description: Weather realisation NF68
    name: NF68
  - data:
      t_max: climate/t_max__NF69.csv
      t_min: climate/t_min__NF69.csv
    description: Weather realisation NF69
    name: NF69
  - data:
      t_max: climate/t_max__NF70.csv
      t_min: climate/t_min__NF70.csv
    description: Weather realisation NF70
    name: NF70
  - data:
      t_max: climate/t_max__NF71.csv
      t_min: climate/t_min__NF71.csv
    description: Weather realisation NF71
    name: NF71
  - data:
      t_max: climate/t_max__NF72.csv
      t_min: climate/t_min__NF72.csv
    description: Weather realisation NF72
    name: NF72
  - data:
      t_max: climate/t_max__NF73.csv
      t_min: climate/t_min__NF73.csv
    description: Weather realisation NF73
    name: NF73
  - data:
      t_max: climate/t_max__NF74.csv
      t_min: climate/t_min__NF74.csv
    description: Weather realisation NF74
    name: NF74
  - data:
      t_max: climate/t_max__NF75.csv
      t_min: climate/t_min__NF75.csv
    description: Weather realisation NF75
    name: NF75
  - data:
      t_max: climate/t_max__NF76.csv
      t_min: climate/t_min__NF76.csv
    description: Weather realisation NF76
    name: NF76
  - data:
      t_max: climate/t_max__NF77.csv
      t_min: climate/t_min__NF77.csv
    description: Weather realisation NF77
    name: NF77
  - data:
      t_max: climate/t_max__NF78.csv
      t_min: climate/t_min__NF78.csv
    description: Weather realisation NF78
    name: NF78
  - data:
      t_max: climate/t_max__NF79.csv
      t_min: climate/t_min__NF79.csv
    description: Weather realisation NF79
    name: NF79
  - data:
      t_max: climate/t_max__NF80.csv
      t_min: climate/t_min__NF80.csv
    description: Weather realisation NF80
    name: NF80
  - data:
      t_max: climate/t_max__NF81.csv
      t_min: climate/t_min__NF81.csv
    description: Weather realisation NF81
    name: NF81
  - data:
      t_max: climate/t_max__NF82.csv
      t_min: climate/t_min__NF82.csv
    description: Weather realisation NF82
    name: NF82
  - data:
      t_max: climate/t_max__NF83.csv
      t_min: climate/t_min__NF83.csv
    description: Weather realisation NF83
    name: NF83
  - data:
      t_max: climate/t_max__NF84.csv
      t_min: climate/t_min__NF84.csv
    description: Weather realisation NF84
    name: NF84
  - data:
      t_max: climate/t_max__NF85.csv
      t_min: climate/t_min__NF85.csv
    description: Weather realisation NF85
    name: NF85
  - data:
      t_max: climate/t_max__NF86.csv
      t_min: climate/t_min__NF86.csv
    description: Weather realisation NF86
    name: NF86
  - data:
      t_max: climate/t_max__NF87.csv
      t_min: climate/t_min__NF87.csv
    description: Weather realisation NF87
    name: NF87
  - data:
      t_max: climate/t_max__NF88.csv
      t_min: climate/t_min__NF88.csv
    description: Weather realisation NF88
    name: NF88
  - data:
      t_max: climate/t_max__NF89.csv
      t_min: climate/t_min__NF89.csv
    description: Weather realisation NF89
    name: NF89
  - data:
      t_max: climate/t_max__NF90.csv
      t_min: climate/t_min__NF90.csv
    description: Weather realisation NF90
    name: NF90
  - data:
      t_max: climate/t_max__NF91.csv
      t_min: climate/t_min__NF91.csv
    description: Weather realisation NF91
    name: NF91
  - data:
      t_max: climate/t_max__NF92.csv
      t_min: climate/t_min__NF92.csv
    description: Weather realisation NF92
    name: NF92
  - data:
      t_max: climate/t_max__NF93.csv
      t_min: climate/t_min__NF93.csv
    description: Weather realisation NF93
    name: NF93
  - data:
      t_max: climate/t_max__NF94.csv
      t_min: climate/t_min__NF94.csv
    description: Weather realisation NF94
    name: NF94
  - data:
      t_max: climate/t_max__NF95.csv
      t_min: climate/t_min__NF95.csv
    description: Weather realisation NF95
    name: NF95
  - data:
      t_max: climate/t_max__NF96.csv
      t_min: climate/t_min__NF96.csv
    description: Weather realisation NF96
    name: NF96
  - data:
      t_max: climate/t_max__NF97.csv
      t_min: climate/t_min__NF97.csv
    description: Weather realisation NF97
    name: NF97
  - data:
      t_max: climate/t_max__NF98.csv
      t_min: climate/t_min__NF98.csv
    description: Weather realisation NF98
    name: NF98
  - data:
      t_max: climate/t_max__NF99.csv
      t_min: climate/t_min__NF99.csv
    description: Weather realisation NF99
    name: NF99
  - data:
      t_max: climate/t_max__NF100.csv
      t_min: climate/t_min__NF100.csv
    description: Weather realisation NF100
    name: NF100