name: transport_energy_demand
description: Hourly electricity demand of transport model
provides:
  - name: electricity
    description: ''
    dims:
    - lad_gb_2016
    dtype: float
    unit: GWh
variants:
  - name: et_demand_baseline
    description: Baseline GWh of transport for the UK
    data:
      electricity: et_demand_electricity.csv
