name: water_supply_data
description: Data for water supply model
provides:
  - name: flows_data
    description: Data related to flows
    dims:
    - water_supply/days_into_year
    - water_supply/flow_file_column_names
    dtype: float
    unit: Ml/day
variants:
  - name: predicted_2020_2050
    description: Predicted water supply data
    data:
      flows_data: water_supply/flows_data
