name: water_demand_predicted
description: Predicted population and water demand for water resource zones, 2020-2044
provides:
  - name: population
    description: Population of water resource zones
    dims:
    - water_resource_zones
    dtype: float
    unit: thousands of people
  - name: constant_water_demand
    description: Constant demand for each water resource zone
    dims:
    - water_resource_zones
    dtype: float
    unit: Ml/day
  - name: per_capita_water_demand
    description: Demand per thousand people for each water resource zone
    dims:
    - water_resource_zones
    dtype: float
    unit: Ml/(thousand people)/day
variants:
  - name: predicted
    description: Predicted population and water demand for water resource zones, 2020-2044
    data:
      population: water_demand/water_resource_zone_populations
      constant_water_demand: water_demand/constant_water_demand
      per_capita_water_demand: water_demand/per_capita_water_demand
