name: technology
description: Describes the evolution of technology
provides:
- name: High Tech Demand Side Management
  description: High penetration of SMART technology on the demand side
  dtype: float
  unit: TODO
variants:
- name: test_narrative
  description: TODO
  data:
    High Tech Demand Side Management: high_tech_dsm.yml
    test_narrative: high_tech_dsm.yml
