classname: AggregateInputs
description: Aggregates energy demand outputs for energy supply residential heatload
initial_conditions: []
inputs:
- name: residential_gas_boiler_gas
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- name: residential_electricity_boiler_electricity
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- name: residential_gas_stirling_micro_gas
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- name: residential_electricity_heat_pumps_electricity
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- name: residential_electricity_district_heating_electricity
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- name: residential_gas_district_heating_CHP_gas
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
interventions: []
name: aggregate_residential_heatload
outputs:
- name: residential_heatload
  units: MW
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
parameters: []
path: models/aggregate.py
