classname: AggregateInputs
description: 'Aggregates industry gas and biomass energy demand outputs for energy supply input gasload'
initial_conditions: []
inputs:
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_boiler_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_biomass_boiler_biomass
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_stirling_micro_CHP_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_district_heating_CHP_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_biomass_district_heating_biomass
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_non_heating
  spatial_resolution: energy_hub
interventions: []
name: aggregate_gasload
outputs:
- name: gasload
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: mcm
parameters: []
path: models/aggregate.py
