classname: AggregateInputs
description: Aggregates energy demand outputs for energy supply service heatload
initial_conditions: []
inputs:
- name: service_gas_boiler_gas
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_electricity_boiler_electricity
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_electricity_heat_pumps_electricity
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_gas_district_heating_gas
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_electricity_district_heating_electricity
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_gas_stirling_micro_gas
  units: MW
  dims:
  - energy_hub
  dtype: TODO
interventions: []
name: aggregate_service_heatload
outputs:
- name: service_heatload
  units: MW
  dims:
  - energy_hub
  dtype: TODO
parameters: []
path: models/aggregate.py
