classname: AggregateInputs
description: 'Aggregates energy demand outputs for energy supply transmission elecload '
initial_conditions: []
inputs:
- name: industry_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
interventions: []
name: aggregate_elecload
outputs:
- name: elecload
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
parameters: []
path: models/aggregate.py
