classname: AggregateInputs
description: Aggregates energy demand outputs for energy supply service heatload
initial_conditions: []
inputs:
- name: service_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_district_heating_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
interventions: []
name: aggregate_service_heatload
outputs:
- name: service_heatload
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
parameters: []
path: models/aggregate.py
