classname: AggregateInputs
description: 'Aggregates energy demand outputs for energy supply transmission elecload '
initial_conditions: []
inputs:
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_boiler_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_heat_pumps_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_district_heating_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_non_heating
  spatial_resolution: energy_hub
interventions: []
name: aggregate_elecload
outputs:
- name: elecload
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
parameters: []
path: models/aggregate.py
