classname: AggregateInputs
description: Aggregates industry gas and biomass energy demand outputs for energy
  supply input gasload
initial_conditions: []
inputs:
- units: mcm
  name: industry_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_biomass_boiler_biomass
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_biomass_district_heating_biomass
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
interventions: []
name: aggregate_gasload
outputs:
- name: gasload
  units: mcm
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
parameters: []
path: models/aggregate.py
