classname: ConvertDemandToSupply
description: Converts the spatial and temporal resolution of outputs from energy_demand_toy
  to those required at the inputs to energy_supply_toy
initial_conditions: []
inputs:
# --------------- From energy demand
- name: residential_gas_boiler_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_electricity_boiler_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_electricity_heat_pumps_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_gas_district_heating_CHP_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_electricity_district_heating_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_gas_stirling_micro_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_gas_boiler_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_electricity_boiler_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_electricity_heat_pumps_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_gas_district_heating_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_electricity_district_heating_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_gas_stirling_micro_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_gas_boiler_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_electricity_boiler_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_biomass_boiler_biomass
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_electricity_heat_pumps_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_gas_district_heating_CHP_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_electricity_district_heating_electricity
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_biomass_district_heating_biomass
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_gas_stirling_micro_CHP_gas
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_gas_non_heating
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: residential_electricity_non_heating
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_gas_non_heating
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: service_electricity_non_heating
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_gas_non_heating
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
- name: industry_electricity_non_heating
  spatial_resolution: lad_uk_2016
  temporal_resolution: hourly
  units: GW
interventions: []
name: convert_ed_to_es
outputs:
- temporal_resolution: seasonal_week
  units: MW
  name: residential_gas_boiler_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_electricity_boiler_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_gas_stirling_micro_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_electricity_heat_pumps_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_electricity_district_heating_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_gas_district_heating_CHP_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_gas_non_heating
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: residential_electricity_non_heating
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_gas_boiler_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_electricity_boiler_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_gas_stirling_micro_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_electricity_heat_pumps_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_electricity_district_heating_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_gas_district_heating_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_gas_non_heating
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: service_electricity_non_heating
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_boiler_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_boiler_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_biomass_boiler_biomass
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_stirling_micro_CHP_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_heat_pumps_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_district_heating_electricity
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_district_heating_CHP_gas
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_biomass_district_heating_biomass
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: mcm
  name: industry_gas_non_heating
  spatial_resolution: energy_hub
- temporal_resolution: seasonal_week
  units: MW
  name: industry_electricity_non_heating
  spatial_resolution: energy_hub
- temporal_resolution: annual
  units: GBP/Mt
  name: cost_of_carbon
  spatial_resolution: national
- temporal_resolution: annual
  units: GBP/MWh
  name: electricity_price
  spatial_resolution: national
- temporal_resolution: annual
  units: GBP/MWh
  name: gas_price
  spatial_resolution: national
- temporal_resolution: annual
  units: GBP/MWh
  name: nuclearFuel_price
  spatial_resolution: national
- temporal_resolution: annual
  units: GBP/MWh
  name: oil_price
  spatial_resolution: national
- temporal_resolution: annual
  units: GBP/MWh
  name: coal_price
  spatial_resolution: national
parameters: []
path: models/convert.py
