name: convert_units_ed_to_es_optimised
description: Performs a unit conversion of the energy demand data from GW to either MW or mcm
path: models/convert.py
classname: ConvertGWMW
initial_conditions: []
inputs:
  - name: gasload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: elecload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: heatload_res
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: gasload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: elecload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: heatload_com
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: gasload
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: elecload
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: hydrogen_non_heat_eh
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
interventions: []
outputs:
  - name: gasload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: elecload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: heatload_res
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: gasload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: elecload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: heatload_com
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: gasload
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: elecload
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: hydrogen_non_heat_eh
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
parameters: []
