classname: ConvertDemandToSupply
description: Converts the spatial and temporal resolution of outputs from energy_demand_toy
  to those required at the inputs to energy_supply_toy
initial_conditions: []
inputs:
# --------------- From energy demand
- name: residential_gas_boiler_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_electricity_boiler_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_electricity_heat_pumps_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_gas_district_heating_CHP_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_electricity_district_heating_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_gas_stirling_micro_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_gas_boiler_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_electricity_boiler_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_electricity_heat_pumps_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_gas_district_heating_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_electricity_district_heating_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_gas_stirling_micro_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_gas_boiler_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_electricity_boiler_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_biomass_boiler_biomass
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_electricity_heat_pumps_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_gas_district_heating_CHP_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_electricity_district_heating_electricity
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_biomass_district_heating_biomass
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_gas_stirling_micro_CHP_gas
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_gas_non_heating
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: residential_electricity_non_heating
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_gas_non_heating
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: service_electricity_non_heating
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_gas_non_heating
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
- name: industry_electricity_non_heating
  units: GW
  dims:
  - lad_uk_2016
  - hourly
  dtype: float
interventions: []
name: convert_ed_to_es
outputs:
- units: MW
  name: residential_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: residential_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: residential_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: residential_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: residential_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: residential_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: residential_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: residential_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_gas_district_heating_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: service_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: service_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: industry_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_biomass_boiler_biomass
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: industry_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: industry_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_biomass_district_heating_biomass
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: mcm
  name: industry_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
- units: MW
  name: industry_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
parameters: []
path: models/convert.py
