name: convert_units_tr_to_es
description: Interval conversion
path: models/convert.py
classname: ConvertGWMW
inputs:
  - name: electric_vehicle_electricity_consumption
    dims:
      - seasonal_week
      - energy_hub
    unit: kWh
    dtype: float
  - name: v2g_g2v_capacity
    dims:
      - energy_hub
    unit: kW
    dtype: float
outputs:
  - name: electric_vehicle_electricity_consumption
    dims:
      - seasonal_week
      - energy_hub
    unit: MWh
    dtype: float
  - name: v2g_g2v_capacity
    dims:
      - energy_hub
    unit: MW
    dtype: float
parameters: []
interventions: []
initial_conditions: []
