classname: ConvertHourlyToSeasonalWeek
description: Performs a spatial aggregation of the energy demand data assuming a uniform spatial distribution
initial_conditions: []
inputs:
- name: residential_gas_boiler_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_electricity_boiler_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_electricity_district_heating_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_gas_boiler_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_electricity_boiler_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_electricity_district_heating_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_gas_boiler_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_electricity_boiler_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_biomass_boiler_biomass
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_electricity_district_heating_electricity
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_biomass_district_heating_biomass
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_gas_non_heating
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: residential_electricity_non_heating
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_gas_non_heating
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: service_electricity_non_heating
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_gas_non_heating
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
- name: industry_electricity_non_heating
  dims:
  - energy_hub
  - hourly
  unit: GW
  dtype: float
interventions: []
name: convert_intervals_ed_to_es
outputs:
- name: residential_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_biomass_boiler_biomass
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_biomass_district_heating_biomass
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
parameters: []
path: models/convert.py
