name: convert_regions_tr_to_es
description: Region conversion
path: models/convert.py
classname: ConvertLADtoEnergyHub
inputs:
  - name: electric_vehicle_electricity_consumption
    dims:
      - lad_gb_2016
      - annual_day_hours
    unit: kWh
    dtype: float
  - name: hydrogen_vehicle_hydrogen_consumption
    dims:
      - lad_gb_2016
      - annual_day_hours
    unit: kWh
    dtype: float
  - name: v2g_g2v_capacity
    dims:
      - lad_gb_2016
    unit: kW
    dtype: float
outputs:
  - name: electric_vehicle_electricity_consumption
    dims:
      - energy_hub
      - annual_day_hours
    unit: kWh
    dtype: float
  - name: hydrogen_vehicle_hydrogen_consumption
    dims:
      - energy_hub
      - annual_day_hours
    unit: kWh
    dtype: float
  - name: v2g_g2v_capacity
    dims:
      - energy_hub
    unit: kW
    dtype: float
parameters: []
interventions: []
initial_conditions: []
