classname: ConvertLADtoEnergyHub
inputs:
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_gas_boiler_gas
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_electricity_boiler_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_electricity_heat_pumps_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_gas_district_heating_CHP_gas
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_electricity_district_heating_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_gas_boiler_gas
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_electricity_boiler_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_electricity_heat_pumps_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_gas_district_heating_gas
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_electricity_district_heating_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_gas_boiler_gas
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_electricity_boiler_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_biomass_boiler_biomass
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_electricity_heat_pumps_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_gas_district_heating_CHP_gas
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_electricity_district_heating_electricity
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_biomass_district_heating_biomass
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_gas_non_heating
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: residential_electricity_non_heating
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_gas_non_heating
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: service_electricity_non_heating
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_gas_non_heating
  unit: GW
- dims:
  - lad_uk_2016
  - hourly
  dtype: float
  name: industry_electricity_non_heating
  unit: GW
parameters: []
outputs:
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_gas_boiler_gas
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_electricity_boiler_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_electricity_heat_pumps_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_gas_district_heating_CHP_gas
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_electricity_district_heating_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_gas_boiler_gas
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_electricity_boiler_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_electricity_heat_pumps_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_gas_district_heating_gas
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_electricity_district_heating_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_gas_boiler_gas
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_electricity_boiler_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_biomass_boiler_biomass
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_electricity_heat_pumps_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_gas_district_heating_CHP_gas
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_electricity_district_heating_electricity
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_biomass_district_heating_biomass
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_gas_non_heating
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: residential_electricity_non_heating
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_gas_non_heating
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: service_electricity_non_heating
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_gas_non_heating
  unit: GW
- dims:
  - energy_hub
  - hourly
  dtype: float
  name: industry_electricity_non_heating
  unit: GW
description: Performs a spatial aggregation of the energy demand data assuming a uniform
  spatial distribution
name: convert_regions_ed_to_es
interventions: []
initial_conditions: []
path: models/convert.py
