classname: ConvertGWMW
description: Performs a unit conversion of the energy demand data from GW to either MW or mcm
initial_conditions: []
inputs:
# --------------- From energy demand
- name: residential_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_district_heating_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_biomass_boiler_biomass
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_biomass_district_heating_biomass
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: residential_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: service_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
- name: industry_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: GW
  dtype: float
interventions: []
name: convert_units_ed_to_es
outputs:
- name: residential_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: residential_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: residential_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: residential_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: residential_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: residential_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_district_heating_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_stirling_micro_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_gas_boiler_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: industry_electricity_boiler_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_biomass_boiler_biomass
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: industry_electricity_heat_pumps_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_gas_district_heating_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: industry_electricity_district_heating_electricity
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_biomass_district_heating_biomass
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: industry_gas_stirling_micro_CHP_gas
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: residential_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: residential_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: service_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
- name: industry_gas_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: mcm
  dtype: float
- name: industry_electricity_non_heating
  dims:
  - energy_hub
  - seasonal_week
  unit: MW
  dtype: float
parameters: []
path: models/convert.py
