name: convert_units_ed_to_es_constrained
description: Performs a unit conversion of the energy demand data from GW to either MW or mcm
path: models/convert.py
classname: ConvertGWMW
initial_conditions: []
inputs:
  - name: building_biomass_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: building_elec_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: building_gas_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: building_heatpump
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: building_hydrogen_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: building_hydrogen_heatpump
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: building_oil_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: dh_biomass_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: dh_elec_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: dh_gas_CHP
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: dh_hydrogen_fuelcell
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: elecload
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: elecload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: elecload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: gasload
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: gasload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: gasload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
  - name: hydrogen_non_heat_eh
    dims:
      - energy_hub
      - seasonal_week
    unit: GW
    dtype: float
interventions: []
outputs:
  - name: building_biomass_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: building_elec_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: building_gas_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: building_heatpump
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: building_hydrogen_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: building_hydrogen_heatpump
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: building_oil_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: dh_biomass_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: dh_elec_boiler
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: dh_gas_CHP
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: dh_hydrogen_fuelcell
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: elecload
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: elecload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: elecload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
  - name: gasload
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: gasload_non_heat_com
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: gasload_non_heat_res
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
  - name: hydrogen_non_heat_eh
    dims:
      - energy_hub
      - seasonal_week
    unit: MW
    dtype: float
parameters: []
