parameters:
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  description: The cost of installing a fiber link
  abs_range:
  - 0
  - 1000
  name: costs_links_fiber_meter
  unit: GBP
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The cost of installing a copper link
  name: costs_links_copper_meter
  abs_range:
  - 0
  - 1000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable an exchange to service FTTP
  name: costs_assets_exchange_fttp
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable an exchange to service GFast
  name: costs_assets_exchange_gfast
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable an exchange to service FTTC
  name: costs_assets_exchange_fttc
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable an exchange to service ADSL
  name: costs_assets_exchange_adsl
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a cabinet to service FTTP
  name: costs_assets_cabinet_fttp_32_ports
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a cabinet to service GFast
  name: costs_assets_cabinet_gfast
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a cabinet to service FTTC
  name: costs_assets_cabinet_fttc
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a cabinet to service ADSL
  name: costs_assets_cabinet_adsl
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a distribution to service FTTP
  name: costs_assets_distribution_fttp_32_ports
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a distribution to service GFast
  name: costs_assets_distribution_gfast_4_ports
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a distribution to service FTTC
  name: costs_assets_distribution_fttc
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a distribution to service ADSL
  name: costs_assets_distribution_adsl
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a premise to receive FTTP
  name: costs_assets_premise_fttp_modem
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a premise to receive FTTP
  name: costs_assets_premise_fttp_optical_network_terminator
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a premise to receive GFast
  name: costs_assets_premise_gfast_modem
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a premise to receive FTTC
  name: costs_assets_premise_fttc_modem
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The costs to enable a premise to receive ADSL
  name: costs_assets_premise_adsl_modem
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The benefits to enable a premise to receive FTTP
  name: benefits_assets_premise_fttp
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The benefits to enable a premise to receive GFast
  name: benefits_assets_premise_gfast
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The benefits to enable a premise to receive FTTC
  name: benefits_assets_premise_fttc
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The benefits to enable a premise to receive ADSL
  name: benefits_assets_premise_adsl
  abs_range:
  - 0
  - 100000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: The yearly budget to spend on infrastructure
  name: annual_budget
  abs_range:
  - 0
  - 100000000
- default: ../digital_comms/parameters/defaults.csv
  dims: []
  dtype: int
  unit: GBP
  description: Service obligation capacity
  name: service_obligation_capacity
  abs_range:
  - 0
  - 10000
initial_conditions: []
interventions: []
path: models/digital_comms/run.py
outputs:
- dtype: int
  dims: []
  name: interventions
  unit: assets
- dtype: int
  dims:
  - broadband_distributions
  name: distribution_upgrades
  unit: GBP
- dtype: int
  dims:
  - broadband_distributions
  name: distribution_upgrade_costs_fttp
  unit: GBP
inputs: []
description: The Cambridge Communications Assessment Model provides analytics for
  decision-makers on (i) capacity-demand and (ii) risk, vulnerability and resilience.
  The fixed, wireless and satellite sectors are currently under development.
name: digital_comms
classname: DigitalCommsWrapper
