parameters:
- description: The cost of installing a fiber link
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_links_fibre_meter
  dtype: int
  abs_range:
  - 0
  - 1000
  unit: GBP
- description: The cost of installing a copper link
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_links_copper_meter
  dtype: int
  abs_range:
  - 0
  - 1000
  unit: GBP
- description: The costs to enable an exchange to service FTTDP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_exchange_fttdp
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable an exchange to service FTTP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_exchange_fttp
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable an exchange to service GFast
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_exchange_gfast
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable an exchange to service FTTC
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_exchange_fttc
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable an exchange to service ADSL
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_exchange_adsl
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a cabinet to service FTTP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_cabinet_fttp_32_ports
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a cabinet to service GFast
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_cabinet_gfast
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a cabinet to service FTTC
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_cabinet_fttc
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a cabinet to service ADSL
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_cabinet_adsl
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a distribution to service FTTP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_distribution_fttp_32_ports
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a distribution to service GFast
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_distribution_gfast_4_ports
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a distribution to service FTTC
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_distribution_fttc
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a distribution to service ADSL
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_distribution_adsl
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a premise to receive FTTP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_fttp_modem
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a premise to receive FTTP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_fttp_optical_network_terminator
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a premise to receive GFast
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_gfast_modem
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a premise to receive FTTC
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_fttc_modem
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The costs to enable a premise to receive ADSL
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_adsl_modem
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The benefits to enable a premise to receive FTTP
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: benefits_assets_premise_fttp
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The benefits to enable a premise to receive GFast
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: benefits_assets_premise_gfast
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The benefits to enable a premise to receive FTTC
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: benefits_assets_premise_fttc
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: The benefits to enable a premise to receive ADSL
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: benefits_assets_premise_adsl
  dtype: int
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: ' The yearly budget to spend on infrastructure'
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: annual_budget
  dtype: int
  sug_range:
  - 0
  - 1000000000
  abs_range:
  - 0
  - 10000000000
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: service_obligation_capacity
  dtype: int
  sug_range:
  - 0
  - 1000
  abs_range:
  - 0
  - 10000
  unit: mbps
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: planning_administration_cost
  dtype: int
  sug_range:
  - 0
  - 100000
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_fttdp_modem
  dtype: int
  sug_range:
  - 0
  - 100000
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_premise_fttp_optical_connection_point
  dtype: int
  sug_range:
  - 0
  - 100
  abs_range:
  - 0
  - 100
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_distribution_fttdp_8_ports
  dtype: int
  sug_range:
  - 0
  - 100000
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_cabinet_fttp
  dtype: int
  sug_range:
  - 0
  - 100000
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: costs_assets_cabinet_fttdp
  dtype: int
  sug_range:
  - 0
  - 100000
  abs_range:
  - 0
  - 100000
  unit: GBP
- description: ' '
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: technology_strategy
  dtype: int
  sug_range:
  - 0
  - 0
  abs_range:
  - 0
  - 0
  unit: mode
- description: ' The yearly budget for a telco to match fund on infrastructure'
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: telco_match_funding
  dtype: int
  sug_range:
  - 0
  - 1000000000
  abs_range:
  - 0
  - 10000000000
  unit: GBP
- description: The yearly government subsidy to spend on infrastructure
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: subsidy
  dtype: int
  sug_range:
  - 0
  - 1000000000
  abs_range:
  - 0
  - 10000000000
  unit: GBP
- description: Months per year
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: months_per_year
  dtype: int
  sug_range:
  - 0
  - 12
  abs_range:
  - 0
  - 12
  unit: months
- description: Payback period
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: payback_period
  dtype: int
  sug_range:
  - 4
  - 10
  abs_range:
  - 0
  - 30
  unit: years
- description: Profit margin
  dims: []
  default: ../digital_comms/parameters/defaults.csv
  name: profit_margin
  dtype: int
  sug_range:
  - 15
  - 30
  abs_range:
  - 0
  - 100
  unit: percent
outputs:
- name: adoption_cap
  dtype: float
  description: ''
  dims: []
  unit: 0
- name: distribution_upgrades
  dtype: int
  description: ' '
  dims:
  - broadband_distributions
  - annual
  unit: GBP
- name: distribution_upgrade_costs_fttp
  dtype: int
  unit: GBP
  dims:
  - broadband_distributions
- name: premises_by_distribution
  dtype: int
  description: ' '
  dims:
  - broadband_distributions
  - annual
  unit: Number of premises
- name: interventions
  dtype: int
  unit: assets
  dims:
  - national
  - annual
- name: distribution_upgrades
  dtype: int
  unit: GBP
  dims:
  - broadband_distributions
  - annual
- name: distribution_upgrade_costs_fttp
  dtype: int
  unit: GBP
  dims:
  - broadband_distributions
  - annual
- name: distribution_upgrade_costs_fttdp
  dtype: int
  unit: GBP
  dims:
  - broadband_distributions
  - annual
- name: premises_upgrade_costs_fttp
  dtype: int
  unit: GBP
  dims:
  - broadband_distributions
  - annual
- name: premises_upgrade_costs_fttdp
  dtype: int
  unit: GBP
  dims:
  - broadband_distributions
  - annual
- name: premises_by_distribution
  dtype: int
  unit: premises
  dims:
  - broadband_distributions
  - annual
- name: premises_adoption_desirability
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: premises_connection_statistics
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: premises_passed_with_fttp
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: percentage_of_premises_passed_with_fttp
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: premises_connected_with_fttp
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: percentage_of_premises_connected_with_fttp
  dtype: float
  description: Percentage of premises connected with fttp
  dims:
  - lad_uk_2016
  unit: premises
- name: premises_passed_with_fttdp
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: percentage_of_premises_passed_with_fttdp
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: premises_connected_with_fttdp
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- description: Percentage of premises connected with fttdp
  dims:
  - lad_uk_2016
  name: percentage_of_premises_connected_with_fttdp
  dtype: float
  sug_range:
  - 0
  - 1
  abs_range:
  - 0
  - 1
  unit: '%'
- name: percentage_of_premises_with_fttc
  dtype: int
  unit: premises
  dims:
  - national
  - annual
- name: lad_premises_with_fttp
  dtype: int
  description: Count of premises with fttp per LAD
  dims:
  - lad_uk_2016
  unit: premises
- name: lad_premises_with_fttdp
  dtype: int
  description: Count of premises with fttdp per LAD
  dims:
  - lad_uk_2016
  unit: premises
- name: lad_premises_with_fttc
  dtype: int
  description: Count of premises with fttc per LAD
  dims:
  - lad_uk_2016
  unit: premises
- name: lad_premises_with_adsl
  dtype: int
  description: Count of premises with adsl per LAD
  dims:
  - lad_uk_2016
  unit: premises
- name: coverage
  dtype: float
  description: Premises level coverage by LAD
  dims:
  - lad_uk_2016
  unit: '0'
- description: Percentage of premises connected with fttc
  dims:
  - lad_uk_2016
  name: percentage_of_premises_connected_with_fttc
  dtype: float
  sug_range:
  - 0
  - 1
  abs_range:
  - 0
  - 1
  unit: '%'
- description: Percentage of premises connected with adsl
  dims:
  - lad_uk_2016
  name: percentage_of_premises_connected_with_adsl
  dtype: float
  sug_range:
  - 0
  - 1
  abs_range:
  - 0
  - 1
  unit: '%'
- description: Percentage of premises connected with docsis3
  dims:
  - lad_uk_2016
  name: percentage_of_premises_connected_with_docsis3
  dtype: float
  sug_range:
  - 0
  - 1
  abs_range:
  - 0
  - 1
  unit: '%'
- name: total_cost
  dtype: float
  description: Total cost of all interventions
  dims: []
  unit: GBP
- name: rollout_costs
  dtype: float
  description: The cost of upgrading the exchanges with a given technology for the
    current year
  dims:
  - technology
  - exchanges
  unit: GBP
- name: rollout_bcr
  dtype: float
  description: The benefit cost ratio of upgrading the exchanges with a given technology for the
    current year
  dims:
  - technology
  - exchanges
  unit: 1
description: The Cambridge Communications Assessment Model provides analytics for
  decision-makers on (i) capacity-demand and (ii) risk, vulnerability and resilience.
  The fixed, wireless and satellite sectors are currently under development.
classname: DigitalCommsWrapper
name: digital_comms_fixed_network
inputs:
- description: Adoption
  dims:
  - national
  name: adoption
  dtype: int
  sug_range:
  - 0
  - 100
  abs_range:
  - 0
  - 1000
  unit: '?'
interventions: [../digital_comms/interventions/exchanges.csv]
initial_conditions: []
path: models/digital_comms/run.py
