classname: EnergySupplyWrapper
description: CGEN++ simulates the operation of the coupled UK gas and electricity.
initial_conditions:
- ../energy_supply/initial_conditions/historical_interventions_minimal.csv
inputs:
- name: elecload
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: gasload
  units: mcm
  dims:
  - gas_nodes_minimal
  - seasonal_week
  dtype: float
- name: residential_heatload
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: residential_gas_non_heating
  units: mcm
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: residential_electricity_non_heating
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: service_heatload
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: service_gas_non_heating
  units: mcm
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: service_electricity_non_heating
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: cost_of_carbon
  units: GBP/Mt
  dims:
  - seasons
  dtype: float
- name: electricity_price
  units: GBP/MWh
  dims:
  - seasons
  dtype: float
- name: gas_price
  units: GBP/MWh
  dims:
  - seasons
  dtype: float
- name: nuclearFuel_price
  units: GBP/MWh
  dims:
  - seasons
  dtype: float
- name: oil_price
  units: GBP/MWh
  dims:
  - seasons
  dtype: float
- name: coal_price
  units: GBP/MWh
  dims:
  - seasons
  dtype: float
interventions:
- ../energy_supply/interventions/minimal/es_elec_network_minimal.csv
- ../energy_supply/interventions/minimal/es_gaspipes_minimal.csv
- ../energy_supply/interventions/minimal/es_gasstorage_minimal.csv
- ../energy_supply/interventions/minimal/es_gasterminals_minimal.csv
- ../energy_supply/interventions/minimal/es_generators_minimal.csv
# - high_renewables_interventions.yml
# - high_distributed_interventions.yml
name: energy_supply_toy
outputs:
- name: gasfired_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: coal_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: hydro_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: pumpedHydro_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: nuclear_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: interconnector_elec_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: renewable_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: wind_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: pv_gen_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: wind_curtail_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: pv_curtail_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: gasfired_gen_eh
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: wind_gen_eh
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: pv_gen_eh
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: lng_supply
  units: mcm
  dims:
  - seasonal_week
  dtype: float
- name: domestic_gas
  units: mcm
  dims:
  - seasonal_week
  dtype: float
- name: interconnector_gas
  units: mcm
  dims:
  - seasonal_week
  dtype: float
- name: storage_gas
  units: mcm
  dims:
  - seasonal_week
  dtype: float
- name: load_shed_gas
  units: mcm
  dims:
  - seasonal_week
  dtype: float
- name: load_shed_elec
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: load_shed_gas_eh
  units: mcm
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: load_shed_elec_eh
  units: MW
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: elec_cost
  units: GBP/kWh
  dims:
  - seasonal_week
  dtype: float
- name: heat_gasboiler
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: heat_heatpump
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: elec_reserve_tran
  units: MW
  dims:
  - seasonal_week
  dtype: float
- name: problem_objective
  units: GBP
  dims: []
  dtype: float
- name: problem_status
  units: None
  dims: []
  dtype: float
- name: total_opt_cost
  units: GBP
  dims: []
  dtype: float
- name: emissions_eh
  units: t
  dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
- name: emissions_bb
  units: t
  dims:
  - bus_bars
  - seasonal_week
  dtype: float
parameters:
- description: cost of electricity load shedding
  name: LoadShed_elec
  units: GBP/MWh
  default: 100
- description: cost of gas load shedding
  name: LoadShed_gas
  units: GBP/MWh
  default: 300
path: models/energy_supply/energy_supply.py
