classname: EnergySupplyWrapper
description: energy_supply model description
initial_conditions: []
inputs:
- name: elecload
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: gasload
  spatial_resolution: gas_nodes
  temporal_resolution: seasonal_week
  units: mcm
- name: residential_gas_boiler_gas
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: residential_electricity_boiler_electricity
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: residential_gas_stirling_micro_gas
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: residential_electricity_heat_pumps_electricity
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: residential_electricity_district_heating_electricity
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: residential_gas_district_heating_CHP_gas
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: residential_gas_non_heating
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: mcm
- name: residential_electricity_non_heating
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_gas_boiler_gas
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_electricity_boiler_electricity
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_gas_stirling_micro_gas
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_electricity_heat_pumps_electricity
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_electricity_district_heating_electricity
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_gas_district_heating_gas
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: service_gas_non_heating
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: mcm
- name: service_electricity_non_heating
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: MW
- name: cost_of_carbon
  spatial_resolution: national
  temporal_resolution: seasons
  units: GBP/Mt
- name: electricity_price
  spatial_resolution: national
  temporal_resolution: seasons
  units: GBP/MWh
- name: gas_price
  spatial_resolution: national
  temporal_resolution: seasons
  units: GBP/MWh
- name: nuclearFuel_price
  spatial_resolution: national
  temporal_resolution: seasons
  units: GBP/MWh
- name: oil_price
  spatial_resolution: national
  temporal_resolution: seasons
  units: GBP/MWh
- name: coal_price
  spatial_resolution: national
  temporal_resolution: seasons
  units: GBP/MWh
interventions:
- energy_supply_interventions.yml
name: energy_supply
outputs:
- name: gasfired_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: coal_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: hydro_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: pumpedHydro_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: nuclear_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: interconnector_elec_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: renewable_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: wind_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: pv_gen_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: wind_curtail_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: pv_curtail_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: gasfired_gen_eh
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: wind_gen_eh
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: pv_gen_eh
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: lng_supply
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: mcm
- name: domestic_gas
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: mcm
- name: interconnector_gas
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: mcm
- name: storage_gas
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: mcm
- name: load_shed_gas
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: mcm
- name: load_shed_elec
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: load_shed_gas_eh
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: mcm
- name: load_shed_elec_eh
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: elec_cost
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: GBP/kWh
- name: heat_gasboiler
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: heat_heatpump
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: elec_reserve_tran
  spatial_resolution: national
  temporal_resolution: seasonal_week
  units: MW
- name: problem_objective
  spatial_resolution: national
  temporal_resolution: annual
  units: GBP
- name: problem_status
  spatial_resolution: national
  temporal_resolution: annual
  units: None
- name: total_opt_cost
  spatial_resolution: national
  temporal_resolution: annual
  units: GBP
- name: emissions_eh
  spatial_resolution: energy_hub
  temporal_resolution: seasonal_week
  units: t
- name: emissions_bb
  spatial_resolution: bus_bars
  temporal_resolution: seasonal_week
  units: t
parameters:
- absolute_range:
  - 0
  - inf
  default_value: 100
  description: cost of electricity load shedding
  name: LoadShed_elec
  suggested_range:
  - 0
  - 500
  units: GBP/MWh
- absolute_range:
  - 0
  - inf
  default_value: 300
  description: cost of gas load shedding
  name: LoadShed_gas
  suggested_range:
  - 0
  - 500
  units: GBP/MWh
path: models/energy_supply/energy_supply.py
