classname: EnergySupplyWrapper
description: Toy version of the CGEN++ energy supply model which uses minimal data
initial_conditions:
- ../energy_supply/initial_conditions/historical_interventions_minimal.csv
inputs:
- name: elecload
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: gasload
  dims:
  - gas_nodes_minimal
  - seasonal_week
  unit: mcm
  dtype: float
- name: residential_heatload
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: residential_gas_non_heating
  dims:
  - energy_hub_min
  - seasonal_week
  unit: mcm
  dtype: float
- name: residential_electricity_non_heating
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: service_heatload
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: service_gas_non_heating
  dims:
  - energy_hub_min
  - seasonal_week
  unit: mcm
  dtype: float
- name: service_electricity_non_heating
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: cost_of_carbon
  dims:
  - seasons
  unit: GBP/Mt
  dtype: float
- name: electricity_price
  dims:
  - seasons
  unit: GBP/MWh
  dtype: float
- name: gas_price
  dims:
  - seasons
  unit: GBP/MWh
  dtype: float
- name: nuclearFuel_price
  dims:
  - seasons
  unit: GBP/MWh
  dtype: float
- name: oil_price
  dims:
  - seasons
  unit: GBP/MWh
  dtype: float
- name: coal_price
  dims:
  - seasons
  unit: GBP/MWh
  dtype: float
interventions:
- ../energy_supply/interventions/minimal/es_elec_network_minimal.csv
- ../energy_supply/interventions/minimal/es_gaspipes_minimal.csv
- ../energy_supply/interventions/minimal/es_gasstorage_minimal.csv
- ../energy_supply/interventions/minimal/es_gasterminals_minimal.csv
- ../energy_supply/interventions/minimal/es_generators_minimal.csv
- ../energy_supply/interventions/strategies/high_renewables_interventions.yml
# - high_distributed_interventions.yml
name: energy_supply_toy
outputs:
- name: gasfired_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: coal_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: hydro_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: pumpedHydro_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: nuclear_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: interconnector_elec_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: renewable_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: wind_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: pv_gen_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: wind_curtail_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: pv_curtail_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: gasfired_gen_eh
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: wind_gen_eh
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: pv_gen_eh
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: lng_supply
  dims:
  - national
  - seasonal_week
  unit: mcm
  dtype: float
- name: domestic_gas
  dims:
  - national
  - seasonal_week
  unit: mcm
  dtype: float
- name: interconnector_gas
  dims:
  - national
  - seasonal_week
  unit: mcm
  dtype: float
- name: storage_gas
  dims:
  - national
  - seasonal_week
  unit: mcm
  dtype: float
- name: load_shed_gas
  dims:
  - national
  - seasonal_week
  unit: mcm
  dtype: float
- name: load_shed_elec
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: load_shed_gas_eh
  dims:
  - energy_hub_min
  - seasonal_week
  unit: mcm
  dtype: float
- name: load_shed_elec_eh
  dims:
  - energy_hub_min
  - seasonal_week
  unit: MW
  dtype: float
- name: elec_cost
  dims:
  - national
  - seasonal_week
  unit: GBP/kWh
  dtype: float
- name: heat_gasboiler
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: heat_heatpump
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: elec_reserve_tran
  dims:
  - national
  - seasonal_week
  unit: MW
  dtype: float
- name: problem_objective
  dims: []
  unit: GBP
  dtype: float
- name: problem_status
  dims: []
  unit: None
  dtype: float
- name: total_opt_cost
  dims: []
  unit: GBP
  dtype: float
- name: emissions_eh
  dims:
  - energy_hub_min
  - seasonal_week
  unit: t
  dtype: float
- name: emissions_bb
  dims:
  - bus_bars
  - seasonal_week
  unit: t
  dtype: float
parameters:
- description: cost of electricity load shedding
  name: LoadShed_elec
  units: GBP/MWh
  dtype: float
  default: 100
- description: cost of gas load shedding
  name: LoadShed_gas
  units: GBP/MWh
  dtype: float
  default: 300
path: models/energy_supply/energy_supply.py
