name: energy_demand_unconstrained
description: ''
path: models/energy_demand/run.py
classname: EDWrapper
# ---------------------------------------------------
inputs:
- name: population
  dims:
  - lad_uk_2016
  unit: people
  dtype: float
- name: gva
  dims:
  - lad_uk_2016
  unit: GBP
  dtype: float
# ---------------------------------------------------
outputs:
- name: residential_solid_fuel
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: residential_gas
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: residential_electricity
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: residential_oil
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: residential_biomass
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: residential_hydrogen
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: residential_heat
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_solid_fuel
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_gas
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_electricity
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_oil
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_biomass
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_hydrogen
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: service_heat
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_solid_fuel
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_gas
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_electricity
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_oil
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_biomass
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_hydrogen
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
- name: industry_heat
  dims:
  - lad_uk_2016
  - hourly
  unit: GW
  dtype: float
# ---------------------------------------------------
interventions: []
initial_conditions: []
parameters:
# Paramters generated from script---------------------------------------------------
