classname: EnergySupplyWrapper
description: Toy version of the CGEN++ energy supply model which uses minimal data
initial_conditions:
- ../energy_supply/initial_conditions/historical_interventions_minimal.csv
inputs:
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: elecload
  unit: MW
- dims:
  - gas_nodes_minimal
  - seasonal_week
  dtype: float
  name: gasload
  unit: mcm
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: residential_heatload
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: residential_gas_non_heating
  unit: mcm
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: residential_electricity_non_heating
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: service_heatload
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: service_gas_non_heating
  unit: mcm
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: service_electricity_non_heating
  unit: MW
- dims:
  - seasons
  dtype: float
  name: cost_of_carbon
  unit: GBP/Mt
- dims:
  - seasons
  dtype: float
  name: electricity_price
  unit: GBP/MWh
- dims:
  - seasons
  dtype: float
  name: gas_price
  unit: GBP/MWh
- dims:
  - seasons
  dtype: float
  name: nuclearFuel_price
  unit: GBP/MWh
- dims:
  - seasons
  dtype: float
  name: oil_price
  unit: GBP/MWh
- dims:
  - seasons
  dtype: float
  name: coal_price
  unit: GBP/MWh
interventions:
- ../energy_supply/interventions/minimal/es_elec_network_minimal.csv
- ../energy_supply/interventions/minimal/es_gaspipes_minimal.csv
- ../energy_supply/interventions/minimal/es_gasstorage_minimal.csv
- ../energy_supply/interventions/minimal/es_gasterminals_minimal.csv
- ../energy_supply/interventions/minimal/es_generators_minimal.csv
- ../energy_supply/interventions/minimal/es_heattech_minimal.csv
# - ../energy_supply/interventions/strategies/high_renewables_interventions.yml
# - high_distributed_interventions.yml
name: energy_supply_toy
outputs:
- dims:
  - national
  - seasonal_week
  dtype: float
  name: gasfired_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: coal_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: hydro_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: pumpedHydro_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: nuclear_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: interconnector_elec_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: renewable_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: wind_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: pv_gen_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: wind_curtail_tran
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: pv_curtail_tran
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: gasfired_gen_eh
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: wind_gen_eh
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: pv_gen_eh
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: lng_supply
  unit: mcm
- dims:
  - national
  - seasonal_week
  dtype: float
  name: domestic_gas
  unit: mcm
- dims:
  - national
  - seasonal_week
  dtype: float
  name: interconnector_gas
  unit: mcm
- dims:
  - national
  - seasonal_week
  dtype: float
  name: storage_gas
  unit: mcm
- dims:
  - national
  - seasonal_week
  dtype: float
  name: load_shed_gas
  unit: mcm
- dims:
  - national
  - seasonal_week
  dtype: float
  name: load_shed_elec
  unit: MW
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: load_shed_gas_eh
  unit: mcm
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: load_shed_elec_eh
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: elec_cost
  unit: GBP/kWh
- dims:
  - national
  - seasonal_week
  dtype: float
  name: heat_gasboiler
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: heat_heatpump
  unit: MW
- dims:
  - national
  - seasonal_week
  dtype: float
  name: elec_reserve_tran
  unit: MW
- dims: []
  dtype: float
  name: problem_objective
  unit: GBP
- dims: []
  dtype: float
  name: problem_status
  unit: None
- dims: []
  dtype: float
  name: total_opt_cost
  unit: GBP
- dims:
  - energy_hub_min
  - seasonal_week
  dtype: float
  name: emissions_eh
  unit: t
- dims:
  - bus_bars
  - seasonal_week
  dtype: float
  name: emissions_bb
  unit: t
parameters:
- name: LoadShed_elec
  description: cost of electricity load shedding
  dims: []
  default: ../energy_supply/parameters/load_shed.csv
  unit: £/MWh
  dtype: float
- name: LoadShed_gas
  description: cost of gas load shedding
  dims: []
  default: ../energy_supply/parameters/load_shed.csv
  unit: £/MWh
  dtype: float
path: models/energy_supply/energy_supply.py
