name: energy_demand_unconstrained
description: ''
path: models/energy_demand/run.py
classname: EDWrapper
initial_conditions: []
inputs:
  - name: floor_area
    unit: meter**2
    dims:
      - lad_uk_2016
      - residential_or_non
    dtype: float
  - name: t_min
    unit: Degree Celcius
    dims:
      - lad_uk_2016
      - yearday
    dtype: float
  - name: t_max
    unit: Degree Celcius
    dims:
      - lad_uk_2016
      - yearday
    dtype: float
  - name: population
    unit: people
    dims:
      - lad_uk_2016
    dtype: float
  - name: gva_per_head
    unit: GBP
    dims:
      - lad_uk_2016
    dtype: float
  - name: gva_per_sector
    unit: GBP
    description: GVA per industrial sector    
    dims:
      - lad_uk_2016
      - sectors
    dtype: float
outputs:
  - name: residential_solid_fuel
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: residential_gas
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: residential_electricity
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: residential_oil
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: residential_biomass
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: residential_hydrogen
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: residential_heat
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_solid_fuel
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_gas
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_electricity
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_oil
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_biomass
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_hydrogen
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: service_heat
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_solid_fuel
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_gas
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_electricity
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_oil
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_biomass
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_hydrogen
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
  - name: industry_heat
    dims:
      - lad_uk_2016
      - hourly
    unit: GW
    dtype: float
parameters:
  - name: virtual_dw_stock
    description: Dwelling stock type or read in floor area directly
    default: ../energy_demand/parameters/virtual_dw_stock
    unit: ''
    dtype: bool
  - name: mode
    description: Mode of model
    default: ../energy_demand/parameters/mode_unconstrained
    unit: ''
    dtype: int
  - name: switches_service
    description: Service switches
    default: ../energy_demand/parameters/switches_service
    unit: ''
    dims:
      - enduses_service_switch
      - tech
      - end_yr
      - sector
    dtype: float
  - name: generic_fuel_switch
    description: Generic fuel switch
    default: ../energy_demand/parameters/generic_fuel_switch
    unit: ''
    dims:
      - generic_switch_number
      - enduses
      - end_yr
      - param_generic_fuel_switch
    dtype: float
  - name: p_cold_rolling_steel
    description: Share in cold rolling in steel manufacturing
    default: ../energy_demand/parameters/p_cold_rolling_steel
    unit: 'decimal'
    dims:
      - end_yr
      - interpolation_params
    dtype: float
  - name: heat_recovered
    description: Recovered heat
    default: ../energy_demand/parameters/heat_recovered
    unit: 'decimal'
    dims:
      - end_yr
      - interpolation_params
      - enduses
    dtype: float
  - name: cooled_floorarea
    description: Share of cooled service floor area
    default: ../energy_demand/parameters/cooled_floorarea
    unit: 'decimal'
    dims:
      - end_yr
      - interpolation_params
      - enduses
    dtype: float
  - name: assump_diff_floorarea_pp
    description: Change in floor area per person
    default: ../energy_demand/parameters/assump_diff_floorarea_pp
    unit: 'decimal'
    dims:
      - end_yr
      - interpolation_params
    dtype: float
  - name: air_leakage
    description: Air leakage caused reducing in demand
    default: ../energy_demand/parameters/air_leakage
    unit: 'decimal'
    dims:
      - enduses
      - end_yr
      - interpolation_params
    dtype: float
  - name: f_eff_achieved
    description: Efficiency achievement level
    default: ../energy_demand/parameters/f_eff_achieved
    unit: 'decimal'
    dims:
      - end_yr
      - interpolation_params
    dtype: float
  - name: smart_meter_p
    description: Smart meter penetration
    default: ../energy_demand/parameters/smart_meter_p
    unit: 'decimal'
    dims:
      - end_yr
      - interpolation_params
    dtype: float
  - name: rs_t_base_heating
    description: Industrial base temperature
    default: ../energy_demand/parameters/rs_t_base_heating
    unit: ''
    dims:
      - interpolation_params
      - end_yr
    dtype: float
  - name: ss_t_base_heating
    description: Industrial base temperature
    default: ../energy_demand/parameters/ss_t_base_heating
    unit: ''
    dims:
      - interpolation_params
      - end_yr
    dtype: float
  - name: is_t_base_heating
    description: Industrial base temperature
    default: ../energy_demand/parameters/is_t_base_heating
    unit: ''
    dims:
      - interpolation_params
      - end_yr
    dtype: float
  - name: dm_improvement
    description: Demand side management improvemnt
    default: ../energy_demand/parameters/dm_improvement
    unit: ''
    dims:
      - enduses
      - interpolation_params
      - end_yr
    dtype: float
  - name: spatial_explicit_diffusion
    description: Spatial explicit diffusion or not
    default: ../energy_demand/parameters/spatial_explicit_diffusion
    unit: 'integer'
    dtype: float
  - name: speed_con_max
    description: Spatial diffusion speed
    default: ../energy_demand/parameters/speed_con_max
    unit: ''
    dtype: float
  - name: gshp_fraction
    description: Heat pump fractions
    default: ../energy_demand/parameters/gshp_fraction
    unit: 'decimal'
    dims:
      - interpolation_params
      - end_yr
    dtype: float
  - name: gshp_fraction
    description: Heat pump fractions
    default: ../energy_demand/parameters/gshp_fraction
    unit: 'decimal'
    dtype: float
  - name: generic_enduse_change
    description: Overall change in energy demand per enduse
    default: ../energy_demand/parameters/generic_enduse_change
    unit: '%'
    dims:
      - enduses
      - interpolation_params
      - end_yr
    dtype: float
interventions: []
