outputs:
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: ccgt_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: coal_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: oil_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: hydro_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: pumpedHydro_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: thermal_tot
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: nuclear_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: interconnector_elec
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: wind_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: pv_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: renewable_gen
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: wind_curtail
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: pv_curtail
- units: mcm
  temporal_resolution: seasonal_week
  spatial_resolution: national
  name: lng_supply
- units: mcm
  temporal_resolution: seasonal_week
  spatial_resolution: national
  name: domestic_gas
- units: mcm
  temporal_resolution: seasonal_week
  spatial_resolution: national
  name: interconnector_gas
- units: mcm
  temporal_resolution: seasonal_week
  spatial_resolution: national
  name: storage_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: Load_shed_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: Load_shed_elec
- units: MtCO2
  temporal_resolution: annual
  spatial_resolution: national
  name: emissions_elec
- units: £/cm
  temporal_resolution: seasonal_week
  spatial_resolution: national
  name: gas_cost
- units: £/kWh
  temporal_resolution: seasonal_week
  spatial_resolution: national
  name: elec_cost
path: models/energy_supply.py
parameters:
- absolute_range: [0, 9999]
  default_value: 100
  suggested_range: [0, 500]
  units: £/MWh
  description: cost of electricity load shedding
  name: LoadShed_elec
- absolute_range: [0, 9999]
  default_value: 300
  suggested_range: [0, 500]
  units: £/MWh
  description: cost of gas load shedding
  name: LoadShed_gas
initial_conditions:
- energy_supply_elecnetwork.yml
- energy_supply_gasnetwork.yml
- energy_supply_gasstore.yml
- energy_supply_gasterminal.yml
- energy_supply_generation.yml
inputs:
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_gas_boiler_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_electricity_boiler_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_gas_stirling_micro_CHP
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_electricity_heat_pumps_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_electricity_district_heating_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_gas_district_heating_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_gas_non_heating
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: residential_electricity_non_heating
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_gas_boiler_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_electricity_boiler_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_gas_stirling_micro_CHP
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_electricity_heat_pumps_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_electricity_district_heating_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_gas_district_heating_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_gas_non_heating
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: service_electricity_non_heating
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_gas_boiler_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_electricity_boiler_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_biomass_boiler_biomass
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_gas_stirling_micro_CHP
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_electricity_heat_pumps_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_electricity_district_heating_electricity
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_gas_district_heating_gas
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_biomass_district_heating_biomass
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_gas_non_heating
- units: MW
  temporal_resolution: seasonal_week
  spatial_resolution: exit_zones
  name: industry_electricity_non_heating
- units: £/kgCO2
  temporal_resolution: annual
  spatial_resolution: national
  name: cost_of_carbon
- units: £/MWh
  temporal_resolution: annual
  spatial_resolution: national
  name: electricity_price
- units: £/MWh
  temporal_resolution: annual
  spatial_resolution: national
  name: gas_price
- units: £/MWh
  temporal_resolution: annual
  spatial_resolution: national
  name: nuclearFuel_price
- units: £/MWh
  temporal_resolution: annual
  spatial_resolution: national
  name: oil_price
- units: £/MWh
  temporal_resolution: annual
  spatial_resolution: national
  name: coal_price
description: CGEN++ simulates the operation of the coupled UK gas and electricity
interventions:
- energy_supply.yml
classname: EnergySupplyWrapper
name: energy_supply
