classname: EnergySupplyWrapper
description: energy_supply model description
initial_conditions:
- ../energy_supply/initial_conditions/historical_interventions.csv
inputs:
- name: elecload
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: gasload
  units: mcm
  dims:
  - gas_nodes
  dtype: TODO
- name: residential_heatload
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: residential_gas_non_heating
  units: mcm
  dims:
  - energy_hub
  dtype: TODO
- name: residential_electricity_non_heating
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_heatload
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: service_gas_non_heating
  units: mcm
  dims:
  - energy_hub
  dtype: TODO
- name: service_electricity_non_heating
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: cost_of_carbon
  units: GBP/Mt
  dims:
  - national
  dtype: TODO
- name: electricity_price
  units: GBP/MWh
  dims:
  - national
  dtype: TODO
- name: gas_price
  units: GBP/MWh
  dims:
  - national
  dtype: TODO
- name: nuclearFuel_price
  units: GBP/MWh
  dims:
  - national
  dtype: TODO
- name: oil_price
  units: GBP/MWh
  dims:
  - national
  dtype: TODO
- name: coal_price
  units: GBP/MWh
  dims:
  - national
  dtype: TODO
interventions:
- ../energy_supply/interventions/full/es_elec_network.csv
- ../energy_supply/interventions/full/es_gaspipes.csv
- ../energy_supply/interventions/full/es_gasstorage.csv
- ../energy_supply/interventions/full/es_gasterminals.csv
- ../energy_supply/interventions/full/es_generators.csv
- ../energy_supply/interventions/full/es_heattech.csv
name: energy_supply
outputs:
- name: gasfired_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: coal_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: hydro_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: pumpedHydro_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: nuclear_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: interconnector_elec_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: renewable_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: wind_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: pv_gen_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: wind_curtail_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: pv_curtail_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: gasfired_gen_eh
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: wind_gen_eh
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: pv_gen_eh
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: lng_supply
  units: mcm
  dims:
  - national
  dtype: TODO
- name: domestic_gas
  units: mcm
  dims:
  - national
  dtype: TODO
- name: interconnector_gas
  units: mcm
  dims:
  - national
  dtype: TODO
- name: storage_gas
  units: mcm
  dims:
  - national
  dtype: TODO
- name: load_shed_gas
  units: mcm
  dims:
  - national
  dtype: TODO
- name: load_shed_elec
  units: MW
  dims:
  - national
  dtype: TODO
- name: load_shed_gas_eh
  units: mcm
  dims:
  - energy_hub
  dtype: TODO
- name: load_shed_elec_eh
  units: MW
  dims:
  - energy_hub
  dtype: TODO
- name: elec_cost
  units: GBP/kWh
  dims:
  - national
  dtype: TODO
- name: heat_gasboiler
  units: MW
  dims:
  - national
  dtype: TODO
- name: heat_heatpump
  units: MW
  dims:
  - national
  dtype: TODO
- name: elec_reserve_tran
  units: MW
  dims:
  - national
  dtype: TODO
- name: problem_objective
  units: GBP
  dims:
  - national
  dtype: TODO
- name: problem_status
  units: None
  dims:
  - national
  dtype: TODO
- name: total_opt_cost
  units: GBP
  dims:
  - national
  dtype: TODO
- name: emissions_eh
  units: t
  dims:
  - energy_hub
  dtype: TODO
- name: emissions_bb
  units: t
  dims:
  - bus_bars
  dtype: TODO
parameters:
- description: cost of electricity load shedding
  name: LoadShed_elec
  units: GBP/MWh
  default: 100
- description: cost of gas load shedding
  name: LoadShed_gas
  units: GBP/MWh
  default: 300
path: models/energy_supply/energy_supply.py
