name: et_module
description: ''
path: ../models/et_module/run.py
classname: ETWrapper
# ---------------------------------------------------
inputs:
- name: electricity
  units: GWh
  dims:
  - lad_uk_2016
  dtype: TODO
# ---------------------------------------------------
outputs:
- name: electricity
  units: GWh
  dims:
  - lad_uk_2016
  dtype: TODO
interventions: []
initial_conditions: []
parameters: []
