name: et_module
description: ''
path: ../models/et_module/run.py
classname: ETWrapper
# ---------------------------------------------------
inputs:
- name: electricity
  dims:
  - lad_uk_2016
  unit: GWh
  dtype: float
# ---------------------------------------------------
outputs:
- name: electricity
  dims:
  - lad_uk_2016
  - hourly
  unit: GWh
  dtype: float
interventions: []
initial_conditions: []
parameters: []
