name: et_module
description: Derives energy demand and V2G capacity from transport EV results
path: models/et_module/run.py
classname: ETWrapper
inputs:
  - name: ev_electricity
    description: Electricity demand of electric vehicles
    dims:
      - annual_day_hours
      - lad_uk_2016
    unit: kWh
    dtype: float
  - name: ev_trips
    description: Trip count of electric vehicles
    dims:
      - annual_day_hours
      - lad_uk_2016
    dtype: int
    unit: trips
outputs:
  - name: v2g_g2v_capacity
    dims:
     - lad_uk_2016
    dtype: float
    unit: kW
parameters:
  - default: ../et_module/parameters/ev_scheduling_default.csv
    description: Year until future load profile assignment is fully realised
    dtype: float
    name: yr_until_changed_lp
    units: 1
  - default: ../et_module/parameters/ev_scheduling_default.csv
    description: EV charging regime
    dtype: float
    name: load_profile_charging_regime
    units: 1
interventions: []
initial_conditions: []
