name: rail_southampton
description: Transport rail model for Southampton and neighbouring LADs
path: ./models/transport/run_rail_only.py
classname: SouthamptonRailTransportWrapper
inputs:
  - name: population
    dims:
      - lad_southampton
    unit: people
    dtype: float
  - name: gva
    dims:
      - lad_southampton
    unit: GBP
    dtype: float
outputs:
  - name: energy_consumption
    dims:
      - annual_day
      - transport_fuel_type
    unit: l
    dtype: float
parameters:
  - name: elasticities
    dims:
      - variables
      - area
    description: Population elasticity for passenger demand
    dtype: float
    default: default_rail_elasticities.csv
  - name: BaseYearYearUsage
    dims:
      - NLC_southampton
    description:
    dtype: float
    default: default_base_year_rail_demand_southampton.csv
  - name: BaseYearDayUsage
    dims:
      - NLC_southampton
    description:
    dtype: float
    default: default_base_year_rail_demand_southampton.csv
  - name: use_car_cost_from_road_model
    description: Whether to use output of road model for car costs
    dtype: bool
    default: default_rail_flags.csv
  - name: predict_intermediate_rail_years
    description: Wether to predict all years between base year and predicted year
    dtype: bool
    default: default_rail_flags.csv
interventions:
  - transport_rail.csv
initial_conditions: []
