name: rail_southampton
description: Transport rail model for Southampton and neighbouring LADs
path: ./models/transport/run_rail_only.py
classname: SouthamptonRailTransportWrapper
inputs:
  - name: population
    dims:
      - lad_southampton
    unit: people
    dtype: float
  - name: gva
    dims:
      - lad_southampton
    unit: GBP
    dtype: float
  - name: day_usage
    dims:
      - stations_NLC
    unit: ppl
    dtype: float
  - name: year_usage
    dims:
      - stations_NLC
    unit: ppl
    dtype: float
  - name: rail_journey_fares
    dims:
      - stations_NLC
    unit: £
    dtype: float
  - name: rail_journey_times
    dims:
      - stations_NLC_generalised
    unit: h
    dtype: float
  - name: car_zonal_journey_costs
    dims:
      - lad_southampton
    unit: £
    dtype: float
outputs:
  - name: energy_consumption
    dims:
      - annual_day
      - transport_fuel_type
    unit: l
    dtype: float
parameters:
  - name: elasticities
    dims:
      - variables
      - area
    description: Population elasticity for passenger demand
    dtype: float
    default: default_rail_elasticities.csv
  - name: use_car_cost_from_road_model
    description: Whether to use output of road model for car costs
    dtype: bool
    default: default_rail_flags.csv
  - name: predict_intermediate_rail_years
    description: Wether to predict all years between base year and predicted year
    dtype: bool
    default: default_rail_flags.csv
interventions:
  - transport_rail.csv
initial_conditions:
  - base_year_railstations.csv
