classname: RemapEnergyHubToGasNode
description: Remaps data from energy hub regions to gas nodes
initial_conditions: []
inputs:
- units: mcm
  name: gasload
  dims:
  - energy_hub
  - seasonal_week
  dtype: float
interventions: []
name: remap_gas
outputs:
- name: gasload
  units: mcm
  dims:
  - gas_nodes
  - seasonal_week
  dtype: float
parameters: []
path: models/remap_gas.py
