classname: RemapEnergyHubToGasNode
description: 'Aggregates energy demand outputs for energy supply transmission elecload '
initial_conditions: []
inputs:
- temporal_resolution: seasonal_week
  units: mcm
  name: gasload
  spatial_resolution: energy_hub
interventions: []
name: aggregate_elecload
outputs:
- name: gasload
  spatial_resolution: gas_nodes
  temporal_resolution: seasonal_week
  units: mcm
parameters: []
path: models/remap_gas.py
