classname: RemapEnergyHubToGasNode
description: 'Remaps data from energy hub regions to gas nodes'
initial_conditions: []
inputs:
- temporal_resolution: seasonal_week
  units: mcm
  name: gasload
  spatial_resolution: energy_hub
interventions: []
name: remap_gas
outputs:
- name: gasload
  spatial_resolution: gas_nodes
  temporal_resolution: seasonal_week
  units: mcm
parameters: []
path: models/remap_gas.py
