name: remap_gas
description: Remaps data from energy hub regions to gas nodes
path: models/remap_gas.py
classname: RemapEnergyHubToGasNode
initial_conditions: []
inputs:
  - name: gasload
    dims:
      - energy_hub
      - seasonal_week
    unit: mcm
    dtype: float
interventions: []
outputs:
  - name: gasload
    dims:
      - gas_nodes
      - seasonal_week
    unit: mcm
    dtype: float
parameters: []
