classname: RemapEnergyHubToGasNode
description: Remaps data from energy hub regions to gas nodes
initial_conditions: []
inputs:
- units: mcm
  name: gasload
  dims:
  - energy_hub
  dtype: TODO
interventions: []
name: remap_gas
outputs:
- name: gasload
  units: mcm
  dims:
  - gas_nodes
  dtype: TODO
parameters: []
path: models/remap_gas.py
