name: transport
description: transport model description
path: ./models/transport/run.py
classname: TransportWrapper
inputs:
- name: population
  dims:
  - lad_uk_2016
  unit: people
  dtype: float
- name: gva
  dims:
  - lad_uk_2016
  unit: GBP
  dtype: float
outputs:
- name: energy_consumption_petrol
  dims:
  - whole_system
  - annual_day
  unit: l
  dtype: float
- name: energy_consumption_diesel
  dims:
  - whole_system
  - annual_day
  unit: l
  dtype: float
- name: energy_consumption_lpg
  dims:
  - whole_system
  - annual_day
  unit: l
  dtype: float
- name: energy_consumption_electricity
  dims:
  - whole_system
  - annual_day
  unit: kWh
  dtype: float
- name: energy_consumption_hydrogen
  dims:
  - whole_system
  - annual_day
  unit: l
  dtype: float
- name: energy_consumption_hybrid
  dims:
  - whole_system
  - annual_day
  unit: l
  dtype: float
parameters:
- name: POPULATION_ETA
  description: Population elasticity for passenger demand
  units:
  dtype: float
  default: 1
- name: GVA_ETA
  description: GVA elasticity for passenger demand
  units:
  dtype: float
  default: 0.63
- name: TIME_ETA
  description: Time elasticity for passenger demand
  units:
  dtype: float
  default: -0.41
- name: COST_ETA
  description: Cost elasticity for passenger demand
  units:
  dtype: float
  default: -0.215
- name: POPULATION_FREIGHT_ETA
  description: Population elasticity for freight demand
  units:
  dtype: float
  default: 1
- name: GVA_FREIGHT_ETA
  description: GVA elasticity for freight demand
  units:
  dtype: float
  default: 0.7
- name: TIME_FREIGHT_ETA
  description: Time elasticity for freight demand
  units:
  dtype: float
  default: -0.41
- name: COST_FREIGHT_ETA
  description: Cost elasticity for freight demand
  units:
  dtype: float
  default: -0.1
interventions:
- transport_interventions.yml
initial_conditions: []
