name: transport
description: Transport model for Southampton and neighbouring LADs
path: ./models/transport/run.py
classname: TransportWrapper
inputs:
  - name: population
    dims:
      - lad_gb_2016
    unit: people
    dtype: float
  - name: gva
    dims:
      - lad_gb_2016
    unit: GBP
    dtype: float
  - name: fuel_price
    unit: £/l
    dtype: float
    dims:
      - transport_fuel_type
  - name: fuel_price_electricity
    unit: £/kWh
    dtype: float
  - name: link_travel_time
    dims:
      - road_edge_id
      - annual_day_hours
    unit: h
    dtype: float
  - name: time_of_day_distribution_passenger
    description:
    dtype: float
    dims:
      - annual_day_hours
  - name: time_of_day_distribution_freight
    description:
    dtype: float
    dims:
      - annual_day_hours
      - freight_vehicle_type
  - name: engine_type_fractions
    description:
    dtype: float
    dims:
      - vehicle_type
      - engine_type
  - name: autonomous_vehicle_fractions
    description:
    dtype: float
    dims:
      - vehicle_type
outputs:
  - name: energy_consumption
    dims:
      - annual_day
      - transport_fuel_type
    unit: l
    dtype: float
  - name: energy_consumption_electricity
    dims:
      - annual_day
    unit: kWh
    dtype: float
  - name: electric_vehicle_electricity_consumption
    dims:
      - lad_gb_2016
      - annual_day_hours
    unit: kWh
    dtype: float
  - name: electric_vehicle_trip_starts
    dims:
      - lad_gb_2016
      - annual_day_hours
    unit: trips
    dtype: int
  - name: link_travel_time
    dims:
      - road_edge_id
      - annual_day_hours
    unit: h
    dtype: float
parameters:
  - name: POPULATION_ETA
    description: Population elasticity for passenger demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: GVA_ETA
    description: GVA elasticity for passenger demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: TIME_ETA
    description: Time elasticity for passenger demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: COST_ETA
    description: Cost elasticity for passenger demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: POPULATION_FREIGHT_ETA
    description: Population elasticity for freight demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: GVA_FREIGHT_ETA
    description: GVA elasticity for freight demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: TIME_FREIGHT_ETA
    description: Time elasticity for freight demand
    dtype: float
    default: default_transport_elasticities.csv
  - name: COST_FREIGHT_ETA
    description: Cost elasticity for freight demand
    dtype: float
    default: default_transport_elasticities.csv
interventions:
  - transport_lane_expansions.csv
  - transport_new_links.csv
  - transport_congestion_zones.csv
initial_conditions: []
