name: transport
description: transport model description
path: ./models/transport/run.py
classname: TransportWrapper
inputs:
  - name: population
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual_day
    units: people
outputs:
  - name: energy_consumption_petrol
    spatial_resolution: whole_system
    temporal_resolution: annual_day
    units: l
  - name: energy_consumption_diesel
    spatial_resolution: whole_system
    temporal_resolution: annual_day
    units: l
  - name: energy_consumption_lpg
    spatial_resolution: whole_system
    temporal_resolution: annual_day
    units: l
  - name: energy_consumption_electricity
    spatial_resolution: whole_system
    temporal_resolution: annual_day
    units: kwh
  - name: energy_consumption_hydrogen
    spatial_resolution: whole_system
    temporal_resolution: annual_day
    units: l
  - name: energy_consumption_hybrid
    spatial_resolution: whole_system
    temporal_resolution: annual_day
    units: l
parameters:
  - name: POPULATION_ETA
    description: Population elasticity for passenger demand
    default_value: 1
    units:
    absolute_range:
    suggested_range:
  - name: GVA_ETA
    description: GVA elasticity for passenger demand
    default_value: 0.63
    units:
    absolute_range:
    suggested_range:
  - name: TIME_ETA
    description: Time elasticity for passenger demand
    default_value: -0.41
    units:
    absolute_range:
    suggested_range:
  - name: COST_ETA
    description: Cost elasticity for passenger demand
    default_value: -0.215
    units:
    absolute_range:
    suggested_range:
  - name: POPULATION_FREIGHT_ETA
    description: Population elasticity for freight demand
    default_value: 1
    units:
    absolute_range:
    suggested_range:
  - name: GVA_FREIGHT_ETA
    description: GVA elasticity for freight demand
    default_value: 0.7
    units:
    absolute_range:
    suggested_range:
  - name: TIME_FREIGHT_ETA
    description: Time elasticity for freight demand
    default_value: -0.41
    units:
    absolute_range:
    suggested_range:
  - name: COST_FREIGHT_ETA
    description: Cost elasticity for freight demand
    default_value: -0.1
    units:
    absolute_range:
    suggested_range:
interventions:
  - transport_interventions.yml
initial_conditions: []
