name: transport
description: transport model description
path: ./models/transport/run.py
classname: TransportWrapper
inputs:
- name: population
  units: people
  dims:
  - lad_uk_2016
  dtype: TODO
- name: gva
  units: GBP
  dims:
  - lad_uk_2016
  dtype: TODO
outputs:
- name: energy_consumption_petrol
  units: l
  dims:
  - whole_system
  dtype: TODO
- name: energy_consumption_diesel
  units: l
  dims:
  - whole_system
  dtype: TODO
- name: energy_consumption_lpg
  units: l
  dims:
  - whole_system
  dtype: TODO
- name: energy_consumption_electricity
  units: kWh
  dims:
  - whole_system
  dtype: TODO
- name: energy_consumption_hydrogen
  units: l
  dims:
  - whole_system
  dtype: TODO
- name: energy_consumption_hybrid
  units: l
  dims:
  - whole_system
  dtype: TODO
parameters:
- name: POPULATION_ETA
  description: Population elasticity for passenger demand
  units:
  default: 1
- name: GVA_ETA
  description: GVA elasticity for passenger demand
  units:
  default: 0.63
- name: TIME_ETA
  description: Time elasticity for passenger demand
  units:
  default: -0.41
- name: COST_ETA
  description: Cost elasticity for passenger demand
  units:
  default: -0.215
- name: POPULATION_FREIGHT_ETA
  description: Population elasticity for freight demand
  units:
  default: 1
- name: GVA_FREIGHT_ETA
  description: GVA elasticity for freight demand
  units:
  default: 0.7
- name: TIME_FREIGHT_ETA
  description: Time elasticity for freight demand
  units:
  default: -0.41
- name: COST_FREIGHT_ETA
  description: Cost elasticity for freight demand
  units:
  default: -0.1
interventions:
- transport_interventions.yml
initial_conditions: []
