classname: WaterWrapper
description: Water supply model
initial_conditions: []
inputs:
- name: water_demand
  dims:
  - water_resource_zones
  dtype: float
  unit: Ml/day
- name: reservoir_levels
  dims:
  - water_supply_reservoirs
  dtype: float
  unit: Ml
interventions: []
name: water_supply
outputs:
- name: reservoir_levels  # This is the end-of-year volumes that go into next timestep
  dims:
    - water_supply_reservoirs
  dtype: float
  unit: Ml
- name: water_supply_reservoir_daily_volumes  # Daily volumes output from wathnet
  dims:
  - water_supply_days_into_year
  - water_supply_reservoirs
  dtype: float
  unit: ML
- name: water_supply_arc_flows
  dims:
  - water_supply_days_into_year
  - water_supply_arcs
  dtype: float
  unit: ML/day
parameters: []
path: models/water_supply/run.py
