classname: WaterWrapper
description: Water supply model
initial_conditions: []
inputs:
- name: water_demand
  dims:
  - water_resource_zones
  dtype: float
  unit: Ml/day
- name: reservoir_levels
  dims:
  - water_supply/reservoir_names
  dtype: float
  unit: Ml
- name: flows_data
  dims:
  - water_supply/days_into_year
  - water_supply/flow_file_column_names
  dtype: float
  unit: Ml/day
interventions: []
name: water_supply
outputs:
- name: reservoir_levels  # This is the end-of-year volumes that go into next timestep
  dims:
    - water_supply/reservoir_names
  dtype: float
  unit: Ml
- name: water_supply_reservoir_daily_volumes  # Daily volumes output from wathnet
  dims:
  - water_supply/days_into_year
  - water_supply/reservoir_names
  dtype: float
  unit: Ml
- name: water_supply_arc_flows
  dims:
  - water_supply/days_into_year
  - water_supply/arc_names
  dtype: float
  unit: Ml/day
- name: water_supply_global_variables
  dims:
  - water_supply/days_into_year
  - water_supply/global_variable_names
  dtype: float
  unit: Unknown/possibly variable
- name: water_supply_requested_demand
  dims:
  - water_supply/days_into_year
  - water_supply/demand_nodes
  dtype: float
  unit: Ml
- name: water_supply_shortfall
  dims:
  - water_supply/days_into_year
  - water_supply/demand_nodes
  dtype: float
  unit: Ml
parameters:
- name: nonpublic_water_demand
  description: Nonpublic water demand required for preparing Wathnet nodal file
  dims:
  - water_supply/cams_names
  - water_supply/nonpublic_use_codes
  dtype: float
  unit: Ml/day
  default: water_supply/nonpublic_water_demands.csv
- name: demand_profiles
  description: Demand profiles required for preparing Wathnet nodal file
  dims:
  - water_supply/days_into_year
  - water_supply/demand_profile_zones
  dtype: float
  unit: None
  default: water_supply/demand_profiles.csv
path: models/water_supply/run.py
