kind: Model
apiVersion: v1alpha4
metadata:
  displayName: NISMOD - Energy Transport (model v0.3.1 build 1)
  name: nismod-et-module
  summary: National Infrastructure Systems Model
  type: systems of systems
  description: >
    Converts electricity demand and trip counts output from transport model to
    estimate available vehicle battery capacity.

    The hourly electricity demand is used to simulate the Vehicle-to-Grid and
    Grid-to-Vehicle (V2G and G2V) capacity based on simplified assumptions about
    average electric vehicle battery capacity and assumptions on average EV
    storage capacity. The simulated capacity can then be used by the energy
    supply model in its optimisation.
spec:
  inputs:
    env:
      - name: sector_model
        title: ET Module Sector Model
        desc: Pick one of the NISMOD2 et_module Sector Models to run
        type: string
        default: et_module
        options:
          - name: et_module
            title: Energy Transport Module
      - name: model_to_run
        title: Model Run
        desc: The name of the model run that is being executed
        type: string
        default: et_module_test
      - name: part_of_sos_model
        title: Part of SOS Model
        desc: "Is this model being run as part of a NISMOD2 Systems of Systems Model?"
        type: boolean
        default: false
      - name: use_generated_scenario
        title: Use generated scenario
        desc: "Is this run using a new generated scenario file?"
        type: boolean
        default: false
      - name: timestep
        title: Timestep
        desc: "Timestep to run the Model at if this is part of an SoS Model"
        type: integer
    dataslots:
      - name: Scenario Data
        description: >
          NISMOD scenario data pack. Should contain socio-economic scenarios
          (population, GVA) and energy (fuel) price scenarios.
        default:
          - uid: 1237868f-52ea-416c-9087-eef9dbde429d
            versionUid: cef750da-b26d-4da1-b67b-871281c3d551
        path: scenarios/
        required: true
      - name: ET Module Data
        description: >
          NISMOD Energy Transport Module data pack. Should contain full data
          setup for the model, including charging schedule parameters and
          vehicle trip starts and consumption scenarios (test outputs from the
          Transport model used to test running the et_module standalone).
        default:
          - uid: dbfe6814-3fd3-4e94-8c30-ccfec60c9989
            versionUid: df234857-a622-4b83-bec1-c72b1c7ed8b6
        path: et_module/
        required: true
      - name: LAD boundaries
        description: >
          LAD boundaries - shared definition for data exchange between models.
        default:
          - uid: 36adf09d-7657-4e46-a6d8-55dde43cbe51
            versionUid: 4050b797-0a12-4b86-9ca3-9edfde3aeb6d
          - uid: 40ba1196-6ee1-4be3-b813-471934bf3acd
            versionUid: adce60be-2019-4ec8-8f61-a297c5a26cc5
        path: lads/
        required: true
