name: Test Project
interval_definitions:
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
- description: One week in each season of 168 hours
  filename: seasonal_week.csv
  name: seasonal_week
- name: hourly
  description: 'Every hour in a year'
  filename: hourly_intervals.csv
- description: One representative day
  filename: annual_day.csv
  name: annual_day
narrative_sets:
- description: Describes the evolution of technology
  name: technology
- description: Describes the governance landscape
  name: governance
narratives:
- name: 'High Tech Demand Side Management'
  description: 'High penetration of SMART technology on the demand side'
  filename: high_tech_dsm.yml
  narrative_set: technology
region_definitions:
- description: ''
  filename: uk_nations_shp/regions.shp
  name: national
- description: National grid-gas exit zones
  filename: uk_nations_shp/regions.shp
  name: exit_zones
- description: 'Local Authority Districts (data from 2016, unchanged since 2009)'
  filename: lad_uk_2016-12/lad_uk_2016-12.shp
  name: lad_uk_2016
- description: Southampton LAD for transport test
  filename: lad_southampton/zones.shp
  name: lad_southampton
- description: Southampton LAD-LAD Origin-Destination for transport test
  filename: lad_southampton/od.geojson
  name: od_southampton
- description: Southampton whole system for transport test
  filename: lad_southampton/whole_system.geojson
  name: whole_system
scenario_sets:
- description: UK precipitation
  name: rainfall
- description: Growth in UK population
  name: population
- description: Gross value added
  name: gva
- description: Passenger OD flows for transport base year
  name: passenger_vehicle_OD
scenarios:
- name: et_demand_baseline
  description: 'Baseline GWh of transport for the UK'
  scenario_set: transport_energy_demand
  parameters:
  - name: electricity
    filename: et_demand_electricity.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: GWh
- name: pop_baseline
  description: 'Baseline Population for the UK'
  scenario_set: population
  parameters:
  - name: population
    filename: uk_population_by_district_codes_Baseline.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: pop_high
  description: 'High Population for the UK'
  scenario_set: population
  parameters:
  - name: population
    filename: uk_population_by_district_codes_High.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: pop_low
  description: 'Low Population for the UK'
  scenario_set: population
  parameters:
  - name: population
    filename: uk_population_by_district_codes_Low.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: gva_baseline
  description: 'Baseline gva for the UK'
  scenario_set: gva
  parameters:
  - name: gva
    filename: gva_sven.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: pounds
- name: Southampton-Southampton test OD
  description: Test data for transport base year
  scenario_set: passenger_vehicle_OD
  parameters:
    - name: flow
      filename: soton_passenger_vehicle_OD.csv
      spatial_resolution: od_southampton
      temporal_resolution: annual_day
      units: vehicles
units: units.txt
