name: NISMOD v2.0.0
units: units.txt
# ------------------------------------------------
scenarios:
- name: population
  description: UK population, total people
  provides:
  - name: population
    description: ''
    dims:
    - lad_uk_2016
    dtype: float
    unit: people
  variants:
  - name: pop_baseline
    description: Baseline population for the UK
    data:
      population: uk_population_by_district_codes_Baseline.csv
  - name: pop_high
    description: High population for the UK
    data:
      population: uk_population_by_district_codes_High.csv
  - name: pop_low
    description: Low population for the UK
    data:
      population: uk_population_by_district_codes_Low.csv
- name: gva
  description: Gross value added
  provides:
  - name: gva
    description: ''
    dims:
    - lad_uk_2016
    dtype: float
    unit: GBP
  variants:
  - name: gva_baseline
    description: Baseline gva for the UK
    data:
      gva: gva_sven.csv
- name: transport_energy_demand
  description: Hourly electricity demand of transport model
  provides:
  - name: electricity
    description: ''
    dims:
    - lad_uk_2016
    dtype: float
    unit: GWh
  variants:
  - name: et_demand_baseline
    description: Baseline GWh of transport for the UK
    data:
      electricity: et_demand_electricity.csv
- name: passenger_vehicle_OD
  description: Passenger OD flows for transport base year
  provides:
  - name: flow
    description: ''
    dims:
    - od_southampton
    - annual_day
    dtype: float
    unit: vehicles
  variants:
  - name: Southampton-Southampton test OD
    description: Test data for transport base year
    data:
      flow: soton_passenger_vehicle_OD.csv
- name: es_residential
  description: Dummy data for energy_supply model residential inputs
  provides:
  - name: residential_gas_boiler_gas
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: residential_electricity_boiler_electricity
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  variants:
  - name: es_residential_dummy
    description: Dummy data for residential inputs to energy supply model
    data:
      residential_gas_boiler_gas: residential_gas_boiler_gas.csv
      residential_electricity_boiler_electricity: residential_electricity_boiler_electricity.csv
- name: es_prices
  description: Dummy data for energy_supply prices data
  provides:
  - name: gas_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: electricity_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: gas_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: oil_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: coal_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: nuclearFuel_price
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/MWh
  - name: cost_of_carbon
    description: ''
    dims:
    - seasons
    dtype: float
    unit: GBP/Mt
  variants:
  - name: es_prices_dummy
    description: Dummy prices data to pass to the energy_supply toy model
    data:
      gas_price: ../energy_supply/scenarios/price.csv
      electricity_price: ../energy_supply/scenarios/price.csv
      oil_price: ../energy_supply/scenarios/price.csv
      coal_price: ../energy_supply/scenarios/price.csv
      nuclearFuel_price: ../energy_supply/scenarios/price.csv
      cost_of_carbon: ../energy_supply/scenarios/price.csv
- name: dummy_energy_demands
  description: Dummy energy demand data for the energy supply model
  provides:
  - name: elecload
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: gasload
    description: ''
    dims:
    - gas_nodes_minimal
    - seasonal_week
    dtype: float
    unit: mcm
  - name: residential_heatload
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: residential_gas_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: mcm
  - name: residential_electricity_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: service_heatload
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  - name: service_gas_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: mcm
  - name: service_electricity_non_heating
    description: ''
    dims:
    - energy_hub_min
    - seasonal_week
    dtype: float
    unit: MW
  variants:
  - name: es_energy_demand_minimal
    description: ''
    data:
      elecload: ../energy_supply/scenarios/energy_demand_minimal.csv
      gasload: ../energy_supply/scenarios/energy_demand_minimal_gasload.csv
      residential_heatload: ../energy_supply/scenarios/energy_demand_minimal.csv
      residential_gas_non_heating: ../energy_supply/scenarios/energy_demand_minimal.csv
      residential_electricity_non_heating: ../energy_supply/scenarios/energy_demand_minimal.csv
      service_heatload: ../energy_supply/scenarios/energy_demand_minimal.csv
      service_gas_non_heating: ../energy_supply/scenarios/energy_demand_minimal.csv
      service_electricity_non_heating: ../energy_supply/scenarios/energy_demand_minimal.csv
  - name: es_energy_demand_dummy
    description: ''
    data:
      elecload: ../energy_supply/scenarios/full/elecload.csv
      gasload: ../energy_supply/scenarios/full/gasload.csv
      residential_heatload: ../energy_supply/scenarios/full/residential_heatload.csv
      residential_gas_non_heating: ../energy_supply/scenarios/full/residential_gas_non_heating.csv
      residential_electricity_non_heating: ../energy_supply/scenarios/full/residential_electricity_non_heating.csv
      service_heatload: ../energy_supply/scenarios/full/service_heatload.csv
      service_gas_non_heating: ../energy_supply/scenarios/full/service_gas_non_heating.csv
      service_electricity_non_heating: ../energy_supply/scenarios/full/service_electricity_non_heating.csv
narratives:
- name: technology
  description: Describes the evolution of technology
  provides:
  - name: High Tech Demand Side Management
    description: High penetration of SMART technology on the demand side
    dtype: float
    unit: TODO
  - name: test_narrative
    description: High penetration of SMART technology on the demand side
    dtype: float
    unit: TODO
  variants:
  - name: test_narrative
    description: TODO
    data:
      'High Tech Demand Side Management': high_tech_dsm.yml
      test_narrative: high_tech_dsm.yml
- name: governance
  description: Describes the governance landscape
  provides: []
  variants:
  - name: TODO
    description: TODO
    data: {}
dimensions:
- name: hourly
  description: Every hour in a year
  elements: hourly_intervals.csv
- name: annual
  description: One annual interval of 8760 hours
  elements: annual_intervals.csv
- name: annual_day
  description: One representative day
  elements: annual_day.csv
- name: seasonal_week
  description: One week in each season mapped to all other weeks in the season
  elements: seasonal_week.csv
- name: seasons
  description: The seasons covered by the model
  elements: seasons.csv
- name: lad_uk_2016
  description: Local Authority Districts (data from 2016, unchanged since 2009)
  elements: ../energy_demand/region_definitions/same_as_scenario_data/lad_2016_uk_simplified.shp
- name: lad_southampton
  description: Southampton LAD for transport test
  elements: lad_southampton/zones.shp
- name: od_southampton
  description: Southampton LAD-LAD Origin-Destination for transport test
  elements: lad_southampton/od.geojson
- name: whole_system
  description: Southampton whole system for transport test
  elements: lad_southampton/whole_system.geojson
- name: national
  description: Boundary of Great Britain
  elements: national.shp
- name: energy_hub_min
  description: Boundaries of 2 Energy Hubs (ES test data set)
  elements: ../energy_supply/region_definitions/eh_region.shp
- name: energy_hub
  description: Boundaries of all 39 Energy Hubs
  elements: ../energy_supply/region_definitions/EH_Region_Boundaries.shp
- name: gas_nodes
  description: Points of all 87 gas offtake nodes
  elements: ../energy_supply/region_definitions/gas_nodes.shp
- name: gas_nodes_minimal
  description: Points of just 3 gas offtake nodes
  elements: ../energy_supply/region_definitions/gas_nodes_minimal.shp
- name: bus_bars
  description: Points of electricity transmission bus bars
  elements: ../energy_supply/region_definitions/bus_bars.shp
- name: broadband_distributions
  description: Broadband network distributions (Fixed network)
  elements: ../digital_comms/assets_layer4_distributions.shp
- name: broadband_cabinets
  description: Broadband network cabinets (Fixed network)
  elements: ../digital_comms/assets_layer3_cabinets.shp
