name: NISMOD v2.0.0
# ------------------------------------------------
scenario_sets:
- name: population
  description: UK population, total people
  facets:
  - name: population
    description: ''
- name: gva
  description: Gross value added
  facets:
  - name: gva
    description: ''
- name: transport_energy_demand
  description: Hourly electricity demand of transport model
  facets:
  - name: electricity
    description: ''
- name: passenger_vehicle_OD
  description: Passenger OD flows for transport base year
  facets:
  - name: flow
    description: ''
- name: es_residential
  description: Dummy data for energy_supply model residential inputs
  facets:
  - name: residential_gas_boiler_gas
    description: ''
  - name: residential_electricity_boiler_electricity
    description: ''
- name: es_prices
  description: Dummy data for energy_supply prices data
  facets:
  - name: gas_price
    description: ''
  - name: electricity_price
    description: ''
  - name: gas_price
    description: ''
  - name: oil_price
    description: ''
  - name: coal_price
    description: ''
  - name: nuclearFuel_price
    description: ''
  - name: cost_of_carbon
    description: ''
- name: dummy_energy_demands
  description: Dummy energy demand data for the energy supply model
  facets:
  - name: elecload
    description: ''
  - name: gasload
    description: ''
  - name: residential_gas_boiler_gas
    description: ''
  - name: residential_electricity_boiler_electricity
    description: ''
  - name: residential_gas_stirling_micro_gas
    description: ''
  - name: residential_electricity_heat_pumps_electricity
    description: ''
  - name: residential_electricity_district_heating_electricity
    description: ''
  - name: residential_gas_district_heating_CHP_gas
    description: ''
  - name: residential_gas_non_heating
    description: ''
  - name: residential_electricity_non_heating
    description: ''
  - name: service_gas_boiler_gas
    description: ''
  - name: service_electricity_boiler_electricity
    description: ''
  - name: service_gas_stirling_micro_gas
    description: ''
  - name: service_electricity_heat_pumps_electricity
    description: ''
  - name: service_electricity_district_heating_electricity
    description: ''
  - name: service_gas_district_heating_gas
    description: ''
  - name: service_gas_non_heating
    description: ''
  - name: service_electricity_non_heating
    description: ''
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- name: lad_uk_2016
  description: Local Authority Districts (data from 2016, unchanged since 2009)
  filename: ../energy_demand/region_definitions/same_as_scenario_data/lad_2016_uk_simplified.shp
- description: Southampton LAD for transport test
  filename: lad_southampton/zones.shp
  name: lad_southampton
- description: Southampton LAD-LAD Origin-Destination for transport test
  filename: lad_southampton/od.geojson
  name: od_southampton
- description: Southampton whole system for transport test
  filename: lad_southampton/whole_system.geojson
  name: whole_system
- description: Boundary of Great Britain
  filename: national.shp
  name: national
- description: Boundaries of 2 Energy Hubs (ES test data set)
  filename: ../energy_supply/region_definitions/eh_region.shp
  name: energy_hub_min
- description: Boundaries of all 39 Energy Hubs
  filename: ../energy_supply/region_definitions/EH_Region_Boundaries.shp
  name: energy_hub
- description: Points of all 87 gas offtake nodes
  filename: ../energy_supply/region_definitions/gas_nodes.shp
  name: gas_nodes
- description: Points of electricity transmission bus bars
  filename: ../energy_supply/region_definitions/bus_bars.shp
  name: bus_bars
- description: Broadband network distributions (Fixed network)
  filename: assets_broadband_network/assets_layer4_distributions.shp
  name: broadband_distributions
- description: Broadband network cabinets (Fixed network)
  filename: assets_broadband_network/assets_layer3_cabinets.shp
  name: broadband_cabinets
# ------------------------------------------------
interval_definitions:
# shared understanding of time intervals within a year
- name: hourly
  description: Every hour in a year
  filename: hourly_intervals.csv
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
- description: One representative day
  filename: annual_day.csv
  name: annual_day
- description: One week in each season mapped to all other weeks in the season
  filename: seasonal_week.csv
  name: seasonal_week
- description: The seasons covered by the model
  filename: seasons.csv
  name: seasons
# ------------------------------------------------
units: units.txt
# ------------------------------------------------
scenarios:
# given input data, required values for every year of a model run
- name: et_demand_baseline
  description: Baseline GWh of transport for the UK
  scenario_set: transport_energy_demand
  facets:
  - name: electricity
    filename: et_demand_electricity.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: GWh
- name: pop_baseline
  description: Baseline population for the UK
  scenario_set: population
  facets:
  - name: population
    filename: uk_population_by_district_codes_Baseline.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: pop_high
  description: High population for the UK
  scenario_set: population
  facets:
  - name: population
    filename: uk_population_by_district_codes_High.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: pop_low
  description: Low population for the UK
  scenario_set: population
  facets:
  - name: population
    filename: uk_population_by_district_codes_Low.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: gva_baseline
  description: Baseline gva for the UK
  scenario_set: gva
  facets:
  - name: gva
    filename: gva_sven.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: GBP
- name: Southampton-Southampton test OD
  description: Test data for transport base year
  scenario_set: passenger_vehicle_OD
  facets:
  - name: flow
    filename: soton_passenger_vehicle_OD.csv
    spatial_resolution: od_southampton
    temporal_resolution: annual_day
    units: vehicles
- description: Dummy data for residential inputs to energy supply model
  name: es_residential_dummy
  facets:
  - filename: residential_gas_boiler_gas.csv
    name: residential_gas_boiler_gas
    spatial_resolution: energy_hub_min
    temporal_resolution: seasonal_week
    units: MW
  - filename: residential_electricity_boiler_electricity.csv
    name: residential_electricity_boiler_electricity
    spatial_resolution: energy_hub_min
    temporal_resolution: seasonal_week
    units: MW
  scenario_set: es_residential
- description: Dummy prices data to pass to the energy_supply toy model
  name: es_prices_dummy
  facets:
  - filename: gas_price.csv
    name: gas_price
    spatial_resolution: national
    temporal_resolution: seasons
    units: GBP/MWh
  - filename: electricity_price.csv
    name: electricity_price
    spatial_resolution: national
    temporal_resolution: seasons
    units: GBP/MWh
  - filename: oil_price.csv
    name: oil_price
    spatial_resolution: national
    temporal_resolution: seasons
    units: GBP/MWh
  - filename: coal_price.csv
    name: coal_price
    spatial_resolution: national
    temporal_resolution: seasons
    units: GBP/MWh
  - filename: nuclear_fuel_price.csv
    name: nuclearFuel_price
    spatial_resolution: national
    temporal_resolution: seasons
    units: GBP/MWh
  - filename: cost_of_carbon.csv
    name: cost_of_carbon
    spatial_resolution: national
    temporal_resolution: seasons
    units: GBP/Mt
  scenario_set: es_prices
- name: es_energy_demand_dummy
  scenario_set: dummy_energy_demands
  description: ''
  facets:
  - filename: energy_supply/elecload.csv
    name: elecload
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: MW
  - filename: energy_supply/gasload.csv
    name: gasload
    spatial_resolution: gas_nodes
    temporal_resolution: seasonal_week
    units: mcm
  - filename: energy_supply/residential_heatload.csv
    name: residential_heatload
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: MW
  - filename: energy_supply/residential_gas_non_heating.csv
    name: residential_gas_non_heating
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: mcm
  - filename: energy_supply/residential_electricity_non_heating.csv
    name: residential_electricity_non_heating
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: MW
  - filename: energy_supply/service_heatload.csv
    name: service_heatload
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: MW
  - filename: energy_supply/service_gas_non_heating.csv
    name: service_gas_non_heating
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: MW
  - filename: energy_supply/service_electricity_non_heating.csv
    name: service_electricity_non_heating
    spatial_resolution: energy_hub
    temporal_resolution: seasonal_week
    units: MW
# ------------------------------------------------
narrative_sets:
- description: Describes the evolution of technology
  name: technology
- description: Describes the governance landscape
  name: governance
# ------------------------------------------------
narratives:
- name: High Tech Demand Side Management
  description: High penetration of SMART technology on the demand side
  filename: high_tech_dsm.yml
  narrative_set: technology
- name: test_narrative
  description: High penetration of SMART technology on the demand side
  filename: ../energy_demand/narratives/narrative_test.yml
  narrative_set: technology
