name: "Test Project"
# ------------------------------------------------
scenario_sets:
- name: population
  description: 'UK population, total people'
- name: gva
  description: 'Gross value added'
- name: transport_energy_demand
  description: 'Hourly electricity demand of transport model'
- description: Passenger OD flows for transport base year
  name: passenger_vehicle_OD
# ------------------------------------------------
region_definitions:
# shared understanding of regions within the modelled area (e.g. GB)
- name: lad_uk_2016
  description: 'Local Authority Districts (data from 2016, unchanged since 2009)'
  filename: ../energy_demand/region_definitions/same_as_scenario_data/lad_2016_uk_simplified.shp #lad_uk_2016-12/lad_uk_2016-12.shp
- description: Southampton LAD for transport test
  filename: lad_southampton/zones.shp
  name: lad_southampton
- description: Southampton LAD-LAD Origin-Destination for transport test
  filename: lad_southampton/od.geojson
  name: od_southampton
- description: Southampton whole system for transport test
  filename: lad_southampton/whole_system.geojson
  name: whole_system
# ------------------------------------------------
interval_definitions:
# shared understanding of time intervals within a year
- name: hourly
  description: 'Every hour in a year'
  filename: hourly_intervals.csv
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
- description: One representative day
  filename: annual_day.csv
  name: annual_day
# ------------------------------------------------
units: units.txt
# ------------------------------------------------
scenarios:
# given input data, required values for every year of a model run
- name: et_demand_baseline
  description: 'Baseline GWh of transport for the UK'
  scenario_set: transport_energy_demand
  facets:
  - name: electricity
    filename: et_demand_electricity.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: GWh
- name: pop_baseline
  description: 'Baseline population for the UK'
  scenario_set: population
  facets:
  - name: population
    filename: uk_population_by_district_codes_Baseline.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: pop_high
  description: 'High population for the UK'
  scenario_set: population
  facets:
  - name: population
    filename: uk_population_by_district_codes_High.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: pop_low
  description: 'Low population for the UK'
  scenario_set: population
  facets:
  - name: population
    filename: uk_population_by_district_codes_Low.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: people
- name: gva_baseline
  description: 'Baseline gva for the UK'
  scenario_set: gva
  facets:
  - name: gva
    filename: gva_sven.csv
    spatial_resolution: lad_uk_2016
    temporal_resolution: annual
    units: GBP
- name: Southampton-Southampton test OD
  description: Test data for transport base year
  scenario_set: passenger_vehicle_OD
  facets:
    - name: flow
      filename: soton_passenger_vehicle_OD.csv
      spatial_resolution: od_southampton
      temporal_resolution: annual_day
      units: vehicles
# ------------------------------------------------
narrative_sets:
- description: Describes the evolution of technology
  name: technology
- description: Describes the governance landscape
  name: governance
# ------------------------------------------------
narratives:
- name: 'High Tech Demand Side Management'
  description: 'High penetration of SMART technology on the demand side'
  filename: high_tech_dsm.yml
  narrative_set: technology
- name: 'test_narrative'
  description: 'High penetration of SMART technology on the demand side'
  filename: ../energy_demand/narratives/narrative_test.yml
  narrative_set: technology
