interval_definitions:
- description: One annual interval of 8760 hours
  filename: annual_intervals.csv
  name: annual
- description: One week in each season of 168 hours
  filename: seasonal_week.csv
  name: seasonal_week
name: Test Project
narrative_sets:
- description: Describes the evolution of technology
  name: technology
- description: Describes the governance landscape
  name: governance
narratives: []
region_definitions:
- description: ''
  filename: uk_nations_shp/regions.shp
  name: national
- description: ''
  filename: oxfordshire/regions.geojson
  name: oxfordshire
- description: National grid-gas exit zones
  filename: oxfordshire/regions.geojson
  name: exit_zones
scenario_sets:
- description: UK precipitation
  name: rainfall
- description: Growth in UK population
  name: population
scenarios: []
units: units.txt
