sector_models:
  - name: solid_waste
    path: ../data/solid_waste/__init__.py
    classname: SolidWAsteSectorModel
    config_dir: ../data/solid_waste
timesteps: timesteps.yaml
planning:
  pre_specified:
    use: true
    files:
      - ../data/pre-specified.yaml # The build instructions
  rule_based:
    use: false
  optimisation:
    use: false