convergence_absolute_tolerance: 1e-05
convergence_relative_tolerance: 1e-05
dependencies: []
description: ''
max_iterations: 1
name: adfadf
narrative_sets: []
scenario_sets:
- population
- gva
sector_models:
- convert_ed_to_es
- energy_supply
- energy_demand_constrained
