name: energy_demand_unconstrained
description: The future demand for energy in the UK
sector_models:
- energy_demand_unconstrained
scenarios:
- socio-economic
- temperature
narratives:
  - name: virtual_dw_stock
    description: Virtual dwelling stock mode
    provides:
      energy_demand_constrained:
        - virtual_dw_stock
    variants:
      - name: load_in_directly
        description: Loads in floor area directly
        data:
          virtual_dw_stock: ../../data/energy_demand/narratives/virtual_dw_stock_false
      - name: virtual_stock
        description: Creates virtual stock
        data:
          virtual_dw_stock: ../../data/energy_demand/narratives/virtual_stock_true
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_unconstrained
  sink_input: floor_area
  source: socio-economic
  source_output: floor_area
- sink: energy_demand_unconstrained
  sink_input: population
  source: socio-economic
  source_output: population
- sink: energy_demand_unconstrained
  sink_input: gva_per_head
  source: socio-economic
  source_output: gva_per_head
- sink: energy_demand_unconstrained
  sink_input: gva_per_sector
  source: socio-economic
  source_output: gva_per_sector
- sink: energy_demand_unconstrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_unconstrained
  sink_input: t_max
  source: temperature
  source_output: t_max
