convergence_relative_tolerance: 1e-05
sector_models:
- energy_supply
- energy_demand_constrained
- convert_ed_to_es
- aggregate_elecload
- aggregate_gasload
- remap_gas
- aggregate_residential_heatload
- aggregate_service_heatload
description: A full version of the energy demand - energy supply system-of-systems
  model
name: energy_supply_demand
scenarios:
- population
- es_prices
- gva
narratives: []
scenario_dependencies:
- source: population
  source_output: population
  sink: energy_demand_constrained
  sink_input: population
- source: gva
  source_output: gva
  sink: energy_demand_constrained
  sink_input: gva
- source: es_prices
  source_output: gas_price
  sink: energy_supply
  sink_input: gas_price
- source: es_prices
  source_output: electricity_price
  sink: energy_supply
  sink_input: electricity_price
- source: es_prices
  source_output: oil_price
  sink: energy_supply
  sink_input: oil_price
- source: es_prices
  source_output: coal_price
  sink: energy_supply
  sink_input: coal_price
- source: es_prices
  source_output: nuclearFuel_price
  sink: energy_supply
  sink_input: nuclearFuel_price
- source: es_prices
  source_output: cost_of_carbon
  sink: energy_supply
  sink_input: cost_of_carbon
model_dependencies:
- source: energy_demand_constrained
  source_output: residential_gas_boiler_gas
  sink: convert_ed_to_es
  sink_input: residential_gas_boiler_gas
- source: energy_demand_constrained
  source_output: residential_electricity_boiler_electricity
  sink: convert_ed_to_es
  sink_input: residential_electricity_boiler_electricity
- source: energy_demand_constrained
  source_output: residential_electricity_heat_pumps_electricity
  sink: convert_ed_to_es
  sink_input: residential_electricity_heat_pumps_electricity
- source: energy_demand_constrained
  source_output: residential_gas_district_heating_CHP_gas
  sink: convert_ed_to_es
  sink_input: residential_gas_district_heating_CHP_gas
- source: energy_demand_constrained
  source_output: residential_electricity_district_heating_electricity
  sink: convert_ed_to_es
  sink_input: residential_electricity_district_heating_electricity
- source: energy_demand_constrained
  source_output: residential_gas_stirling_micro_CHP_gas
  sink: convert_ed_to_es
  sink_input: residential_gas_stirling_micro_gas
- source: energy_demand_constrained
  source_output: service_gas_boiler_gas
  sink: convert_ed_to_es
  sink_input: service_gas_boiler_gas
- source: energy_demand_constrained
  source_output: service_electricity_boiler_electricity
  sink: convert_ed_to_es
  sink_input: service_electricity_boiler_electricity
- source: energy_demand_constrained
  source_output: service_electricity_heat_pumps_electricity
  sink: convert_ed_to_es
  sink_input: service_electricity_heat_pumps_electricity
- source: energy_demand_constrained
  source_output: service_gas_district_heating_CHP_gas
  sink: convert_ed_to_es
  sink_input: service_gas_district_heating_gas
- source: energy_demand_constrained
  source_output: service_electricity_district_heating_electricity
  sink: convert_ed_to_es
  sink_input: service_electricity_district_heating_electricity
- source: energy_demand_constrained
  source_output: service_gas_stirling_micro_CHP_gas
  sink: convert_ed_to_es
  sink_input: service_gas_stirling_micro_gas
- source: energy_demand_constrained
  source_output: industry_gas_boiler_gas
  sink: convert_ed_to_es
  sink_input: industry_gas_boiler_gas
- source: energy_demand_constrained
  source_output: industry_electricity_boiler_electricity
  sink: convert_ed_to_es
  sink_input: industry_electricity_boiler_electricity
- source: energy_demand_constrained
  source_output: industry_biomass_boiler_biomass
  sink: convert_ed_to_es
  sink_input: industry_biomass_boiler_biomass
- source: energy_demand_constrained
  source_output: industry_electricity_heat_pumps_electricity
  sink: convert_ed_to_es
  sink_input: industry_electricity_heat_pumps_electricity
- source: energy_demand_constrained
  source_output: industry_gas_district_heating_CHP_gas
  sink: convert_ed_to_es
  sink_input: industry_gas_district_heating_CHP_gas
- source: energy_demand_constrained
  source_output: industry_electricity_district_heating_electricity
  sink: convert_ed_to_es
  sink_input: industry_electricity_district_heating_electricity
- source: energy_demand_constrained
  source_output: industry_biomass_district_heating_biomass
  sink: convert_ed_to_es
  sink_input: industry_biomass_district_heating_biomass
- source: energy_demand_constrained
  source_output: industry_gas_stirling_micro_CHP_gas
  sink: convert_ed_to_es
  sink_input: industry_gas_stirling_micro_CHP_gas
- source: energy_demand_constrained
  source_output: residential_gas_non_heating
  sink: convert_ed_to_es
  sink_input: residential_gas_non_heating
- source: energy_demand_constrained
  source_output: residential_electricity_non_heating
  sink: convert_ed_to_es
  sink_input: residential_electricity_non_heating
- source: energy_demand_constrained
  source_output: service_gas_non_heating
  sink: convert_ed_to_es
  sink_input: service_gas_non_heating
- source: energy_demand_constrained
  source_output: service_electricity_non_heating
  sink: convert_ed_to_es
  sink_input: service_electricity_non_heating
- source: energy_demand_constrained
  source_output: industry_gas_non_heating
  sink: convert_ed_to_es
  sink_input: industry_gas_non_heating
- source: energy_demand_constrained
  source_output: industry_electricity_non_heating
  sink: convert_ed_to_es
  sink_input: industry_electricity_non_heating
- source: convert_ed_to_es
  source_output: industry_electricity_non_heating
  sink: aggregate_elecload
  sink_input: industry_electricity_non_heating
- source: convert_ed_to_es
  source_output: industry_electricity_boiler_electricity
  sink: aggregate_elecload
  sink_input: industry_electricity_boiler_electricity
- source: convert_ed_to_es
  source_output: industry_electricity_heat_pumps_electricity
  sink: aggregate_elecload
  sink_input: industry_electricity_heat_pumps_electricity
- source: convert_ed_to_es
  source_output: industry_electricity_district_heating_electricity
  sink: aggregate_elecload
  sink_input: industry_electricity_district_heating_electricity
- source: convert_ed_to_es
  source_output: residential_gas_boiler_gas
  sink: aggregate_residential_heatload
  sink_input: residential_gas_boiler_gas
- source: convert_ed_to_es
  source_output: residential_electricity_boiler_electricity
  sink: aggregate_residential_heatload
  sink_input: residential_electricity_boiler_electricity
- source: convert_ed_to_es
  source_output: residential_electricity_heat_pumps_electricity
  sink: aggregate_residential_heatload
  sink_input: residential_electricity_heat_pumps_electricity
- source: convert_ed_to_es
  source_output: residential_gas_district_heating_CHP_gas
  sink: aggregate_residential_heatload
  sink_input: residential_gas_district_heating_CHP_gas
- source: convert_ed_to_es
  source_output: residential_electricity_district_heating_electricity
  sink: aggregate_residential_heatload
  sink_input: residential_electricity_district_heating_electricity
- source: convert_ed_to_es
  source_output: residential_gas_stirling_micro_gas
  sink: aggregate_residential_heatload
  sink_input: residential_gas_stirling_micro_gas
- source: convert_ed_to_es
  source_output: service_gas_boiler_gas
  sink: aggregate_service_heatload
  sink_input: service_gas_boiler_gas
- source: convert_ed_to_es
  source_output: service_electricity_boiler_electricity
  sink: aggregate_service_heatload
  sink_input: service_electricity_boiler_electricity
- source: convert_ed_to_es
  source_output: service_electricity_heat_pumps_electricity
  sink: aggregate_service_heatload
  sink_input: service_electricity_heat_pumps_electricity
- source: convert_ed_to_es
  source_output: service_gas_district_heating_gas
  sink: aggregate_service_heatload
  sink_input: service_gas_district_heating_gas
- source: convert_ed_to_es
  source_output: service_electricity_district_heating_electricity
  sink: aggregate_service_heatload
  sink_input: service_electricity_district_heating_electricity
- source: convert_ed_to_es
  source_output: service_gas_stirling_micro_gas
  sink: aggregate_service_heatload
  sink_input: service_gas_stirling_micro_gas
- source: convert_ed_to_es
  source_output: residential_gas_non_heating
  sink: energy_supply
  sink_input: residential_gas_non_heating
- source: convert_ed_to_es
  source_output: residential_electricity_non_heating
  sink: energy_supply
  sink_input: residential_electricity_non_heating
- source: convert_ed_to_es
  source_output: service_gas_non_heating
  sink: energy_supply
  sink_input: service_gas_non_heating
- source: convert_ed_to_es
  source_output: service_electricity_non_heating
  sink: energy_supply
  sink_input: service_electricity_non_heating
- source: convert_ed_to_es
  source_output: industry_gas_boiler_gas
  sink: aggregate_gasload
  sink_input: industry_gas_boiler_gas
- source: convert_ed_to_es
  source_output: industry_biomass_boiler_biomass
  sink: aggregate_gasload
  sink_input: industry_biomass_boiler_biomass
- source: convert_ed_to_es
  source_output: industry_gas_district_heating_CHP_gas
  sink: aggregate_gasload
  sink_input: industry_gas_district_heating_CHP_gas
- source: convert_ed_to_es
  source_output: industry_biomass_district_heating_biomass
  sink: aggregate_gasload
  sink_input: industry_biomass_district_heating_biomass
- source: convert_ed_to_es
  source_output: industry_gas_stirling_micro_CHP_gas
  sink: aggregate_gasload
  sink_input: industry_gas_stirling_micro_CHP_gas
- source: convert_ed_to_es
  source_output: industry_gas_non_heating
  sink: aggregate_gasload
  sink_input: industry_gas_non_heating
- source: aggregate_elecload
  source_output: elecload
  sink: energy_supply
  sink_input: elecload
- source: aggregate_gasload
  source_output: gasload
  sink: remap_gas
  sink_input: gasload
- source: remap_gas
  source_output: gasload
  sink: energy_supply
  sink_input: gasload
- source: aggregate_service_heatload
  source_output: service_heatload
  sink: energy_supply
  sink_input: service_heatload
- source: aggregate_residential_heatload
  source_output: residential_heatload
  sink: energy_supply
  sink_input: residential_heatload
