description: Links the toy version of the energy supply model to dummy scenarios
name: energy_supply_toy
sector_models:
- energy_supply_toy
scenarios:
- es_prices
- dummy_energy_demands_minimal
narratives: []
scenario_dependencies:
- source: es_prices
  source_output: gas_price
  sink: energy_supply_toy
  sink_input: gas_price
- source: es_prices
  source_output: electricity_price
  sink: energy_supply_toy
  sink_input: electricity_price
- source: es_prices
  source_output: oil_price
  sink: energy_supply_toy
  sink_input: oil_price
- source: es_prices
  source_output: coal_price
  sink: energy_supply_toy
  sink_input: coal_price
- source: es_prices
  source_output: nuclearFuel_price
  sink: energy_supply_toy
  sink_input: nuclearFuel_price
- source: es_prices
  source_output: cost_of_carbon
  sink: energy_supply_toy
  sink_input: cost_of_carbon
- source: dummy_energy_demands_minimal
  source_output: residential_gas_non_heating
  sink: energy_supply_toy
  sink_input: residential_gas_non_heating
- source: dummy_energy_demands_minimal
  source_output: residential_electricity_non_heating
  sink: energy_supply_toy
  sink_input: residential_electricity_non_heating
- source: dummy_energy_demands_minimal
  source_output: service_gas_non_heating
  sink: energy_supply_toy
  sink_input: service_gas_non_heating
- source: dummy_energy_demands_minimal
  source_output: service_electricity_non_heating
  sink: energy_supply_toy
  sink_input: service_electricity_non_heating
- source: dummy_energy_demands_minimal
  source_output: elecload
  sink: energy_supply_toy
  sink_input: elecload
- source: dummy_energy_demands_minimal
  source_output: gasload
  sink: energy_supply_toy
  sink_input: gasload
- source: dummy_energy_demands_minimal
  source_output: service_heatload
  sink: energy_supply_toy
  sink_input: service_heatload
- source: dummy_energy_demands_minimal
  source_output: residential_heatload
  sink: energy_supply_toy
  sink_input: residential_heatload
model_dependencies: []
