name: energy_demand_unconstrained
sector_models:
- energy_demand_unconstrained
narratives:
- description: ''
  provides:
    energy_demand_unconstrained:
    - mode
  name: mode
  variants:
  - data:
      mode: ../energy_demand/narratives/mode_constrained.csv
    description: 
    name: constrained_mode
  - data:
      mode: ../energy_demand/narratives/mode_unconstrained.csv
    description: 
    name: unconstrained_mode
- description: ''
  provides:
    energy_demand_unconstrained:
    - air_leakage
  name: air_leakage
  variants:
  - data:
      air_leakage: ../energy_demand/narratives/air_leakage__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      air_leakage: ../energy_demand/narratives/air_leakage__flower.csv
    description: Central assumptions
    name: flower_narrative
  - data:
      air_leakage: ../energy_demand/narratives/air_leakage__progression.csv
    description: Central assumptions
    name: progression_narrative
  - data:
      air_leakage: ../energy_demand/narratives/air_leakage__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - assump_diff_floorarea_pp
  name: assump_diff_floorarea_pp
  variants:
  - data:
      assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__flower.csv
    description: Thousand flower assumptions
    name: flower_narrative
  - data:
      assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - cooled_floorarea
  name: cooled_floorarea
  variants:
  - data:
      cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - dm_improvement
  name: dm_improvement
  variants:
  - data:
      dm_improvement: ../energy_demand/narratives/dm_improvement__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      dm_improvement: ../energy_demand/narratives/dm_improvement__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      dm_improvement: ../energy_demand/narratives/dm_improvement__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      dm_improvement: ../energy_demand/narratives/dm_improvement__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - f_eff_achieved
  name: f_eff_achieved
  variants:
  - data:
      f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - generic_enduse_change
  name: generic_enduse_change
  variants:
  - data:
      generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - heat_recovered
  name: heat_recovered
  variants:
  - data:
      heat_recovered: ../energy_demand/narratives/heat_recovered__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      heat_recovered: ../energy_demand/narratives/heat_recovered__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      heat_recovered: ../energy_demand/narratives/heat_recovered__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      heat_recovered: ../energy_demand/narratives/heat_recovered__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: Change in heating
  provides:
    energy_demand_unconstrained:
    - rs_t_base_heating
    - ss_t_base_heating
    - is_t_base_heating
  name: t_base_heating
  variants:
  - data:
      is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__central.csv
      ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__central.csv
      rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__flower.csv
      ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__flower.csv
      rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__progression.csv
      ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__progression.csv
      rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__multivector.csv
      ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__multivector.csv
      rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - p_cold_rolling_steel
  name: p_cold_rolling_steel
  variants:
  - data:
      p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - smart_meter_p
  name: smart_meter_p
  variants:
  - data:
      smart_meter_p: ../energy_demand/narratives/smart_meter_p__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      smart_meter_p: ../energy_demand/narratives/smart_meter_p__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      smart_meter_p: ../energy_demand/narratives/smart_meter_p__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      smart_meter_p: ../energy_demand/narratives/smart_meter_p__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - generic_fuel_switch
  name: generic_fuel_switch
  variants:
  - data:
      generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
- description: ''
  provides:
    energy_demand_unconstrained:
    - switches_service
  name: switches_service
  variants:
  - data:
      switches_service: ../energy_demand/narratives/switches_service__central.csv
    description: Central assumptions
    name: central_narrative
  - data:
      switches_service: ../energy_demand/narratives/switches_service__flower.csv
    description: flower assumptions
    name: flower_narrative
  - data:
      switches_service: ../energy_demand/narratives/switches_service__progression.csv
    description: progression assumptions
    name: progression_narrative
  - data:
      switches_service: ../energy_demand/narratives/switches_service__multivector.csv
    description: multivector assumptions
    name: multivector_narrative
description: The future demand for energy in the UK
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_unconstrained
  sink_input: population
  source: population
  source_output: population
- sink: energy_demand_unconstrained
  sink_input: gva_per_head
  source: gva
  source_output: gva_per_head
- sink: energy_demand_unconstrained
  sink_input: gva_per_sector
  source: gva
  source_output: gva_per_sector
- sink: energy_demand_unconstrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_unconstrained
  sink_input: t_max
  source: temperature
  source_output: t_max
scenarios:
- gva
- temperature
- population
