name: energy_sd_optimised_corrected
description: A full version of the energy demand - energy supply system-of-systems
  model in unconstrained/optimised heat technology mode
sector_models:
  - energy_demand_unconstrained
  - apply_energy_correction_factors_unconstrained
  - aggregate_energy_optimised
  - convert_regions_ed_to_es_optimised
  - convert_intervals_ed_to_es_optimised
  - convert_units_ed_to_es_optimised
  - remap_gas
  - energy_supply_optimised
scenarios:
  - fuel_price
  - socio-economic
  - temperature
  - dummy_weather_inputs_full
  - dummy_energy_demands_full
  - biomass_waste_to_energy
  - elec_interconnector_prices
model_dependencies:
  # from energy demand to apply correction
  - source: energy_demand_unconstrained
    source_output: residential_gas
    sink: apply_energy_correction_factors_unconstrained
    sink_input: residential_gas
  - source: energy_demand_unconstrained
    source_output: residential_electricity
    sink: apply_energy_correction_factors_unconstrained
    sink_input: residential_electricity
  - source: energy_demand_unconstrained
    source_output: service_gas
    sink: apply_energy_correction_factors_unconstrained
    sink_input: service_gas
  - source: energy_demand_unconstrained
    source_output: service_electricity
    sink: apply_energy_correction_factors_unconstrained
    sink_input: service_electricity
  - source: energy_demand_unconstrained
    source_output: industry_gas
    sink: apply_energy_correction_factors_unconstrained
    sink_input: industry_gas
  - source: energy_demand_unconstrained
    source_output: industry_electricity
    sink: apply_energy_correction_factors_unconstrained
    sink_input: industry_electricity
  # from energy demand to aggregation
  - source: energy_demand_unconstrained
    source_output: residential_hydrogen
    sink: aggregate_energy_optimised
    sink_input: residential_hydrogen
  - source: energy_demand_unconstrained
    source_output: service_hydrogen
    sink: aggregate_energy_optimised
    sink_input: service_hydrogen
  - source: energy_demand_unconstrained
    source_output: industry_hydrogen
    sink: aggregate_energy_optimised
    sink_input: industry_hydrogen
  - source: energy_demand_unconstrained
    source_output: service_heat
    sink: aggregate_energy_optimised
    sink_input: service_heat
  - source: energy_demand_unconstrained
    source_output: industry_heat
    sink: aggregate_energy_optimised
    sink_input: industry_heat
  - source: energy_demand_unconstrained
    source_output: industry_oil
    sink: aggregate_energy_optimised
    sink_input: industry_oil
  - source: energy_demand_unconstrained
    source_output: service_oil
    sink: aggregate_energy_optimised
    sink_input: service_oil
  - source: energy_demand_unconstrained
    source_output: residential_oil
    sink: aggregate_energy_optimised
    sink_input: residential_oil
  - source: energy_demand_unconstrained
    source_output: industry_solid_fuel
    sink: aggregate_energy_optimised
    sink_input: industry_solid_fuel
  - source: energy_demand_unconstrained
    source_output: service_solid_fuel
    sink: aggregate_energy_optimised
    sink_input: service_solid_fuel
  - source: energy_demand_unconstrained
    source_output: residential_solid_fuel
    sink: aggregate_energy_optimised
    sink_input: residential_solid_fuel
  # from apply correction to region conversion
  - source: apply_energy_correction_factors_unconstrained
    source_output: residential_gas
    sink: convert_regions_ed_to_es_optimised
    sink_input: gasload_non_heat_res
  - source: apply_energy_correction_factors_unconstrained
    source_output: residential_electricity
    sink: convert_regions_ed_to_es_optimised
    sink_input: elecload_non_heat_res
  - source: apply_energy_correction_factors_unconstrained
    source_output: service_gas
    sink: convert_regions_ed_to_es_optimised
    sink_input: gasload_non_heat_com
  - source: apply_energy_correction_factors_unconstrained
    source_output: service_electricity
    sink: convert_regions_ed_to_es_optimised
    sink_input: elecload_non_heat_com
  - source: apply_energy_correction_factors_unconstrained
    source_output: industry_gas
    sink: convert_regions_ed_to_es_optimised
    sink_input: gasload
  - source: apply_energy_correction_factors_unconstrained
    source_output: industry_electricity
    sink: convert_regions_ed_to_es_optimised
    sink_input: elecload
  # from energy demand to region conversion
  - source: energy_demand_unconstrained
    source_output: residential_heat
    sink: convert_regions_ed_to_es_optimised
    sink_input: heatload_res
  # from aggregation to region conversion
  - source: aggregate_energy_optimised
    source_output: hydrogen_non_heat_eh
    sink: convert_regions_ed_to_es_optimised
    sink_input: hydrogen_non_heat_eh
  - source: aggregate_energy_optimised
    source_output: heatload_com
    sink: convert_regions_ed_to_es_optimised
    sink_input: heatload_com
  - source: aggregate_energy_optimised
    source_output: oil_non_heat_eh
    sink: convert_regions_ed_to_es_optimised
    sink_input: oil_non_heat_eh
  - source: aggregate_energy_optimised
    source_output: solid_fuel_non_heat_eh
    sink: convert_regions_ed_to_es_optimised
    sink_input: solid_fuel_non_heat_eh
  # from region conversion to interval conversion
  - source: convert_regions_ed_to_es_optimised
    source_output: gasload_non_heat_res
    sink: convert_intervals_ed_to_es_optimised
    sink_input: gasload_non_heat_res
  - source: convert_regions_ed_to_es_optimised
    source_output: elecload_non_heat_res
    sink: convert_intervals_ed_to_es_optimised
    sink_input: elecload_non_heat_res
  - source: convert_regions_ed_to_es_optimised
    source_output: heatload_res
    sink: convert_intervals_ed_to_es_optimised
    sink_input: heatload_res
  - source: convert_regions_ed_to_es_optimised
    source_output: gasload_non_heat_com
    sink: convert_intervals_ed_to_es_optimised
    sink_input: gasload_non_heat_com
  - source: convert_regions_ed_to_es_optimised
    source_output: elecload_non_heat_com
    sink: convert_intervals_ed_to_es_optimised
    sink_input: elecload_non_heat_com
  - source: convert_regions_ed_to_es_optimised
    source_output: heatload_com
    sink: convert_intervals_ed_to_es_optimised
    sink_input: heatload_com
  - source: convert_regions_ed_to_es_optimised
    source_output: gasload
    sink: convert_intervals_ed_to_es_optimised
    sink_input: gasload
  - source: convert_regions_ed_to_es_optimised
    source_output: elecload
    sink: convert_intervals_ed_to_es_optimised
    sink_input: elecload
  - source: convert_regions_ed_to_es_optimised
    source_output: hydrogen_non_heat_eh
    sink: convert_intervals_ed_to_es_optimised
    sink_input: hydrogen_non_heat_eh
  - source: convert_regions_ed_to_es_optimised
    source_output: oil_non_heat_eh
    sink: convert_intervals_ed_to_es_optimised
    sink_input: oil_non_heat_eh
  - source: convert_regions_ed_to_es_optimised
    source_output: solid_fuel_non_heat_eh
    sink: convert_intervals_ed_to_es_optimised
    sink_input: solid_fuel_non_heat_eh
  # from interval conversion to unit conversion
  - source: convert_intervals_ed_to_es_optimised
    source_output: gasload_non_heat_res
    sink: convert_units_ed_to_es_optimised
    sink_input: gasload_non_heat_res
  - source: convert_intervals_ed_to_es_optimised
    source_output: elecload_non_heat_res
    sink: convert_units_ed_to_es_optimised
    sink_input: elecload_non_heat_res
  - source: convert_intervals_ed_to_es_optimised
    source_output: heatload_res
    sink: convert_units_ed_to_es_optimised
    sink_input: heatload_res
  - source: convert_intervals_ed_to_es_optimised
    source_output: gasload_non_heat_com
    sink: convert_units_ed_to_es_optimised
    sink_input: gasload_non_heat_com
  - source: convert_intervals_ed_to_es_optimised
    source_output: elecload_non_heat_com
    sink: convert_units_ed_to_es_optimised
    sink_input: elecload_non_heat_com
  - source: convert_intervals_ed_to_es_optimised
    source_output: heatload_com
    sink: convert_units_ed_to_es_optimised
    sink_input: heatload_com
  - source: convert_intervals_ed_to_es_optimised
    source_output: gasload
    sink: convert_units_ed_to_es_optimised
    sink_input: gasload
  - source: convert_intervals_ed_to_es_optimised
    source_output: elecload
    sink: convert_units_ed_to_es_optimised
    sink_input: elecload
  - source: convert_intervals_ed_to_es_optimised
    source_output: hydrogen_non_heat_eh
    sink: convert_units_ed_to_es_optimised
    sink_input: hydrogen_non_heat_eh
  - source: convert_intervals_ed_to_es_optimised
    source_output: oil_non_heat_eh
    sink: convert_units_ed_to_es_optimised
    sink_input: oil_non_heat_eh
  - source: convert_intervals_ed_to_es_optimised
    source_output: solid_fuel_non_heat_eh
    sink: convert_units_ed_to_es_optimised
    sink_input: solid_fuel_non_heat_eh
  # from unit conversion to remap gas nodes
  - source: convert_units_ed_to_es_optimised
    source_output: gasload
    sink: remap_gas
    sink_input: gasload
  # remap gas nodes to energy supply
  - source: remap_gas
    source_output: gasload
    sink: energy_supply_optimised
    sink_input: gasload
  # from unit conversion to energy supply
  - source: convert_units_ed_to_es_optimised
    source_output: elecload
    sink: energy_supply_optimised
    sink_input: elecload
  - source: convert_units_ed_to_es_optimised
    source_output: gasload_non_heat_res
    sink: energy_supply_optimised
    sink_input: gasload_non_heat_res
  - source: convert_units_ed_to_es_optimised
    source_output: elecload_non_heat_res
    sink: energy_supply_optimised
    sink_input: elecload_non_heat_res
  - source: convert_units_ed_to_es_optimised
    source_output: gasload_non_heat_com
    sink: energy_supply_optimised
    sink_input: gasload_non_heat_com
  - source: convert_units_ed_to_es_optimised
    source_output: elecload_non_heat_com
    sink: energy_supply_optimised
    sink_input: elecload_non_heat_com
  - source: convert_units_ed_to_es_optimised
    source_output: hydrogen_non_heat_eh
    sink: energy_supply_optimised
    sink_input: hydrogen_non_heat_eh
  - source: convert_units_ed_to_es_optimised
    source_output: heatload_res
    sink: energy_supply_optimised
    sink_input: heatload_res
  - source: convert_units_ed_to_es_optimised
    source_output: heatload_com
    sink: energy_supply_optimised
    sink_input: heatload_com
  - source: convert_units_ed_to_es_optimised
    source_output: oil_non_heat_eh
    sink: energy_supply_optimised
    sink_input: oil_non_heat_eh
  - source: convert_units_ed_to_es_optimised
    source_output: solid_fuel_non_heat_eh
    sink: energy_supply_optimised
    sink_input: solid_fuel_non_heat_eh
scenario_dependencies:
  - sink: energy_demand_unconstrained
    sink_input: floor_area
    source: socio-economic
    source_output: floor_area
  - source: fuel_price
    source_output: energy_supply_price
    sink: energy_supply_optimised
    sink_input: fuel_price
  - source: socio-economic
    source_output: gva_per_head
    sink: energy_demand_unconstrained
    sink_input: gva_per_head
  - source: socio-economic
    source_output: gva_per_sector
    sink: energy_demand_unconstrained
    sink_input: gva_per_sector
  - source: socio-economic
    source_output: population
    sink: energy_demand_unconstrained
    sink_input: population
  - source: temperature
    source_output: t_min
    sink: energy_demand_unconstrained
    sink_input: t_min
  - source: temperature
    source_output: t_max
    sink: energy_demand_unconstrained
    sink_input: t_max
  - source: dummy_weather_inputs_full
    source_output: wind_speed_eh
    sink: energy_supply_optimised
    sink_input: wind_speed_eh
  - source: dummy_weather_inputs_full
    source_output: wind_speed_bus
    sink: energy_supply_optimised
    sink_input: wind_speed_bus
  - source: dummy_weather_inputs_full
    source_output: insolation_eh
    sink: energy_supply_optimised
    sink_input: insolation_eh
  - source: dummy_weather_inputs_full
    source_output: insolation_bus
    sink: energy_supply_optimised
    sink_input: insolation_bus
  - source: biomass_waste_to_energy
    source_output: biomass_feedstock
    sink: energy_supply_optimised
    sink_input: biomass_feedstock
  - source: biomass_waste_to_energy
    source_output: municipal_waste
    sink: energy_supply_optimised
    sink_input: municipal_waste
  - source: elec_interconnector_prices
    source_output: elec_int
    sink: energy_supply_optimised
    sink_input: elec_int
  - source: dummy_energy_demands_full
    source_output: elec_trans
    sink: energy_supply_optimised
    sink_input: elec_trans
  - source: dummy_energy_demands_full
    source_output: EV_Cap
    sink: energy_supply_optimised
    sink_input: EV_Cap
narratives: []
