convergence_absolute_tolerance: 1.0e-05
convergence_relative_tolerance: 1.0e-05
dependencies:
#  Scenarios to Energy Demand
- sink_model: energy_demand_constrained
  sink_model_input: population
  source_model: population
  source_model_output: population
- sink_model: energy_demand_constrained
  sink_model_input: gva
  source_model: gva
  source_model_output: gva
#  Energy Demand to Convertor
- sink_model: convert_ed_to_es
  sink_model_input: residential_gas_boiler_gas
  source_model_output: residential_gas_boiler_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_electricity_boiler_electricity
  source_model_output: residential_electricity_boiler_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_electricity_heat_pumps_electricity
  source_model_output: residential_electricity_heat_pumps_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_gas_district_heating_CHP_gas
  source_model_output: residential_gas_district_heating_CHP_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_electricity_district_heating_electricity
  source_model_output: residential_electricity_district_heating_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_gas_stirling_micro_gas
  source_model_output: residential_gas_stirling_micro_CHP_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_gas_boiler_gas
  source_model_output: service_gas_boiler_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_electricity_boiler_electricity
  source_model_output: service_electricity_boiler_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_electricity_heat_pumps_electricity
  source_model_output: service_electricity_heat_pumps_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_gas_district_heating_gas
  source_model_output: service_gas_district_heating_CHP_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_electricity_district_heating_electricity
  source_model_output: service_electricity_district_heating_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_gas_stirling_micro_gas
  source_model_output: service_gas_stirling_micro_CHP_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_gas_boiler_gas
  source_model_output: industry_gas_boiler_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_electricity_boiler_electricity
  source_model_output: industry_electricity_boiler_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_biomass_boiler_biomass
  source_model_output: industry_biomass_boiler_biomass
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_electricity_heat_pumps_electricity
  source_model_output: industry_electricity_heat_pumps_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_gas_district_heating_CHP_gas
  source_model_output: industry_gas_district_heating_CHP_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_electricity_district_heating_electricity
  source_model_output: industry_electricity_district_heating_electricity
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_biomass_district_heating_biomass
  source_model_output: industry_biomass_district_heating_biomass
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_gas_stirling_micro_CHP_gas
  source_model_output: industry_gas_stirling_micro_CHP_gas
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_gas_non_heating
  source_model_output: residential_gas_non_heating
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: residential_electricity_non_heating
  source_model_output: residential_electricity_non_heating
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_gas_non_heating
  source_model_output: service_gas_non_heating
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: service_electricity_non_heating
  source_model_output: service_electricity_non_heating
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_gas_non_heating
  source_model_output: industry_gas_non_heating
  source_model: energy_demand_constrained
- sink_model: convert_ed_to_es
  sink_model_input: industry_electricity_non_heating
  source_model_output: industry_electricity_non_heating
  source_model: energy_demand_constrained
# Scenario to Energy Supply
- sink_model: energy_supply
  sink_model_input: gas_price
  source_model: es_prices
  source_model_output: gas_price
- sink_model: energy_supply
  sink_model_input: electricity_price
  source_model: es_prices
  source_model_output: electricity_price
- sink_model: energy_supply
  sink_model_input: oil_price
  source_model: es_prices
  source_model_output: oil_price
- sink_model: energy_supply
  sink_model_input: coal_price
  source_model: es_prices
  source_model_output: coal_price
- sink_model: energy_supply
  sink_model_input: nuclearFuel_price
  source_model: es_prices
  source_model_output: nuclearFuel_price
- sink_model: energy_supply
  sink_model_input: cost_of_carbon
  source_model: es_prices
  source_model_output: cost_of_carbon
# Convertor to aggregate elecload
- sink_model: aggregate_elecload
  sink_model_input: industry_electricity_non_heating
  source_model_output: industry_electricity_non_heating
  source_model: convert_ed_to_es
- sink_model: aggregate_elecload
  sink_model_input: industry_electricity_boiler_electricity
  source_model_output: industry_electricity_boiler_electricity
  source_model: convert_ed_to_es
- sink_model: aggregate_elecload
  sink_model_input: industry_electricity_heat_pumps_electricity
  source_model_output: industry_electricity_heat_pumps_electricity
  source_model: convert_ed_to_es
- sink_model: aggregate_elecload
  sink_model_input: industry_electricity_district_heating_electricity
  source_model_output: industry_electricity_district_heating_electricity
  source_model: convert_ed_to_es
# Convertor to Energy Supply
- sink_model: energy_supply
  sink_model_input: residential_gas_boiler_gas
  source_model_output: residential_gas_boiler_gas
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_electricity_boiler_electricity
  source_model_output: residential_electricity_boiler_electricity
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_electricity_heat_pumps_electricity
  source_model_output: residential_electricity_heat_pumps_electricity
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_gas_district_heating_CHP_gas
  source_model_output: residential_gas_district_heating_CHP_gas
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_electricity_district_heating_electricity
  source_model_output: residential_electricity_district_heating_electricity
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_gas_stirling_micro_gas
  source_model_output: residential_gas_stirling_micro_gas
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_gas_boiler_gas
  source_model_output: service_gas_boiler_gas
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_electricity_boiler_electricity
  source_model_output: service_electricity_boiler_electricity
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_electricity_heat_pumps_electricity
  source_model_output: service_electricity_heat_pumps_electricity
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_gas_district_heating_gas
  source_model_output: service_gas_district_heating_gas
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_electricity_district_heating_electricity
  source_model_output: service_electricity_district_heating_electricity
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_gas_stirling_micro_gas
  source_model_output: service_gas_stirling_micro_gas
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_gas_non_heating
  source_model_output: residential_gas_non_heating
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: residential_electricity_non_heating
  source_model_output: residential_electricity_non_heating
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_gas_non_heating
  source_model_output: service_gas_non_heating
  source_model: convert_ed_to_es
- sink_model: energy_supply
  sink_model_input: service_electricity_non_heating
  source_model_output: service_electricity_non_heating
  source_model: convert_ed_to_es
# Convertor to aggregate gasload
- sink_model: aggregate_gasload
  sink_model_input: industry_gas_boiler_gas
  source_model_output: industry_gas_boiler_gas
  source_model: convert_ed_to_es
- sink_model: aggregate_gasload
  sink_model_input: industry_biomass_boiler_biomass
  source_model_output: industry_biomass_boiler_biomass
  source_model: convert_ed_to_es
- sink_model: aggregate_gasload
  sink_model_input: industry_gas_district_heating_CHP_gas
  source_model_output: industry_gas_district_heating_CHP_gas
  source_model: convert_ed_to_es
- sink_model: aggregate_gasload
  sink_model_input: industry_biomass_district_heating_biomass
  source_model_output: industry_biomass_district_heating_biomass
  source_model: convert_ed_to_es
- sink_model: aggregate_gasload
  sink_model_input: industry_gas_stirling_micro_CHP_gas
  source_model_output: industry_gas_stirling_micro_CHP_gas
  source_model: convert_ed_to_es
- sink_model: aggregate_gasload
  sink_model_input: industry_gas_non_heating
  source_model_output: industry_gas_non_heating
  source_model: convert_ed_to_es
# Aggregate elecload to energy supply
- source_model: aggregate_elecload
  sink_model_input: elecload
  source_model_output: elecload
  sink_model: energy_supply
# Aggregate gasload to remap_gas
- source_model: aggregate_gasload
  sink_model_input: gasload
  source_model_output: gasload
  sink_model: remap_gas
# Aggregate gasload to energy supply
- source_model: remap_gas
  sink_model_input: gasload
  source_model_output: gasload
  sink_model: energy_supply
description: A full version of the energy demand - energy supply system-of-systems
  model
max_iterations: '100'
name: energy_supply_demand
scenario_sets:
- population
- es_prices
- gva
sector_models:
- energy_supply
- energy_demand_constrained
- convert_ed_to_es
- aggregate_elecload
- aggregate_gasload
- remap_gas
