name: energy_demand_unconstrained
sector_models:
- energy_demand_unconstrained
narratives: []
description: The future demand for energy in the UK
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_unconstrained
  sink_input: population
  source: population
  source_output: population
- sink: energy_demand_unconstrained
  sink_input: gva_per_head
  source: gva
  source_output: gva_per_head
- sink: energy_demand_unconstrained
  sink_input: gva_per_sector
  source: gva
  source_output: gva_per_sector
- sink: energy_demand_unconstrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_unconstrained
  sink_input: t_max
  source: temperature
  source_output: t_max
scenarios:
- gva
- temperature
- population
