name: energy_demand_constrained
description: The future demand for energy in the UK
sector_models:
- energy_demand_constrained
scenarios:
- socio-economic
- temperature
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_constrained
  sink_input: floor_area
  source: socio-economic
  source_output: floor_area
- sink: energy_demand_constrained
  sink_input: population
  source: socio-economic
  source_output: population
- sink: energy_demand_constrained
  sink_input: gva_per_head
  source: socio-economic
  source_output: gva_per_head
- sink: energy_demand_constrained
  sink_input: gva_per_sector
  source: socio-economic
  source_output: gva_per_sector
- sink: energy_demand_constrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_constrained
  sink_input: t_max
  source: temperature
  source_output: t_max
narratives: []
