name: energy_supply_optimised
description: Contains only energy supply wrapper with full data and full energy demand
  scenarios
sector_models:
- energy_supply_optimised
model_dependencies: []
scenarios:
- fuel_price
- dummy_energy_demands_full
- dummy_weather_inputs_full
- biomass_waste_to_energy
- elec_interconnector_prices
narratives:
  - name: load_shedding
    description: Costs of shedding load
    provides:
      energy_supply_optimised:
      - LoadShed_elec
      - LoadShed_gas
    variants:
      - name: high_cost
        description: very high cost load shedding
        data:
          LoadShed_elec: ../../data/energy_supply/narratives/high_load_shed
          LoadShed_gas: ../../data/energy_supply/narratives/high_load_shed
  - name: operation_mode
    description: operation mode for energy supply system
    provides:
      energy_supply_optimised:
      - operation_mode
    variants:
      - name: decentral
        decription: decentralised operating mode
        data:
          operation_mode: ../../data/energy_supply/parameters/op_mode_decentral
      - name: central
        decription: centralised operating mode
        data:
          operation_mode: ../../data/energy_supply/parameters/op_mode_central
  - name: heat_supply_strategy
    description: heat supply strategy for operation
    provides:
      energy_supply_optimised:
      - heat_supply_strategy
    variants:
      - name: full_electric
        decription: full electric heating
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_fullelectric
      - name: heat_networks
        decription: heat network domination for heating
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_heatnetworks
      - name: green_gas
        decription: green gas mixture for heat supply
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_greengas
      - name: national_grid_fes
        decription: green gas mixture for heat supply
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_national_grid_fes
  - name: sensitivity_mode
    description: selection of the sensitivity analysis
    provides:
      energy_supply_optimised:
      - sensitivity_mode
    variants:
      - name: wind_increase
        decription: overall increase in wind speed magnitude
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_wind_increase
      - name: wind_decrease
        decription: overall decrease in wind speed magnitude
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_wind_decrease
      - name: peak_increase
        decription: increase in peak demand only for heat, non-heat electricity and non-heat gas
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_peak
      - name: dsm
        decription: dsm opportunity for EV charging demand, non-heat electricity and non-heat gas
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_dsm
      - name: demand_reduction
        decription: further demand reduction for heat, non-heat electricity and non-heat gas
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_demand_reduction
      - name: ev_demand_increase
        decription: an overall increase to EV charging demand
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_ev_demand_increase
      - name: ev_demand_decrease
        decription: an overall decrease to EV charging demand
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_ev_demand_decrease
      - name: ev_residential_public_charging
        decription: assign different shares for residential(slow) and public (fast and rapid) charging within a day
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_residential_charging
      - name: ev_battery_size_change
        decription: increases default ev battery size used for V2G services
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_ev_battery_size
      - name: transport_energy_demand_reduction
        decription: reduces both EV charging and hydrogen demand from transport
        data:
          sensitivity_mode: ../../data/energy_supply/parameters/sensitivity_transport_demand_reduction 
  - name: emissions_constraint
    description: pre defined emissions constraint
    provides:
      energy_supply_optimised:
      - emissions_constraint
    variants:
      - name: emissions_constraint_on
        decription: energy supply subjected to pre-defined emissions constraint
        data:
          emissions_constraint: ../../data/energy_supply/parameters/emissions_constraint_on
  - name: ev_smart_charging
    description: enable/disable smart chariging of EVs
    provides:
      energy_supply_optimised:
      - ev_smart_charging
    variants:
      - name: ev_smart_charging_enabled
        decription: energy supply subjected to smart charging of EVs
        data:
          ev_smart_charging: ../../data/energy_supply/parameters/ev_smart_charging_enabled
  - name: ev_vehicle_to_grid
    description: enable/disable vehicle to grid services of EVs
    provides:
      energy_supply_optimised:
      - ev_vehicle_to_grid
    variants:
      - name: ev_vehicle_to_grid_enabled
        decription: energy supply subjected to EV vehicle to grid services
        data:
          ev_vehicle_to_grid: ../../data/energy_supply/parameters/ev_vehicle_to_grid_enabled
  - name: unit_commitment
    description: unit commitment function for thermal power stations
    provides:
      energy_supply_optimised:
      - unit_commitment
    variants:
      - name: unit_commitment_on
        decription: enable unit commitment functions
        data:
          unit_commitment: ../../data/energy_supply/parameters/unit_commitment_on
  - name: interconnector_neutral
    description: Enable / Disable energy flow neutral constraint for electricity interconnectors
    provides:
      energy_supply_optimised:
      - interconnector_neutral
    variants:
      - name: interconnector_neutral_off
        decription: disable energy neutral constraint
        data:
          interconnector_neutral: ../../data/energy_supply/parameters/interconnector_neutral_off
scenario_dependencies:
- source: fuel_price
  source_output: energy_supply_price
  sink: energy_supply_optimised
  sink_input: fuel_price
- source: dummy_energy_demands_full
  source_output: elecload
  sink: energy_supply_optimised
  sink_input: elecload
- source: dummy_energy_demands_full
  source_output: gasload
  sink: energy_supply_optimised
  sink_input: gasload
- source: dummy_energy_demands_full
  source_output: residential_gas_non_heating
  sink: energy_supply_optimised
  sink_input: gasload_non_heat_res
- source: dummy_energy_demands_full
  source_output: residential_electricity_non_heating
  sink: energy_supply_optimised
  sink_input: elecload_non_heat_res
- source: dummy_energy_demands_full
  source_output: service_gas_non_heating
  sink: energy_supply_optimised
  sink_input: gasload_non_heat_com
- source: dummy_energy_demands_full
  source_output: service_electricity_non_heating
  sink: energy_supply_optimised
  sink_input: elecload_non_heat_com
- source: dummy_energy_demands_full
  source_output: hydrogen_non_heating
  sink: energy_supply_optimised
  sink_input: hydrogen_non_heat_eh
- source: dummy_energy_demands_full
  source_output: hydrogen_trans
  sink: energy_supply_optimised
  sink_input: hydrogen_trans
- source: dummy_energy_demands_full
  source_output: oil_non_heat_eh
  sink: energy_supply_optimised
  sink_input: oil_non_heat_eh
- source: dummy_energy_demands_full
  source_output: solid_fuel_non_heat_eh
  sink: energy_supply_optimised
  sink_input: solid_fuel_non_heat_eh
- source: dummy_energy_demands_full
  source_output: residential_heatload
  sink: energy_supply_optimised
  sink_input: heatload_res
- source: dummy_energy_demands_full
  source_output: service_heatload
  sink: energy_supply_optimised
  sink_input: heatload_com
- source: dummy_weather_inputs_full
  source_output: wind_speed_eh
  sink: energy_supply_optimised
  sink_input: wind_speed_eh
- source: dummy_weather_inputs_full
  source_output: wind_speed_bus
  sink: energy_supply_optimised
  sink_input: wind_speed_bus
- source: dummy_weather_inputs_full
  source_output: insolation_eh
  sink: energy_supply_optimised
  sink_input: insolation_eh
- source: dummy_weather_inputs_full
  source_output: insolation_bus
  sink: energy_supply_optimised
  sink_input: insolation_bus
- source: dummy_energy_demands_full
  source_output: elec_trans
  sink: energy_supply_optimised
  sink_input: elec_trans
- source: dummy_energy_demands_full
  source_output: EV_Cap
  sink: energy_supply_optimised
  sink_input: EV_Cap
- source: biomass_waste_to_energy
  source_output: biomass_feedstock
  sink: energy_supply_optimised
  sink_input: biomass_feedstock
- source: biomass_waste_to_energy
  source_output: municipal_waste
  sink: energy_supply_optimised
  sink_input: municipal_waste
- source: elec_interconnector_prices
  source_output: elec_int
  sink: energy_supply_optimised
  sink_input: elec_int
