name: energy_supply_constrained
narratives:
- variants:
  - data:
      LoadShed_elec: ../../data/energy_supply/narratives/high_load_shed.csv
      LoadShed_gas: ../../data/energy_supply/narratives/high_load_shed.csv
    description: very high cost load shedding
    name: high_cost
  sos_model: energy_supply_only
  description: Costs of shedding load
  name: load_shedding
  provides:
    energy_supply_constrained:
    - LoadShed_elec
    - LoadShed_gas
scenario_dependencies:
- source: fuel_price
  source_output: energy_supply_price
  sink: energy_supply_constrained
  sink_input: fuel_price
- source: dummy_energy_demands_full
  source_output: elecload
  sink: energy_supply_constrained
  sink_input: elecload
- source: dummy_energy_demands_full
  source_output: gasload
  sink: energy_supply_constrained
  sink_input: gasload
- source: dummy_energy_demands_full
  source_output: residential_gas_non_heating
  sink: energy_supply_constrained
  sink_input: gasload_non_heat_res
- source: dummy_energy_demands_full
  source_output: residential_electricity_non_heating
  sink: energy_supply_constrained
  sink_input: elecload_non_heat_res
- source: dummy_energy_demands_full
  source_output: service_gas_non_heating
  sink: energy_supply_constrained
  sink_input: gasload_non_heat_com
- source: dummy_energy_demands_full
  source_output: service_electricity_non_heating
  sink: energy_supply_constrained
  sink_input: elecload_non_heat_com
- source: dummy_energy_demands_full
  source_output: hydrogen_non_heating
  sink: energy_supply_constrained
  sink_input: hydrogen_non_heat_eh
- source: dummy_energy_demands_full
  source_output: building_biomass_boiler
  sink: energy_supply_constrained
  sink_input: building_biomass_boiler
- source: dummy_energy_demands_full
  source_output: building_elec_boiler
  sink: energy_supply_constrained
  sink_input: building_elec_boiler
- source: dummy_energy_demands_full
  source_output: building_heatpump
  sink: energy_supply_constrained
  sink_input: building_heatpump
- source: dummy_energy_demands_full
  source_output: building_gas_boiler
  sink: energy_supply_constrained
  sink_input: building_gas_boiler
- source: dummy_energy_demands_full
  source_output: building_hydrogen_boiler
  sink: energy_supply_constrained
  sink_input: building_hydrogen_boiler
- source: dummy_energy_demands_full
  source_output: building_hydrogen_heatpump
  sink: energy_supply_constrained
  sink_input: building_hydrogen_heatpump
- source: dummy_energy_demands_full
  source_output: building_oil_boiler
  sink: energy_supply_constrained
  sink_input: building_oil_boiler
- source: dummy_energy_demands_full
  source_output: dh_biomass_boiler
  sink: energy_supply_constrained
  sink_input: dh_biomass_boiler
- source: dummy_energy_demands_full
  source_output: dh_elec_boiler
  sink: energy_supply_constrained
  sink_input: dh_elec_boiler
- source: dummy_energy_demands_full
  source_output: dh_gas_CHP
  sink: energy_supply_constrained
  sink_input: dh_gas_CHP
- source: dummy_energy_demands_full
  source_output: dh_hydrogen_fuelcell
  sink: energy_supply_constrained
  sink_input: dh_hydrogen_fuelcell
- source: dummy_energy_demands_full
  source_output: elec_trans
  sink: energy_supply_constrained
  sink_input: elec_trans
- source: dummy_energy_demands_full
  source_output: EV_Cap
  sink: energy_supply_constrained
  sink_input: EV_Cap
description: Contains only energy supply wrapper with full data and full energy demand
  scenarios
sector_models:
- energy_supply_constrained
model_dependencies: []
scenarios:
- fuel_price
- dummy_energy_demands_full
