name: energy_demand_constrained
scenarios:
- population
- gva_per_head
- temperature
description: The future demand for energy in the UK
model_dependencies: []
sector_models:
- energy_demand_constrained
scenario_dependencies:
- sink: energy_demand_constrained
  source: population
  source_output: population
  sink_input: population
- sink: energy_demand_constrained
  source: gva_per_head
  source_output: gva_per_head
  sink_input: gva_per_head
- sink: energy_demand_constrained
  source: gva_per_head
  source_output: gva_per_sector
  sink_input: gva_per_sector
- sink: energy_demand_constrained
  source: weather_station_coordinates
  source_output: latitude
  sink_input: latitude
- sink: energy_demand_constrained
  source: weather_station_coordinates
  source_output: longitude
  sink_input: longitude
- sink: energy_demand_constrained
  source: temperature
  source_output: t_min
  sink_input: t_min
- sink: energy_demand_constrained
  source: temperature
  source_output: t_max
  sink_input: t_max
narratives:
- name: air_leakage
  provides:
   energy_demand_constrained:
     - air_leakage
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       air_leakage: ../energy_demand/narratives/air_leakage__central.csv
- name: assump_diff_floorarea_pp
  provides:
   energy_demand_constrained:
     - assump_diff_floorarea_pp
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__central.csv
- name: cooled_floorarea
  provides:
   energy_demand_constrained:
     - cooled_floorarea
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__central.csv
- name: dm_improvement
  provides:
   energy_demand_constrained:
     - dm_improvement
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       dm_improvement: ../energy_demand/narratives/dm_improvement__central.csv
- name: f_eff_achieved
  provides:
   energy_demand_constrained:
     - f_eff_achieved
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__central.csv
- name: generic_enduse_change
  provides:
   energy_demand_constrained:
     - generic_enduse_change
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central.csv
- name: generic_enduse_change
  provides:
   energy_demand_constrained:
     - generic_enduse_change
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central.csv
- name: heat_recovered
  provides:
   energy_demand_constrained:
     - heat_recovered
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       heat_recovered: ../energy_demand/narratives/heat_recovered__central.csv
- name: t_base_heating
  provides:
   energy_demand_constrained:
     - rs_t_base_heating
     - ss_t_base_heating
     - is_t_base_heating
  description: 'Change in heating'
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__central.csv
       ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__central.csv
       is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__central.csv
- name: p_cold_rolling_steel
  provides:
   energy_demand_constrained:
     - p_cold_rolling_steel
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__central.csv
- name: smart_meter_p
  provides:
   energy_demand_constrained:
     - smart_meter_p
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       smart_meter_p: ../energy_demand/narratives/smart_meter_p__central.csv
- name: generic_fuel_switch
  provides:
   energy_demand_constrained:
     - generic_fuel_switch
  description: ''
  variants:
   - name: central_narrative
     description: Central assumptions
     data:
       generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__central.csv
  