name: energy_demand_unconstrained
description: The future demand for energy in the UK
sector_models:
- energy_demand_unconstrained
scenarios:
- socio-economic
- temperature
narratives:
  - name: f_eff_achieved
    description: ''
    provides:
      energy_demand_constrained:
      - f_eff_achieved
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__central
      - name: electric_world
        description: Central assumptions
        data:
          f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__electric_world
      - name: multivector_world
        description: Central assumptions
        data:
          f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__multivector_world
  - name: generic_enduse_change
    description: ''
    provides:
      energy_demand_constrained:
      - generic_enduse_change
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central
      - name: electric_world
        description: Electirc world assumptions
        data:
          generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__electric_world
      - name: multivector_world
        description: Multivector assumptions
        data:
          generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__multivector_world
  - name: generic_fuel_switch
    description: ''
    provides:
      energy_demand_constrained:
        - generic_fuel_switch
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__central
      - name: multivector_world
        description: Multivector assumptions
        data:
          generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__multivector_world
      - name: electric_world
        description: Electirc world assumptions
        data:
          generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__electric_world
  - name: heat_recovered
    description: ''
    provides:
      energy_demand_constrained:
      - heat_recovered
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          heat_recovered: ../energy_demand/narratives/heat_recovered__central
      - name: electric_world
        description: Central assumptions
        data:
          heat_recovered: ../energy_demand/narratives/heat_recovered__electric_world
      - name: multivector_world
        description: Central assumptions
        data:
          heat_recovered: ../energy_demand/narratives/heat_recovered__multivector_world
  - name: smart_meter_p
    description: ''
    provides:
      energy_demand_constrained:
        - smart_meter_p
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          smart_meter_p: ../energy_demand/narratives/smart_meter_p__central
      - name: multivector_world
        description: Central assumptions
        data:
          smart_meter_p: ../energy_demand/narratives/smart_meter_p__multivector_world
      - name: electric_world
        description: Central assumptions
        data:
          smart_meter_p: ../energy_demand/narratives/smart_meter_p__electric_world
  - name: switches_service
    description: ''
    provides:
      energy_demand_constrained:
        - switches_service
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          switches_service: ../energy_demand/narratives/switches_service__central
      - name: electric_world
        description: Electric world assumptions
        data:
          switches_service: ../energy_demand/narratives/switches_service__electric_world
      - name: multivector_world
        description: Multivector assumptions
        data:
          switches_service: ../energy_demand/narratives/switches_service__multivector_world
  - name: t_base_heating
    description: Change in heating
    provides:
      energy_demand_constrained:
        - rs_t_base_heating
        - ss_t_base_heating
        - is_t_base_heating
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__central
          ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__central
          rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__central
      - name: electric_world
        description: Electric world assumptions
        data:
          is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__electric_world
          ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__electric_world
          rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__electric_world
      - name: multivector_world
        description: Central assumptions
        data:
          is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__multivector_world
          ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__multivector_world
          rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__multivector_world
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_unconstrained
  sink_input: floor_area
  source: socio-economic
  source_output: floor_area
- sink: energy_demand_unconstrained
  sink_input: population
  source: socio-economic
  source_output: population
- sink: energy_demand_unconstrained
  sink_input: gva_per_head
  source: socio-economic
  source_output: gva_per_head
- sink: energy_demand_unconstrained
  sink_input: gva_per_sector
  source: socio-economic
  source_output: gva_per_sector
- sink: energy_demand_unconstrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_unconstrained
  sink_input: t_max
  source: temperature
  source_output: t_max
