scenarios:
- es_prices
- dummy_energy_demands_minimal
description: Links the toy version of the energy supply model to dummy scenarios
name: energy_supply_toy
narratives:
- variants:
  - data:
      LoadShed_elec: high_load_shed.csv
      LoadShed_gas: high_load_shed.csv
    description: very high cost load shedding
    name: high_cost
  sos_model: ''
  description: Costs of shedding load
  name: load_shedding
  provides:
    energy_supply_toy:
    - LoadShed_elec
    - LoadShed_gas
scenario_dependencies:
- source_output: gas_price
  sink_input: gas_price
  sink: energy_supply_toy
  source: es_prices
- source_output: electricity_price
  sink_input: electricity_price
  sink: energy_supply_toy
  source: es_prices
- source_output: oil_price
  sink_input: oil_price
  sink: energy_supply_toy
  source: es_prices
- source_output: coal_price
  sink_input: coal_price
  sink: energy_supply_toy
  source: es_prices
- source_output: nuclearFuel_price
  sink_input: nuclearFuel_price
  sink: energy_supply_toy
  source: es_prices
- source_output: cost_of_carbon
  sink_input: cost_of_carbon
  sink: energy_supply_toy
  source: es_prices
- source_output: residential_gas_non_heating
  sink_input: residential_gas_non_heating
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: residential_electricity_non_heating
  sink_input: residential_electricity_non_heating
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: service_gas_non_heating
  sink_input: service_gas_non_heating
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: service_electricity_non_heating
  sink_input: service_electricity_non_heating
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: elecload
  sink_input: elecload
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: gasload
  sink_input: gasload
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: service_heatload
  sink_input: service_heatload
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
- source_output: residential_heatload
  sink_input: residential_heatload
  sink: energy_supply_toy
  source: dummy_energy_demands_minimal
model_dependencies: []
sector_models:
- energy_supply_toy
