name: energy_demand_constrained
description: The future demand for energy in the UK
sector_models:
- energy_demand_constrained
scenarios:
- socio-economic
- temperature
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_constrained
  sink_input: floor_area
  source: socio-economic
  source_output: floor_area
- sink: energy_demand_constrained
  sink_input: population
  source: socio-economic
  source_output: population
- sink: energy_demand_constrained
  sink_input: gva_per_head
  source: socio-economic
  source_output: gva_per_head
- sink: energy_demand_constrained
  sink_input: gva_per_sector
  source: socio-economic
  source_output: gva_per_sector
- sink: energy_demand_constrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_constrained
  sink_input: t_max
  source: temperature
  source_output: t_max
narratives:
  - name: virtual_dw_stock
    description: Virtual dwelling stock mode
    provides:
      energy_demand_constrained:
        - virtual_dw_stock
    variants:
      - name: load_in_directly
        description: Loads in floor area directly
        data:
          virtual_dw_stock: ../../data/energy_demand/narratives/virtual_dw_stock_false
      - name: virtual_stock
        description: Creates virtual stock
        data:
          virtual_dw_stock: ../../data/energy_demand/narratives/virtual_stock_true
  - name: air_leakage
    description: ''
    provides:
      energy_demand_constrained:
        - air_leakage
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          air_leakage: ../energy_demand/narratives/air_leakage__central
  - name: assump_diff_floorarea_pp
    description: ''
    provides:
      energy_demand_constrained:
        - assump_diff_floorarea_pp
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__central
  - name: cooled_floorarea
    description: ''
    provides:
      energy_demand_constrained:
        - cooled_floorarea
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__central
  - name: dm_improvement
    description: ''
    provides:
      energy_demand_constrained:
        - dm_improvement
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          dm_improvement: ../energy_demand/narratives/dm_improvement__central
  - name: f_eff_achieved
    description: ''
    provides:
      energy_demand_constrained:
        - f_eff_achieved
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__central
      - name: electric_world
        description: Central assumptions
        data:
          f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__electric_world
      - name: multivector_world
        description: Central assumptions
        data:
          f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__multivector_world
  - name: generic_enduse_change
    description: ''
    provides:
      energy_demand_constrained:
        - generic_enduse_change
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central
      - name: electric_world
        description: Electirc world assumptions
        data:
          generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__electric_world
      - name: multivector_world
        description: Multivector assumptions
        data:
          generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__multivector_world
  - name: heat_recovered
    description: ''
    provides:
      energy_demand_constrained:
        - heat_recovered
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          heat_recovered: ../energy_demand/narratives/heat_recovered__central
      - name: electric_world
        description: Central assumptions
        data:
          heat_recovered: ../energy_demand/narratives/heat_recovered__electric_world
      - name: multivector_world
        description: Central assumptions
        data:
          heat_recovered: ../energy_demand/narratives/heat_recovered__multivector_world
  - name: t_base_heating
    description: Change in heating
    provides:
      energy_demand_constrained:
        - rs_t_base_heating
        - ss_t_base_heating
        - is_t_base_heating
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__central
          ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__central
          rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__central
      - name: electric_world
        description: Electric world assumptions
        data:
          is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__electric_world
          ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__electric_world
          rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__electric_world
      - name: multivector_world
        description: Central assumptions
        data:
          is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__multivector_world
          ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__multivector_world
          rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__multivector_world
  - name: p_cold_rolling_steel
    description: ''
    provides:
      energy_demand_constrained:
        - p_cold_rolling_steel
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__central
  - name: smart_meter_p
    description: ''
    provides:
      energy_demand_constrained:
        - smart_meter_p
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          smart_meter_p: ../energy_demand/narratives/smart_meter_p__central
      - name: multivector_world
        description: Central assumptions
        data:
          smart_meter_p: ../energy_demand/narratives/smart_meter_p__multivector_world
      - name: electric_world
        description: Central assumptions
        data:
          smart_meter_p: ../energy_demand/narratives/smart_meter_p__electric_world
  - name: generic_fuel_switch
    description: ''
    provides:
      energy_demand_constrained:
        - generic_fuel_switch
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__central
      - name: multivector_world
        description: Multivector assumptions
        data:
          generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__multivector_world
      - name: electric_world
        description: Electirc world assumptions
        data:
          generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__electric_world
  - name: switches_service
    description: ''
    provides:
      energy_demand_constrained:
        - switches_service
    variants:
      - name: central_narrative
        description: Central assumptions
        data:
          switches_service: ../energy_demand/narratives/switches_service__central
      - name: electric_world
        description: Electric world assumptions
        data:
          switches_service: ../energy_demand/narratives/switches_service__electric_world
      - name: multivector_world
        description: Multivector assumptions
        data:
          switches_service: ../energy_demand/narratives/switches_service__multivector_world
