name: energy_demand_constrained
scenarios:     # Select 0 or more of the scenario sets
- population
- gva_per_head
- temperature
description: The future demand for energy in the UK
model_dependencies: []
sector_models:
- energy_demand_constrained
scenario_dependencies:
- sink: energy_demand_constrained
  source: population
  source_output: population
  sink_input: population
- sink: energy_demand_constrained
  source: gva_per_head
  source_output: gva_per_head
  sink_input: gva_per_head
- sink: energy_demand_constrained
  source: gva_per_head
  source_output: gva_per_sector
  sink_input: gva_per_sector
- sink: energy_demand_constrained
  source: temperature
  source_output: t_min
  sink_input: t_min
- sink: energy_demand_constrained
  source: temperature
  source_output: t_max
  sink_input: t_max
narratives:
- name: end_use_change
  provides:
    energy_demand_constrained:
    - generic_enduse_change_end_yr
    - generic_enduse_change_value
  description: ' Change in end use'
  sos_model: ''
  variants:
  - name: central_narrative
    description: Central assumptions
    data:
      generic_enduse_change_end_yr: ed_central_assumptions.csv
      generic_enduse_change_value: ed_central_assumptions.csv
