name: energy_supply_only
narratives:
- variants:
  - data:
      LoadShed_elec: ../../data/energy_supply/narratives/high_load_shed.csv
      LoadShed_gas: ../../data/energy_supply/narratives/high_load_shed.csv
    description: very high cost load shedding
    name: high_cost
  sos_model: energy_supply_only
  description: Costs of shedding load
  name: load_shedding
  provides:
    energy_supply_toy:
    - LoadShed_elec
    - LoadShed_gas
scenario_dependencies:
- sink: energy_supply
  source_output: energy_supply_price
  source: fuel_price
  sink_input: fuel_price
- sink: energy_supply
  source_output: residential_gas_non_heating
  source: dummy_energy_demands_full
  sink_input: residential_gas_non_heating
- sink: energy_supply
  source_output: residential_electricity_non_heating
  source: dummy_energy_demands_full
  sink_input: residential_electricity_non_heating
- sink: energy_supply
  source_output: service_gas_non_heating
  source: dummy_energy_demands_full
  sink_input: service_gas_non_heating
- sink: energy_supply
  source_output: service_electricity_non_heating
  source: dummy_energy_demands_full
  sink_input: service_electricity_non_heating
- sink: energy_supply
  source_output: elecload
  source: dummy_energy_demands_full
  sink_input: elecload
- sink: energy_supply
  source_output: gasload
  source: dummy_energy_demands_full
  sink_input: gasload
- sink: energy_supply
  source_output: service_heatload
  source: dummy_energy_demands_full
  sink_input: service_heatload
- sink: energy_supply
  source_output: residential_heatload
  source: dummy_energy_demands_full
  sink_input: residential_heatload
description: Contains only energy supply wrapper with full data and full energy demand
  scenarios
sector_models:
- energy_supply
model_dependencies: []
scenarios:
- fuel_price
- dummy_energy_demands_full
