name: energy_demand_only
description: The future demand for energy in the UK
sector_models: # Select 1 or more of the sector models
- energy_demand_constrained
convergence_relative_tolerance: 1e-05
scenarios:     # Select 0 or more of the scenario sets
- population
- gva
narratives: []
scenario_dependencies:
- source: population
  source_output: population
  sink: energy_demand_constrained
  sink_input: population
- source: gva
  source_output: gva
  sink: energy_demand_constrained
  sink_input: gva
model_dependencies: []
