name: energy_demand_constrained
sector_models:
- energy_demand_constrained
narratives:
- description: ''
  provides:
    energy_demand_constrained:
    - air_leakage
  name: air_leakage
  variants:
  - data:
      air_leakage: ../energy_demand/narratives/air_leakage__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - assump_diff_floorarea_pp
  name: assump_diff_floorarea_pp
  variants:
  - data:
      assump_diff_floorarea_pp: ../energy_demand/narratives/assump_diff_floorarea_pp__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - cooled_floorarea
  name: cooled_floorarea
  variants:
  - data:
      cooled_floorarea: ../energy_demand/narratives/cooled_floorarea__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - dm_improvement
  name: dm_improvement
  variants:
  - data:
      dm_improvement: ../energy_demand/narratives/dm_improvement__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - f_eff_achieved
  name: f_eff_achieved
  variants:
  - data:
      f_eff_achieved: ../energy_demand/narratives/f_eff_achieved__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - generic_enduse_change
  name: generic_enduse_change
  variants:
  - data:
      generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - generic_enduse_change
  name: generic_enduse_change
  variants:
  - data:
      generic_enduse_change: ../energy_demand/narratives/generic_enduse_change__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - heat_recovered
  name: heat_recovered
  variants:
  - data:
      heat_recovered: ../energy_demand/narratives/heat_recovered__central.csv
    description: Central assumptions
    name: central_narrative
- description: Change in heating
  provides:
    energy_demand_constrained:
    - rs_t_base_heating
    - ss_t_base_heating
    - is_t_base_heating
  name: t_base_heating
  variants:
  - data:
      is_t_base_heating: ../energy_demand/narratives/is_t_base_heating__central.csv
      ss_t_base_heating: ../energy_demand/narratives/ss_t_base_heating__central.csv
      rs_t_base_heating: ../energy_demand/narratives/rs_t_base_heating__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - p_cold_rolling_steel
  name: p_cold_rolling_steel
  variants:
  - data:
      p_cold_rolling_steel: ../energy_demand/narratives/p_cold_rolling_steel__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - smart_meter_p
  name: smart_meter_p
  variants:
  - data:
      smart_meter_p: ../energy_demand/narratives/smart_meter_p__central.csv
    description: Central assumptions
    name: central_narrative
- description: ''
  provides:
    energy_demand_constrained:
    - generic_fuel_switch
  name: generic_fuel_switch
  variants:
  - data:
      generic_fuel_switch: ../energy_demand/narratives/generic_fuel_switch__central.csv
    description: Central assumptions
    name: central_narrative
description: The future demand for energy in the UK
model_dependencies: []
scenario_dependencies:
- sink: energy_demand_constrained
  sink_input: population
  source: population
  source_output: population
- sink: energy_demand_constrained
  sink_input: gva_per_head
  source: gva_per_head
  source_output: gva_per_head
- sink: energy_demand_constrained
  sink_input: gva_per_sector
  source: gva_per_head
  source_output: gva_per_sector
- sink: energy_demand_constrained
  sink_input: latitude
  source: weather_station_coordinates
  source_output: latitude
- sink: energy_demand_constrained
  sink_input: longitude
  source: weather_station_coordinates
  source_output: longitude
- sink: energy_demand_constrained
  sink_input: t_min
  source: temperature
  source_output: t_min
- sink: energy_demand_constrained
  sink_input: t_max
  source: temperature
  source_output: t_max
scenarios:
- gva_per_head
- temperature
- population
- weather_station_coordinates
