model_dependencies:
- source: energy_demand_constrained
  sink_input: residential_gas_boiler_gas
  source_output: residential_gas_boiler_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_electricity_boiler_electricity
  source_output: residential_electricity_boiler_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_electricity_heat_pumps_electricity
  source_output: residential_electricity_heat_pumps_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_gas_district_heating_CHP_gas
  source_output: residential_gas_district_heating_CHP_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_electricity_district_heating_electricity
  source_output: residential_electricity_district_heating_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_gas_stirling_micro_gas
  source_output: residential_gas_stirling_micro_CHP_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_gas_boiler_gas
  source_output: service_gas_boiler_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_electricity_boiler_electricity
  source_output: service_electricity_boiler_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_electricity_heat_pumps_electricity
  source_output: service_electricity_heat_pumps_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_gas_district_heating_gas
  source_output: service_gas_district_heating_CHP_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_electricity_district_heating_electricity
  source_output: service_electricity_district_heating_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_gas_stirling_micro_gas
  source_output: service_gas_stirling_micro_CHP_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_gas_boiler_gas
  source_output: industry_gas_boiler_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_electricity_boiler_electricity
  source_output: industry_electricity_boiler_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_biomass_boiler_biomass
  source_output: industry_biomass_boiler_biomass
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_electricity_heat_pumps_electricity
  source_output: industry_electricity_heat_pumps_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_gas_district_heating_CHP_gas
  source_output: industry_gas_district_heating_CHP_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_electricity_district_heating_electricity
  source_output: industry_electricity_district_heating_electricity
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_biomass_district_heating_biomass
  source_output: industry_biomass_district_heating_biomass
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_gas_stirling_micro_CHP_gas
  source_output: industry_gas_stirling_micro_CHP_gas
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_gas_non_heating
  source_output: residential_gas_non_heating
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: residential_electricity_non_heating
  source_output: residential_electricity_non_heating
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_gas_non_heating
  source_output: service_gas_non_heating
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: service_electricity_non_heating
  source_output: service_electricity_non_heating
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_gas_non_heating
  source_output: industry_gas_non_heating
  sink: convert_ed_to_es
- source: energy_demand_constrained
  sink_input: industry_electricity_non_heating
  source_output: industry_electricity_non_heating
  sink: convert_ed_to_es
- source: convert_ed_to_es
  sink_input: industry_electricity_non_heating
  source_output: industry_electricity_non_heating
  sink: aggregate_elecload
- source: convert_ed_to_es
  sink_input: industry_electricity_boiler_electricity
  source_output: industry_electricity_boiler_electricity
  sink: aggregate_elecload
- source: convert_ed_to_es
  sink_input: industry_electricity_heat_pumps_electricity
  source_output: industry_electricity_heat_pumps_electricity
  sink: aggregate_elecload
- source: convert_ed_to_es
  sink_input: industry_electricity_district_heating_electricity
  source_output: industry_electricity_district_heating_electricity
  sink: aggregate_elecload
- source: convert_ed_to_es
  sink_input: residential_gas_boiler_gas
  source_output: residential_gas_boiler_gas
  sink: aggregate_residential_heatload
- source: convert_ed_to_es
  sink_input: residential_electricity_boiler_electricity
  source_output: residential_electricity_boiler_electricity
  sink: aggregate_residential_heatload
- source: convert_ed_to_es
  sink_input: residential_electricity_heat_pumps_electricity
  source_output: residential_electricity_heat_pumps_electricity
  sink: aggregate_residential_heatload
- source: convert_ed_to_es
  sink_input: residential_gas_district_heating_CHP_gas
  source_output: residential_gas_district_heating_CHP_gas
  sink: aggregate_residential_heatload
- source: convert_ed_to_es
  sink_input: residential_electricity_district_heating_electricity
  source_output: residential_electricity_district_heating_electricity
  sink: aggregate_residential_heatload
- source: convert_ed_to_es
  sink_input: residential_gas_stirling_micro_gas
  source_output: residential_gas_stirling_micro_gas
  sink: aggregate_residential_heatload
- source: convert_ed_to_es
  sink_input: service_gas_boiler_gas
  source_output: service_gas_boiler_gas
  sink: aggregate_service_heatload
- source: convert_ed_to_es
  sink_input: service_electricity_boiler_electricity
  source_output: service_electricity_boiler_electricity
  sink: aggregate_service_heatload
- source: convert_ed_to_es
  sink_input: service_electricity_heat_pumps_electricity
  source_output: service_electricity_heat_pumps_electricity
  sink: aggregate_service_heatload
- source: convert_ed_to_es
  sink_input: service_gas_district_heating_gas
  source_output: service_gas_district_heating_gas
  sink: aggregate_service_heatload
- source: convert_ed_to_es
  sink_input: service_electricity_district_heating_electricity
  source_output: service_electricity_district_heating_electricity
  sink: aggregate_service_heatload
- source: convert_ed_to_es
  sink_input: service_gas_stirling_micro_gas
  source_output: service_gas_stirling_micro_gas
  sink: aggregate_service_heatload
- source: convert_ed_to_es
  sink_input: residential_gas_non_heating
  source_output: residential_gas_non_heating
  sink: energy_supply
- source: convert_ed_to_es
  sink_input: residential_electricity_non_heating
  source_output: residential_electricity_non_heating
  sink: energy_supply
- source: convert_ed_to_es
  sink_input: service_gas_non_heating
  source_output: service_gas_non_heating
  sink: energy_supply
- source: convert_ed_to_es
  sink_input: service_electricity_non_heating
  source_output: service_electricity_non_heating
  sink: energy_supply
- source: convert_ed_to_es
  sink_input: industry_gas_boiler_gas
  source_output: industry_gas_boiler_gas
  sink: aggregate_gasload
- source: convert_ed_to_es
  sink_input: industry_biomass_boiler_biomass
  source_output: industry_biomass_boiler_biomass
  sink: aggregate_gasload
- source: convert_ed_to_es
  sink_input: industry_gas_district_heating_CHP_gas
  source_output: industry_gas_district_heating_CHP_gas
  sink: aggregate_gasload
- source: convert_ed_to_es
  sink_input: industry_biomass_district_heating_biomass
  source_output: industry_biomass_district_heating_biomass
  sink: aggregate_gasload
- source: convert_ed_to_es
  sink_input: industry_gas_stirling_micro_CHP_gas
  source_output: industry_gas_stirling_micro_CHP_gas
  sink: aggregate_gasload
- source: convert_ed_to_es
  sink_input: industry_gas_non_heating
  source_output: industry_gas_non_heating
  sink: aggregate_gasload
- source: aggregate_elecload
  sink_input: elecload
  source_output: elecload
  sink: energy_supply
- source: aggregate_gasload
  sink_input: gasload
  source_output: gasload
  sink: remap_gas
- source: remap_gas
  sink_input: gasload
  source_output: gasload
  sink: energy_supply
- source: aggregate_service_heatload
  sink_input: service_heatload
  source_output: service_heatload
  sink: energy_supply
- source: aggregate_residential_heatload
  sink_input: residential_heatload
  source_output: residential_heatload
  sink: energy_supply
scenario_dependencies:
- source: population
  sink_input: population
  source_output: population
  sink: energy_demand_constrained
- source: gva
  sink_input: gva_per_head
  source_output: gva_per_head
  sink: energy_demand_constrained
- source: es_prices
  sink_input: gas_price
  source_output: gas_price
  sink: energy_supply
- source: es_prices
  sink_input: electricity_price
  source_output: electricity_price
  sink: energy_supply
- source: es_prices
  sink_input: oil_price
  source_output: oil_price
  sink: energy_supply
- source: es_prices
  sink_input: coal_price
  source_output: coal_price
  sink: energy_supply
- source: es_prices
  sink_input: nuclearFuel_price
  source_output: nuclearFuel_price
  sink: energy_supply
- source: es_prices
  sink_input: cost_of_carbon
  source_output: cost_of_carbon
  sink: energy_supply
- source: gva
  sink_input: gva_per_sector
  source_output: gva_per_sector
  sink: energy_demand_constrained
scenarios:
- population
- es_prices
- gva
description: A full version of the energy demand - energy supply system-of-systems
  model
sector_models:
- energy_supply
- energy_demand_constrained
- convert_ed_to_es
- aggregate_elecload
- aggregate_gasload
- remap_gas
- aggregate_residential_heatload
- aggregate_service_heatload
name: energy_supply_demand
narratives:
- variants:
  - data:
      LoadShed_elec: ../../data/energy_supply/narratives/high_load_shed.csv
      LoadShed_gas: ../../data/energy_supply/narratives/high_load_shed.csv
    description: very high cost load shedding
    name: high_cost
  sos_model: energy_supply_toy
  description: Costs of shedding load
  name: load_shedding
  provides:
    energy_supply_toy:
    - LoadShed_elec
    - LoadShed_gas
