name: energy_supply_optimised
description: Contains only energy supply wrapper with full data and full energy demand
  scenarios
sector_models:
- energy_supply_optimised
model_dependencies: []
scenarios:
- fuel_price
- dummy_energy_demands_full
- dummy_weather_inputs_full
- biomass_waste_to_energy
- elec_interconnector_prices
narratives:
  - name: load_shedding
    description: Costs of shedding load
    provides:
      energy_supply_optimised:
      - LoadShed_elec
      - LoadShed_gas
    variants:
      - name: high_cost
        description: very high cost load shedding
        data:
          LoadShed_elec: ../../data/energy_supply/narratives/high_load_shed.csv
          LoadShed_gas: ../../data/energy_supply/narratives/high_load_shed.csv
  - name: operation_mode
    description: operation mode for energy supply system
    provides:
      energy_supply_optimised:
      - operation_mode
    variants:
      - name: decentral
        decription: decentralised operating mode
        data:
          operation_mode: ../../data/energy_supply/parameters/op_mode_decentral.csv
      - name: central
        decription: centralised operating mode
        data:
          operation_mode: ../../data/energy_supply/parameters/op_mode_central.csv
  - name: heat_supply_strategy
    description: heat supply strategy for operation
    provides:
      energy_supply_optimised:
      - heat_supply_strategy
    variants:
      - name: full_electric
        decription: full electric heating
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_fullelectric.csv
      - name: heat_networks
        decription: heat network domination for heating
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_heatnetworks.csv
      - name: green_gas
        decription: green gas mixture for heat supply
        data:
          heat_supply_strategy: ../../data/energy_supply/parameters/hs_greengas.csv
scenario_dependencies:
- source: fuel_price
  source_output: energy_supply_price
  sink: energy_supply_optimised
  sink_input: fuel_price
- source: dummy_energy_demands_full
  source_output: elecload
  sink: energy_supply_optimised
  sink_input: elecload
- source: dummy_energy_demands_full
  source_output: gasload
  sink: energy_supply_optimised
  sink_input: gasload
- source: dummy_energy_demands_full
  source_output: residential_gas_non_heating
  sink: energy_supply_optimised
  sink_input: gasload_non_heat_res
- source: dummy_energy_demands_full
  source_output: residential_electricity_non_heating
  sink: energy_supply_optimised
  sink_input: elecload_non_heat_res
- source: dummy_energy_demands_full
  source_output: service_gas_non_heating
  sink: energy_supply_optimised
  sink_input: gasload_non_heat_com
- source: dummy_energy_demands_full
  source_output: service_electricity_non_heating
  sink: energy_supply_optimised
  sink_input: elecload_non_heat_com
- source: dummy_energy_demands_full
  source_output: hydrogen_non_heating
  sink: energy_supply_optimised
  sink_input: hydrogen_non_heat_eh
- source: dummy_energy_demands_full
  source_output: residential_heatload
  sink: energy_supply_optimised
  sink_input: heatload_res
- source: dummy_energy_demands_full
  source_output: service_heatload
  sink: energy_supply_optimised
  sink_input: heatload_com
- source: dummy_weather_inputs_full
  source_output: wind_speed_eh
  sink: energy_supply_optimised
  sink_input: wind_speed_eh
- source: dummy_weather_inputs_full
  source_output: wind_speed_bus
  sink: energy_supply_optimised
  sink_input: wind_speed_bus
- source: dummy_weather_inputs_full
  source_output: insolation_eh
  sink: energy_supply_optimised
  sink_input: insolation_eh
- source: dummy_weather_inputs_full
  source_output: insolation_bus
  sink: energy_supply_optimised
  sink_input: insolation_bus
- source: dummy_energy_demands_full
  source_output: elec_trans
  sink: energy_supply_optimised
  sink_input: elec_trans
- source: dummy_energy_demands_full
  source_output: EV_Cap
  sink: energy_supply_optimised
  sink_input: EV_Cap
- source: biomass_waste_to_energy
  source_output: biomass_feedstock
  sink: energy_supply_optimised
  sink_input: biomass_feedstock
- source: biomass_waste_to_energy
  source_output: municipal_waste
  sink: energy_supply_optimised
  sink_input: municipal_waste
- source: elec_interconnector_prices
  source_output: elec_int
  sink: energy_supply_optimised
  sink_input: elec_int 
