name: et_module_only
description: 'Disaggregation of energy demand from transport sector to hourly'
scenario_sets: # Select 0 or more of the scenario sets
- transport_energy_demand
- population
- gva
narrative_sets: []
sector_models: # Select 1 or more of the sector models
- et_module
- energy_demand_constrained
- energy_supply
dependencies:
- source_model: population
  source_model_output: population
  sink_model: energy_demand_constrained
  sink_model_input: population
- source_model: gva
  source_model_output: gva
  sink_model: energy_demand_constrained
  sink_model_input: gva
- source_model: transport_energy_demand
  source_model_output: electricity
  sink_model: et_module
  sink_model_input: electricity
- source_model: et_module
  output: electricity
  sink_model: energy_supply
  input: electricity
- source_model: energy_demand_constrained
  output: electricity
  sink_model: energy_supply
  input: electricity
max_iterations: 100
convergence_absolute_tolerance: 1e-05
convergence_relative_tolerance: 1e-05
