name: et_module_only
description: Disaggregation of energy demand from transport sector to hourly
sector_models: # Select 1 or more of the sector models
- et_module
- energy_demand_constrained
- energy_supply
scenarios:     # Select 0 or more of the scenario sets
- transport_energy_demand
- population
- gva
narratives: []
scenario_dependencies:
- source: population
  source_output: population
  sink: energy_demand_constrained
  sink_input: population
- source: gva
  source_output: gva
  sink: energy_demand_constrained
  sink_input: gva
- source: transport_energy_demand
  source_output: electricity
  sink: et_module
  sink_input: electricity
model_dependencies:
- output: electricity
  input: electricity
  source: et_module
  sink: energy_supply
- output: electricity
  input: electricity
  source: energy_demand_constrained
  sink: energy_supply
