name: et_module
description: Energy demand assignement to hourly from hourly transportation demand
sector_models:
  - et_module
scenarios:
  - ev_transport_trips
model_dependencies: []
scenario_dependencies:
  - source: ev_transport_trips
    source_output: ev_trip_start
    sink: et_module
    sink_input: ev_trips
  - source: ev_transport_trips
    source_output: ev_trip_elec
    sink: et_module
    sink_input: ev_electricity
narratives:
  - name: default
    description: default narrative
    sos_model: et_module
    provides:
      et_module:
        - load_profile_charging_regime
        - yr_until_changed_lp
    variants:
      - name: managed
        description: EV charging is fully managed by the system operator
        data:
          load_profile_charging_regime: ../et_module/parameters/ev_scheduling_managed.csv
          yr_until_changed_lp: ../et_module/parameters/ev_scheduling_managed.csv
