description: Energy demand assignement to hourly from hourly transportation demand
model_dependencies: []
name: et_module
narratives:
- name: default
  description: default narrative
  sos_model: et_module
  provides:
    et_module:
    - load_profile_charging_regime
    - yr_until_changed_lp
  variants:
  - name: managed
    description: EV charging is fully managed by the system operator
    data:
      load_profile_charging_regime: ../et_module/parameters/ev_scheduling_managed.csv
      yr_until_changed_lp: ../et_module/parameters/ev_scheduling_managed.csv
scenario_dependencies:
- sink: et_module
  sink_input: ev_trips
  source: ev_transport_trips
  source_output: ev_trip_start
  timestep: CURRENT
- sink: et_module
  sink_input: ev_electricity
  source: ev_transport_trips
  source_output: ev_trip_elec
  timestep: CURRENT
scenarios:
- ev_transport_trips
sector_models:
- et_module
