name: et_module
description: Energy demand assignement to hourly from hourly transportation demand
sector_models: # Select 1 or more of the sector models
- et_module
convergence_relative_tolerance: 1e-05
scenarios:     # Select 0 or more of the scenario sets
- transport_energy_demand
scenario_dependencies:
- source: transport_energy_demand
  source_output: electricity
  sink: et_module
  sink_input: electricity
model_dependencies: []
