name: et_module
description: 'Energy demand assignement to hourly from hourly transportation demand'
scenario_sets: # Select 0 or more of the scenario sets
- transport_energy_demand
sector_models: # Select 1 or more of the sector models
- et_module
dependencies: 
- source_model: transport_energy_demand
  source_model_output: electricity
  sink_model: et_module
  sink_model_input: electricity
max_iterations: 100
convergence_absolute_tolerance: 1e-05
convergence_relative_tolerance: 1e-05
