name: rail_southampton
description: Test model for transport
sector_models:
  - rail_southampton
  - extract_southampton_scenarios
scenarios:
  - socio-economic
  - station_usage
  - rail_journey_times_fares
narratives: []
scenario_dependencies:
  - source: socio-economic
    source_output: population
    sink: extract_southampton_scenarios
    sink_input: population
  - source: socio-economic
    source_output: gva_per_head
    sink: extract_southampton_scenarios
    sink_input: gva
  - source: station_usage
    source_output: day_usage
    sink: rail_southampton
    sink_input: day_usage
  - source: station_usage
    source_output: year_usage
    sink: rail_southampton
    sink_input: year_usage
  - source: rail_journey_times_fares
    source_output: rail_journey_fares
    sink: rail_southampton
    sink_input: rail_journey_fares
  - source: rail_journey_times_fares
    source_output: rail_journey_times
    sink: rail_southampton
    sink_input: rail_journey_times
  - source: car_zonal_journey_costs
    source_output: car_zonal_journey_costs
    sink: rail_southampton
    sink_input: car_zonal_journey_costs
model_dependencies:
  - source: extract_southampton_scenarios
    source_output: population
    sink: rail_southampton
    sink_input: population
  - source: extract_southampton_scenarios
    source_output: gva
    sink: rail_southampton
    sink_input: gva
