description: Just tests the conversion from energy_demand_toy to energy_supply_toy
name: test_conversion_only
sector_models:
- convert_ed_to_es
scenarios:
- es_residential
narratives: []
scenario_dependencies:
- source: es_residential
  source_output: residential_gas_boiler_gas
  sink: convert_ed_to_es
  sink_input: residential_gas_boiler_gas
- source: es_residential
  source_output: residential_electricity_boiler_electricity
  sink: convert_ed_to_es
  sink_input: residential_electricity_boiler_electricity
model_dependencies: []
