name: transport_full
description: Test model for transport
sector_models:
  - transport
  - extract_gb_scenarios
scenarios:
  - population
  - gva
  - fuel_price
  - link_travel_time
narratives: []
scenario_dependencies:
  - source: population
    source_output: population
    sink: extract_gb_scenarios
    sink_input: population
  - source: gva
    source_output: gva_per_head
    sink: extract_gb_scenarios
    sink_input: gva
  - source: fuel_price
    source_output: fuel_price
    sink: transport
    sink_input: fuel_price
  - source: fuel_price
    source_output: fuel_price_electricity
    sink: transport
    sink_input: fuel_price_electricity
  - source: link_travel_time
    source_output: link_travel_time
    sink: transport
    sink_input: link_travel_time
model_dependencies:
  - source: extract_gb_scenarios
    source_output: population
    sink: transport
    sink_input: population
  - source: extract_gb_scenarios
    source_output: gva
    sink: transport
    sink_input: gva
  - source: transport
    source_output: link_travel_time
    sink: transport
    sink_input: link_travel_time
    timestep: PREVIOUS  # dependency on own outputs from previous timestep
