name: transport_only
description: Test model for transport
sector_models:
  - transport
# Scenario data
scenario_sets:
  - passenger_vehicle_OD
dependencies:
  - source_model: passenger_vehicle_OD
    source_model_output: flow
    sink_model: transport
    sink_model_input: base_year_passenger_vehicle_OD_matrix
# Narratives
narrative_sets: []
# Iteration settings
convergence_absolute_tolerance: 1.0e-05
convergence_relative_tolerance: 1.0e-05
max_iterations: 1
