name: transport_only
description: Test model for transport
sector_models:
- transport
# Scenario data
convergence_relative_tolerance: 1.0e-05
scenarios:
- population
- gva
narratives: []
scenario_dependencies:
- source: population
  source_output: population
  sink: transport
  sink_input: population
- source: gva
  source_output: gva
  sink: transport
  sink_input: gva
model_dependencies: []
