name: water_demand
description: Future water demand for UK, from LAD population projections
sector_models:
  - water_demand
  - convert_population_lad_to_wrz
scenarios:
  - socio-economic
  - water_demand_projections
narratives: []
scenario_dependencies:
  - source: socio-economic
    source_output: population
    sink: convert_population_lad_to_wrz
    sink_input: population
  - source: water_demand_projections
    source_output: constant_water_demand
    sink: water_demand
    sink_input: constant_water_demand
  - source: water_demand_projections
    source_output: per_capita_water_demand
    sink: water_demand
    sink_input: per_capita_water_demand
model_dependencies:
  - source: convert_population_lad_to_wrz
    source_output: population
    sink: water_demand
    sink_input: population
