decision_module: ''
description: ''
name: energy_supply_toy
narratives:
  technology:
  - test_narrative
scenarios:
  es_prices: es_prices_dummy
  es_residential: es_residential_dummy
sos_model: energy_supply_toy
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
- 2020
