description: ''
name: energy_supply_test
narratives: {}
scenarios:
  es_prices: es_prices_dummy
  dummy_energy_demands: es_energy_demand_dummy
sos_model: energy_supply_only
stamp: '2018-01-31T10:10:41.791Z'
timesteps:
- 2015
- 2020
strategies:
- strategy: pre-specified-planning
  description: high_renewables
  filename: ../energy_supply/strategies/high_renewable.csv
  model_name: energy_supply
