decision_module: ''
description: ''
name: energy_supply_demand
narratives: {}
scenarios:
  es_prices: es_prices_dummy
  gva: gva_baseline
  population: pop_high
sos_model: energy_supply_demand
stamp: '2018-02-23T12:00:22.154Z'
timesteps:
- 2015
- 2020
strategies:
- strategy: pre-specified-planning
  description: high_renewables
  filename: high_renewables.yml
  model_name: energy_supply