kind: Model
apiVersion: v1alpha3
metadata:
  # You will probably want to update this metadata before uploading to DAFNI
  displayName: NISMOD2 - Energy Supply Model
  name: nismod-energy-supply
  summary: National Infrastructure Systems Model
  type: systems of systems
  description: "Energy Supply model from NISMOD2."
spec:
  command: [python3, job_processing_wrapper.py]
  inputs:
    env:
      - name: sector_model
        title: Energy Supply Sector Model
        desc: Pick one of the NISMOD2 energy_supply Sector Models to run
        type: string
        default: energy_supply_constrained
        options:
          - name: energy_supply_agent
            title: Energy Supply Agent
          - name: energy_supply_constrained
            title: Energy Supply Constrained
          - name: energy_supply_optimised
            title: Energy Supply Optimised
      - name: model_to_run
        title: Model Run
        desc: The name of the model run that is being executed
        type: string
        default: energy_supply_constrained
      - name: part_of_sos_model
        title: Part of SOS Model
        desc: "Is this model being run as part of a NISMOD2 Systems of Systems Model?"
        type: boolean
        default: false
      - name: use_generated_scenario
        title: Use generated scenario
        desc: "Is this run using a new generated scenario file?"
        type: boolean
        default: false
      - name: timestep
        title: Timestep
        desc: "Timestep to run the Model at if this is part of an SoS Model"
        type: integer
    datasets:
      # All the below UUIDs are for DAFNI's staging site, they will need updating before uploading to DAFNI production
    - uid: 1c25acf9-8f35-413f-8995-93ac4876eeac
      versionUid: 22bf0529-7f21-43d8-bb11-ce84dbffa123
      path: scenarios/
    - uid: 7a347b45-0f05-42cd-8e34-25210be62f69
      versionUid: 0bd574bd-d2dd-41d4-90aa-19b81c6aefda
      path: energy_supply/
    - uid: 84a711c4-2705-4f7a-b974-7aea05cafe0f
      versionUid: 41de0075-42aa-45a1-b95a-a8d9fb81fc62
      path: lads/
    - uid: a8c81d5b-5adc-4a03-8d1b-8662829e09b1
      versionUid: 35e26802-f094-41e2-81a5-b8d8698caf81
      path: lads/
