kind: Model
apiVersion: v1alpha4
metadata:
  displayName: NISMOD - Adaptors (model v2.4.0 build 3)
  name: nismod-transforms
  summary: National Infrastructure Systems Model
  type: systems of systems
  description: >
    This "model" contains the adaptors used to convert data exchanged between
    NISMOD models. They allow aggregation and disaggregation across regions,
    intervals and categories, for example converting from Local Authority
    Districts to Energy Hub Regions, or from hours in a year to four seasonal
    representative weeks, as well as simple unit conversion.

    Source code: https://github.com/nismod/nismod2
spec:
  inputs:
    env:
      - name: model_to_run
        title: Model Run
        desc: The name of the model run that is being executed
        type: string
      - name: use_generated_scenario
        title: Use generated scenario
        desc: "Is this run using a new generated scenario file?"
        type: boolean
        default: false
      - name: transforms_to_run
        title: Conversion steps to run
        desc: A list of the conversion steps to run
        type: json
        schema:
          type: array
          minItems: 1
          items:
            type: string
      - name: timestep
        title: Timestep
        desc: "Simulation year (used if run as part of a NISMOD Systems of Systems Model)"
        type: integer
    dataslots:
      - name: Scenario Data
        description: >
          NISMOD scenario data pack. Should contain socio-economic scenarios
          (population, GVA) and energy (fuel) price scenarios.
        default:
          - uid: 1237868f-52ea-416c-9087-eef9dbde429d
            versionUid: cef750da-b26d-4da1-b67b-871281c3d551
        path: scenarios/
        required: true
      - name: Transport Model Data
        description: >
          NISMOD transport data pack. Should contain full data setup for the
          transport model including network shapefiles, base year population and
          GVA, origin-destination matrices, engine fuel efficiencies, and future
          interventions (new road links, new stations, congestion charging zones).
        default:
          - uid: dbfe6814-3fd3-4e94-8c30-ccfec60c9989
            versionUid: df234857-a622-4b83-bec1-c72b1c7ed8b6
        path: transport/
        required: true
      - name: Energy Demand Model Data
        description: >
          NISMOD energy demand data pack. Should contain full data setup for the
          energy demand model including hourly interval definitions, technology,
          efficiency, end-use and service parameters to explore changing energy
          demand, historic temperature time series, scenarios of future
          temperature (aligned with the wind speed and insolation time series
          used to model renewables in energy supply), base year national and
          subnational energy consumption estimates, load profiles, and base year
          population and floor area.
        default:
          - uid: 180c33ea-592c-473e-b54b-692c2cc534dd
            versionUid: f63c24ec-4262-4f88-ac1c-28fd47345de1
        path: energy_demand/
        required: true
      - name: Energy Supply Model Data
        description: >
          NISMOD energy supply data pack. Should contain full data setup for the
          energy supply model including model configuration for the electricity
          and gas network in the base year and possible future interventions -
          generation, transmission, interconnectors, gas storage and terminals,
          and heating supply technology options.
        default:
          - uid: aa16e098-452b-496a-b3ae-dc95acd6959b
            versionUid: 3d3380bc-2147-46a8-b1d6-74e755f3726b
        path: energy_supply/
        required: true
      - name: ET Module Data
        description: >
          NISMOD Energy Transport Module data pack. Should contain full data
          setup for the model, including charging schedule parameters and
          vehicle trip starts and consumption scenarios (test outputs from the
          Transport model used to test running the et_module standalone).
        default:
          - uid: ed671698-069c-40f4-8645-bf08e45634fb
            versionUid: 66382de9-bef7-45ab-b729-dbfc1d01007f
        path: et_module/
        required: true
      - name: LAD boundaries
        description: >
          LAD boundaries - shared definition for data exchange between models.
        default:
          - uid: 36adf09d-7657-4e46-a6d8-55dde43cbe51
            versionUid: 4050b797-0a12-4b86-9ca3-9edfde3aeb6d
          - uid: 40ba1196-6ee1-4be3-b813-471934bf3acd
            versionUid: adce60be-2019-4ec8-8f61-a297c5a26cc5
        path: lads/
        required: true
