kind: Model
apiVersion: v1alpha4
metadata:
  # You will probably want to update this metadata before uploading to DAFNI
  displayName: NISMOD2 - High Resolution Energy Demand Model (HIRE, v0.9) 
  name: nismod-energy-demand
  summary: National Infrastructure Systems Model (preliminary upload No.9)
  type: systems of systems
  description: "Energy Demand model that forms part of NISMOD2"
spec:
  command: [python3, job_processing_wrapper.py]
  inputs:
    env:
      - name: sector_model
        title: Energy Demand Sector Model
        desc: Pick one of the NISMOD2 energy_demand Sector Models to run
        type: string
        default: energy_demand_constrained
        options:
          - name: energy_demand_constrained
            title: Energy Demand Constrained
          - name: energy_demand_unconstrained
            title: Energy Demand Unconstrained
      - name: model_to_run
        title: Model Run
        desc: The name of the model run that is being executed
        type: string
        default: energy_demand_constrained
      - name: part_of_sos_model
        title: Part of SOS Model
        desc: "Is this model being run as part of a NISMOD2 Systems of Systems Model?"
        type: boolean
        default: false
      - name: use_generated_scenario
        title: Use generated scenario
        desc: "Is this run using a new generated scenario file?"
        type: boolean
        default: false
      - name: timestep
        title: Timestep
        desc: "Simulation year (used if run as part of a NISMOD Systems of Systems Model)"
        type: integer
    dataslots:
        # All the below UUIDs are for DAFNI's staging site, they will need updating before uploading to DAFNI production
      - name: Scenario Data
        description: >
          NISMOD scenario data pack. Should contain socio-economic scenarios
          (population, GVA) and energy (fuel) price scenarios.
        default:
          - uid: 1237868f-52ea-416c-9087-eef9dbde429d
            versionUid: 5afbfaa2-a351-4a04-9b79-efa6a194aa60
        path: scenarios/
        required: true
      - name: Energy Demand Model Data
        description: >
          NISMOD energy demand data pack. Should contain full data setup for the
          energy demand model.
        default:
          - uid: 180c33ea-592c-473e-b54b-692c2cc534dd
            versionUid: f63c24ec-4262-4f88-ac1c-28fd47345de1
        path: energy_demand/
        required: true
      - name: LAD boundaries
        description: >
          LAD boundaries - shared definition for data exchange between models.
        default:
          - uid: 36adf09d-7657-4e46-a6d8-55dde43cbe51
            versionUid: 4050b797-0a12-4b86-9ca3-9edfde3aeb6d
          - uid: 40ba1196-6ee1-4be3-b813-471934bf3acd
            versionUid: adce60be-2019-4ec8-8f61-a297c5a26cc5
        path: lads/
        required: true
